### ISSUE TITLE
Build about:preferences as a Settings app

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#1]
_From @paulrouget on November 25, 2014 2:31_

Prefs should use the settings API. The UI should be displayed as an app inside the browser itself (like about:preferences in firefox)

_Copied from original issue: paulrouget/firefox.html#1_

**Comment by paulrouget** [comment]
_From @MichaelKohler on December 10, 2014 21:26_

What preferences do we want for a start?

**Comment by paulrouget** [comment]
Which stylesheet to load. If you look at `index.html`, you'll see 2 stylesheets: `default` and `dark`.

**Comment by paulrouget** [comment]
_From @PalmerAL on January 3, 2015 21:22_

Settings is listed as a permission in the app manifest, but trying to use the settings API gives an error "navigator.mozSettings is undefined". What is the correct way to get this to work?

**Comment by paulrouget** [comment]
Right. I need to enable settings in the runtime.

**Comment by Gozala** [comment]
@paulrouget is `about:preferences` different from `about:settings` or can we close this one now ?

**Comment by paulrouget** [comment]
Yeah, I think what we have is good enough for now.
