### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by nt1m** [mozilla/browser.html#105]
- [ ] Window can't be dragged
- [ ] Window controls don't work
- [ ] Window controls are on the left
- [ ] Graphic glitches everywhere
- [ ] No window shadow and border

**Comment by paulrouget** [comment]
For now we only support osx 10.10.

**Comment by Gozala** [comment]
No point in keeping this open until we start supporting other OSs.

**Comment by Coder206** [comment]
@Gozala @paulrouget Can I help out on getting this cross platform?

**Comment by paulrouget** [comment]
> @Gozala @paulrouget Can I help out on getting this cross platform?

It is already.
