### ISSUE TITLE
Show tab shade when creating a new tab or location bar is focused

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#110]
Try `cmd+t, cmd+t` & you wind up with multiple blank tabs but no visual feedback on subsequent tab openings seems like we can do better. @gordonbrander what do you think ?

**Comment by gordonbrander** [comment]
This is not really a case that would happen with the intended tab behavior (see https://github.com/mozilla/browser.html/issues/112). We should talk about whether we think we can realistically try the new tab model in Q1. If not, we can figure out how to mitigate things like this.

**Comment by gordonbrander** [comment]
@Gozala actually, forget what I just said. This stems from an interrelated issue:
The tab shade should be shown when you create a tab because the location bar is focused. When the location bar is focused, the tab shade should show.

**Comment by Gozala** [comment]
This is no longer the case since new tab = dashboard
