### ISSUE TITLE
First render jank

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#121]
Steps to reproduce: hit `f5` rapidly and repeatedly to see first render.

- There is a black box at the top.
- Top bar appears to "drop down".
- Page flickers on first render

Overall effect is a lot of visual noise.

**Comment by paulrouget** [comment]
So this happens between the moment gecko renders the cocoa window and the first paint of the iframe. OSX doesn't like empty windows for some reason (see the `wtf macos` message in shell.html). I'd like to first paint to includes the app. We'll see later how we can get there as it's not trivial.

**Comment by paulrouget** [comment]
I figured out an ugly hack.

**Comment by paulrouget** [comment]
Commit 0a03e55d7039e4437055e8651335b43b454d1945 and part 4 of bug 1134106 will make the situation much better. We still have a white screen for ~200ms still, but we will address later.

**Comment by paulrouget** [comment]
Much better with latest build.
