### ISSUE TITLE
input fields have unnecessary shadows

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#126]
I believe it's artefact of b2g

![screen shot 2015-02-19 at 16 28 30](https://cloud.githubusercontent.com/assets/21236/6279316/7482e35a-b854-11e4-8b7d-bf5a28a76e58.png)

**Comment by paulrouget** [comment]
I think its the default content style:

```
background: white linear-gradient(rgba(115,115,115,0.5) 0, rgba(215,215,215,0.5) 3px, rgba(255,255,255,0.2) 16px);
```
We should use FIrefox' content.css, not the one provided by b2g.

**Comment by gordonbrander** [comment]
@paulrouget Is this fixed in Graphene?

**Comment by Gozala** [comment]
We can test that with `data:text/html,<input%20value=hello/>`

**Comment by paulrouget** [comment]
Fixed by PART 2 in https://bugzilla.mozilla.org/show_bug.cgi?id=1134106
