### ISSUE TITLE
How to use on OSX 10.9?

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#133]
When I try to run, I get this error:

<code>
Error getting tracking ID [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getIntPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://b2g/content/settings.js :: setUpdateTrackingId :: line 20"  data: no]
JavaScript error: resource://gre/modules/FileUtils.jsm, line 1: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]
</code>

And b2g just shows a blank white window with a black bar at the top.

**Comment by paulrouget** [comment]
Builds are not ready yet. Still working on it.
