### ISSUE TITLE
Only show location bar after distance/time of upward scrolling.

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#135]
We need to walk this line:

- As a user reading, I want to adjust the page slightly while reading, without being distracted by controls.
- As a new user trying to get back to the controls, I want them to reappear when I am confused. I scroll back up because I saw them go away upwards.

The solution could be to show the location bar after `n` seconds of time or distance scrolling. I'm not sure what the right approach is yet. __Let's hold off on this while I think of the right heuristic__.

**Comment by KevinGrandon** [comment]
We currently use the same scrollgrab effect in the FirefoxOS browser, and have a similar interaction problem there. I'm interested in whatever heuristic you come up with, and wondering if it would apply to mobile as well. We might need some new hints for the platform to come up with a minimum delay or distance.

**Comment by paulrouget** [comment]
@gordonbrander Do we still want to implement the hotzone thing?

**Comment by gordonbrander** [comment]
@paulrouget yes, but this is a different issue. Hotzone bug is here https://github.com/mozilla/browser.html/issues/96.

**Comment by gordonbrander** [comment]
No longer applies.
