### ISSUE TITLE
Tabs should not always be created at the end of the tabstrip

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#14]
_From @paulrouget on December 11, 2014 9:51_

Tabs opened from a tab should added to the right of the parent tab, unless there is already a child tab. In this case it should be added to the right of the last child tab.

_Copied from original issue: paulrouget/firefox.html#47_

**Comment by paulrouget** [comment]
What is described there: https://bugzilla.mozilla.org/show_bug.cgi?id=465673

**Comment by paulrouget** [comment]
_From @bombsite on December 17, 2014 19:52_

I think I'm misunderstanding the architecture of the project.
In the iframedeck, the way I understand is that the 'parent' that holds all the iframes controls the UI, and the list tabiframearray is simply just a list of all the tabs that are open.
I thought that it'd be a matter of using insertBefore instead of appendChild as well as putting the tabiframe into the correct position in the list. Is that correct? or am I simply misunderstanding?

**Comment by paulrouget** [comment]
You're right. iframedeck only support appending at the end. So we need an option to append a tab anywhere in the array, and the `add` notification sent by iframedeck should include the position of the new tab.

**Comment by gordonbrander** [comment]
No longer applies. Closing.
