### ISSUE TITLE
Browser window should never have a dashed outline

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#140]
Sometimes clicking a `tab` I believe selects the `document.documentElement` (which is `html` element) that causes window to get a dashed outline.

I believe we should be able to style it so that outline won't be present.

**Comment by Gozala** [comment]
Assigned to @gordonbrander as he said he's going to take care of it.

**Comment by paulrouget** [comment]
> I believe we should be able to style it so that outline won't be present.

I would prefer if we could focus something useful instead.

**Comment by Gozala** [comment]
I believe this was fixed, can't see it happening any more.
