### ISSUE TITLE
Progressbar prevents window dragging (just from the left empty zone in the navbar)

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#146]
While the page is loading, the position of the progressbar is `-460px`. It overflows. The navbar is `overflow:hidden`. So we don't see the navbar, but because of the way window dragging works, the progress bar "covers" the dragging area.

**Comment by gordonbrander** [comment]
C++ code needed

**Comment by paulrouget** [comment]
We use a different progressbar now.
