### ISSUE TITLE
servo support

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#15]
_From @pixelr0 on December 11, 2014 13:50_

running with a servo back end 

_Copied from original issue: paulrouget/firefox.html#50_

**Comment by paulrouget** [comment]
_From @Yoric on December 11, 2014 14:24_

Are there missing features in Servo?

From the top of my head, we rely on:
- having a runtime;
- canvas;
- iframe mozbrowser;
- javascript 1.8;
- lots of CSS and DOM.

**Comment by paulrouget** [comment]
_From @jdm on December 11, 2014 14:44_

We're likely missing JS 1.8 features (since we're running on a 2.5 year old version of SM); we have a PR that adds some basic canvas support; we don't have iframe mozbrowser (and iframes in general are undersupported right now).

**Comment by paulrouget** [comment]
What's coming:
* shadow DOM (#6)
* settings API (#1)

**edit** (Yoric) added links

**Comment by paulrouget** [comment]
We can do without most of these features, except the Browser API (mozbrowser).

**Comment by paulrouget** [comment]
_From @jdm on December 11, 2014 15:44_

WebComponents will stop us in our tracks unless we can find a way to inject a working polyfill at the same time.

**Comment by paulrouget** [comment]
_From @Yoric on December 11, 2014 15:57_

JS 1.8 is not critical, I'm sure that dependency could be removed in ~1h.

**Comment by paulrouget** [comment]
_From @Yoric on December 11, 2014 20:16_

Apparently, WebComponents has [polyfills](http://webcomponents.org/polyfills/), so that shouldn't be a blocker.

**Comment by paulrouget** [comment]
_From @eddyb on December 13, 2014 7:34_

I am this -><- close to having Polymer run under Servo, the resource loading (HTMLImports) works, but I'm stuck on an invisible wall (again) trying to get it to take effect and finish its bootstrapping process.
Will report more progress as it happens.

**EDIT**: and for our final trick, well, this was embarrassing, but servo was missing load events for stylesheets - not a big deal:
```js
setTimeout(function() {
    [].forEach.call(document.querySelectorAll('link[rel=stylesheet]'), function(e) {
        e.dispatchEvent(new Event('load'));
    });
}, 10000)
```
[(sneak peek)](https://i.imgur.com/DtXssgU.png)

**Comment by paulrouget** [comment]
I was hesitant to use web components  in Firefox.html, but if Polymer can work, I think we should try to use them as much as possible. Already pushed some code that uses `registerElement` (see `js/tabiframe.js`).

I'm mostly worried about web APIs like the settings and browser APIs.

What's the status of regular the `<iframe>` tag? And how much work would it be to support the browser API (see `dom/webidl/BrowserElement.webidl`).

**Comment by paulrouget** [comment]
_From @jdm on December 15, 2014 14:47_

iframes are a high priority but support is not great at the moment. I don't anticipate supporting the Browser API to be very difficult.

**Comment by eddyb** [comment]
Since this notified me, I have to wonder why the repo was copied instead of being properly transferred/renamed?

**Comment by paulrouget** [comment]
I didn't know it was possible :) That's why.

**Comment by Ap0ph1s** [comment]
When do you think Servo can be implemented in browser.html?

**Comment by jdm** [comment]
Probably closer to months rather than weeks.

**Comment by andreasgal** [comment]
browser.html is meant to be the way of implementing a UI for servo, but as @jdm said it wil take at least a few months to get there.

**Comment by Ap0ph1s** [comment]
Well, its better than nothing, im running windows and Servo isnt really for windows(for debugging i think) according to its gitrepo

**Comment by paulrouget** [comment]
it works now.
