### ISSUE TITLE
While selecting tabs, theme is not updated

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#150]
STR:
- open cnn.com
- open youtube.com
- active last tab (youtube.com)
- theme is red
- Press control tab, but do not release control
- medium.com thumbnail is selected (tab is not active)
- theme is still red

Not sure if we want to keep it that way or not. It's just weird to see medium.com with the youtube theme.

**Comment by Gozala** [comment]
@paulrouget originally it was switching along with thumbnails, but @gordonbrander asked me to change to this behavior instead.

**Comment by paulrouget** [comment]
wont fix then.
