### ISSUE TITLE
History API

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#153]
Need this for https://github.com/mozilla/browser.html/issues/11.

**Comment by gordonbrander** [comment]
@Gozala I would like to get something simple in place. What if we build a store on top of Pouch DB, but don't bother hooking up a backend until later?

**Comment by Gozala** [comment]
Work in progress implementation is in #373

**Comment by gordonbrander** [comment]
@Gozala is this item finished?

**Comment by Gozala** [comment]
@gordonbrander I think so, of course there is bunch we could improve but I would track those separately.
