### ISSUE TITLE
Add support for extended mouse buttons for navigation

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#16]
_From @johndrinkwater on December 12, 2014 14:33_

Had a look at adding forward/backward mouse buttons for history navigation, but js doesn’t get button presses.

_Copied from original issue: paulrouget/firefox.html#58_

**Comment by paulrouget** [comment]
Hmm… which OS? Do you know how these events are sent to the operating system? Are they keyboard media keys events?

**Comment by paulrouget** [comment]
_From @johancz on December 12, 2014 22:59_

http://msdn.microsoft.com/en-us/library/ms646245%28VS.85%29.aspx could be relevant here. I believe it's the "XBUTTON1" and "XBUTTON2" values.

edit: also https://bugzilla.mozilla.org/show_bug.cgi?id=360731

**Comment by paulrouget** [comment]
I might be mistaken (just quick looked at Gecko's code): apparently, the button is not expose as a keyboard event. I think Gecko calls a JS function from the top level window (`BrowserBack`). Maybe it's better to report such button as a DOM event. Does the DOM 4 spec describe such button?

**Comment by paulrouget** [comment]
_From @jdm on December 15, 2014 14:58_

https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3Events-key.html#keys-browser describes a `BrowserBack` key.

**Comment by johndrinkwater** [comment]
Sorry with the late reply… Under Linux, it is native using mouse button presses, with back on mouse button 8, forward on button 9.

**Comment by Gozala** [comment]
@paulrouget do we need to keep this issue open ? Or do we plan on doing anything with this issue ? If not I think we should close it.
