### ISSUE TITLE
When hovering a link, show the URL in the location bar

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#165]
Depends on bug 1126215.

**Comment by gordonbrander** [comment]
I'm ok with this idea, but what happens when the location bar is hidden? I wouldn't want to show it when hovering over a link.

**Comment by Gozala** [comment]
@paulrouget I would like to get this but I'm not sure how I can find out if URL is being hovered. I think this requires #332 or something from platform.

**Comment by paulrouget** [comment]
See first comment.

**Comment by gordonbrander** [comment]
No longer applies.
