### ISSUE TITLE
It's possible to pan the top level iframe (navbar disappearing)

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#166]
So it's possible to pan the top level iframe, even though touch events are disabled. It's a gecko issue. This explains why sometimes the navigation bar disappear.

**Comment by paulrouget** [comment]
My guess: in htmlrunner, touch events were enabled. So the panning code would pan on touch events. But there was no touch events happening, so no pan. Now we disabled touch events. Panning code falls back to mouse events.

**Comment by paulrouget** [comment]
(confirmed)

**Comment by paulrouget** [comment]
Patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1138252

**Comment by gordonbrander** [comment]
I think this is related? https://github.com/mozilla/browser.html/issues/168

**Comment by paulrouget** [comment]
Closing as it will be fixed on the runtime side.
