### ISSUE TITLE
Hovering the bottom edge of the title bar causes tab strip to show

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#167]
Hovering anywhere to the right of the location bar causes tab strip to show. This should not be.

**Comment by paulrouget** [comment]
Meh. Regression from 6bed9e73d0f7224ba41577e742eddd1fda55416c?

**Comment by gordonbrander** [comment]
It seems to happen only when hovering over the bottom 5px to the right of the location bar.

**Comment by paulrouget** [comment]
Indeed.

**Comment by paulrouget** [comment]
progressbar?

**Comment by gordonbrander** [comment]
Happens on both left and right

**Comment by gordonbrander** [comment]
I'll bet so. Looking into it.

**Comment by gordonbrander** [comment]
Progress bar. We should display: none; at end of animation.

**Comment by paulrouget** [comment]
Make it `progress-events:none` instead.

**Comment by paulrouget** [comment]
Wait… no, we should just move the progressbar out of the locationbar.

**Comment by gordonbrander** [comment]
Moved progress bar out of location bar. Fixed the CSS issue.
