### ISSUE TITLE
Lock icon in navigation panel makes content jump

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#180]
I noticed that sometimes when I switch between tabs content would move a pixel or two, I just realised it happens when I switch between tabs where one is secure and other not. So my guess is it's lock icon from font awesome that causes elements to resize.

**Comment by paulrouget** [comment]
See commit dc5bebf

**Comment by paulrouget** [comment]
(which was supposed to fix that, at least on retina display)
