### ISSUE TITLE
FPS drops on ctrl-tab

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#190]
Thumbnails don't scale at 60 FPS if ctrl-tab is used. With mouse-over, no problem.

**Comment by paulrouget** [comment]
So I ruled out any of our JS code. This is a platform issue. Just running this code in scratchpad:
```
let tabS = document.querySelector('.tab.selected');
let tab = document.querySelector('.tab:not(.selected)');
tabS.className = 'tab';
tab.className = 'tab selected';
```
… FPS drops.

**Comment by paulrouget** [comment]
I'm getting the same assertion as in #202:

```
[Parent 4519] ###!!! ASSERTION: overwriting animated transform!: '!aLayer->AsLayerComposite()->GetShadowTransformSetByAnimation()', file /Users/paul/mozilla/gecko-projects/gfx/layers/composite/AsyncCompositionManager.cpp, line 961
```

**Comment by paulrouget** [comment]
Turning on APZC solves this issue.

Set `layers.async-pan-zoom.enabled` to `true`.

**Comment by paulrouget** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1141488

**Comment by gordonbrander** [comment]
@paulrouget hasn't this been fixed by the new Graphene build?

**Comment by paulrouget** [comment]
Yes.
