### ISSUE TITLE
Graphene scrolling freaks out on facebook.com

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#193]
Open http://facebook.com, make sure you're logged out. This generally seems to happen to me when the window is expanded to take up the full screen of my Mac Book Pro 16".

cc @paulrouget

**Comment by paulrouget** [comment]
It's a frontend bug, not a Graphene bug. It happens because we update `contentOverflows` more than once, and some pages change their layout on resize. So we should allow toggling `contentOverflows` only once.

**Comment by Gozala** [comment]
@paulrouget I see what you saying, but I'm not sure proposed solution is actually going to work:

- Single page apps like gmail fetch data on clicks and replace displayed UI, in turn you may initially set `contentOverflows` to `false` but then you may need to set to `true` if we drop those updates it's not going to work correctly for such websites.
-  I had other case in mind that I forgot while writing first one :(

**Comment by Gozala** [comment]
Ok so #348 does what @paulrouget suggested in the comment, I do not think it's ideal (see my previous comment) still better than what we have now though, so I think we can go with it for now.

**Comment by paulrouget** [comment]
This is not supposed to happen anymore.
