### ISSUE TITLE
Remove white border from tab close button

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#199]
Not supposed to be there and causes visual artifacts on Retina and normal screens.

**Comment by paulrouget** [comment]
I added it because of imgur.com. The background is black, so we don't see the close button. Maybe we should use 1px instead of 0.5px.

**Comment by gordonbrander** [comment]
1px might work

**Comment by gordonbrander** [comment]
or maybe I should have a light close button for `isDark` themes?

We'll keep running into edge cases like this (see also the loading bar). The eventual way I want to solve them is to have color functions that can calc distance from black and make a choice about what color to use for other interface elements.
