### ISSUE TITLE
GPU crash while using Graphene 39

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#200]
I'm not sure how to reproduce it. It happened while I had terminal window focused, Graphene in the background. Closed a terminal window tab and GPU crash happened.

**Comment by paulrouget** [comment]
I have the same issue. It's a probleme with OSX. You can actually reproduce this with a regular Firefox if you keep restarting it. The solution I found is to disable "Automatic graphics switching" in osx' Settings > Energy Saver.
