### ISSUE TITLE
Cmd-L should select the text in the location bar even if focused

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#203]
There are 2 approaches:

1. on `accel l`, do `querySelector('.urlinput').select()`
2. add a `selectAll` property to the state. Setting it to `true` on `accel l` and when rendering, update the selection. That means, it needs to be set to `false` as soon as the selection change. So we need to add an `onSelect` handler that will test the selection size. We also need to do that on `onKeydown`, `onClick` and on `onFocus`.

@Gozala what do you think?

**Comment by Gozala** [comment]
At some point I was planning on making Editable.selection that would be able to model full selection range in fact some of the code is there but we don't use & I have not properly tested it either:

https://github.com/mozilla/browser.html/blob/master/src/browser/editable.js#L13-L41

So I think we could either store model input field state into our app state (on pros size we'll be able to quickly restore it to exactly same thing) or we could just modify this `if` https://github.com/mozilla/browser.html/blob/master/src/browser/editable.js#L14 and just make some value that will force it to select all regardless of the previous value, etc.. In that case we would not have to track all the above mentioned events.

**Comment by paulrouget** [comment]
> or we could just modify this if https://github.com/mozilla/browser.html/blob/master/src/browser/editable.js#L14 and just make some value that will force it to select all regardless of the previous value, etc.. In that case we would not have to track all the above mentioned events. 

But how/wheb to reset the value to `false`? Otherwise it will selectAll all the time it's rendered.

**Comment by Gozala** [comment]
Was fixed by #230
