### ISSUE TITLE
Flicker of black when switching between iframes

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#205]
Switching between tabs results in flicker of black. With 2 tabs, this behavior is consistent.

Fabrice's hypothesis is that this is caused by the fact that we first hide the iframe, then show the next iframe, rather than showing, then hiding.

**Comment by gordonbrander** [comment]
Update: we actually change both iframes at the same time.

**Comment by paulrouget** [comment]
Well, not really. At the same time we:
1. hide the old iframe
2. display the new iframe
3. request the new iframe to be visible (setVisible)

We should do *3*, then on first paint, do *1* and *2*.

**Comment by gordonbrander** [comment]
I think this is a platform issue. I hacked together a branch that animates opacity rather than using hide/show and the flicker is still occasionally present.

**Comment by paulrouget** [comment]
Gordon, do you start animating on first paint? Try `iframe.addNextPaintListener()`, then start doing the animation or anything like that.

Also - I'm pretty sure if we set `dom.ipc.processCount` to `2`, it should be much better too.

**Comment by gordonbrander** [comment]
Paul says: it's not a platform issue. Workaround: only allow 2 processes to run.

**Comment by paulrouget** [comment]
Confirmed. `processCount = 2` makes the flickering disappear.

**Comment by paulrouget** [comment]
Alright, I'm not sure anymore about `processCount = 2`. I can't reproduce the black flickering anymore.

**Comment by paulrouget** [comment]
It still happens. Not always. It's more obvious when tabs are activated when selected.

**Comment by gordonbrander** [comment]
This was fixed some time ago.
