### ISSUE TITLE
False tab activation on app switch

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#206]
1. Hover over a tab
2. `cmd tab` over to another app
3. `cmd tab` back to browser.html

The tab you were hovering over, but did not select will be selected as browser.html switches to the background.

I took a quick look but couldn't figure out where this problem came from. cc @Gozala

**Comment by Gozala** [comment]
I think this happen because when tabstrip get's hidden, we activate selected tab. I'm don't recall why but my guess is we hide tabstrip (intentionally, or accidentally) when window looses a focus.

**Comment by Gozala** [comment]
This is no longer the case, presumably because because both design and implementation have changed significantly.
