### ISSUE TITLE
Order tabs LTR

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#215]
I made tabs RTL to match the direction of the back arrow. Web history is conceptually RTL with newest at R.

However, this is opposite of `alt tab` and traditional `ctl tab` direction. @Gozala and @paulrouget don't like this. I suspect they have a point. People who are used to those commands will probably have similar reaction.

Let's make tab order LTR (newest at far L) and I'll figure out how to reconcile spacial model with back button later.

**Comment by Gozala** [comment]
Fixed by #229
