### ISSUE TITLE
Smarter restore session mechanism

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#218]
Today, we just restore the state. We do not bump the version when required, which can break the app. So we need a smarter mechanism. Maybe just store a list of urls + selected index.

As it slows me down, I will disable session restore until this issue is fixed.

**Comment by paulrouget** [comment]
See 06589f7.

**Comment by Gozala** [comment]
I think we got better at bumping versions and also at filtering state that we can't restore. Reopen if you still feel we need to have it around.
