### ISSUE TITLE
If I leave browser open while mac is asleep it's unresponsive whet mac wakes up

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#221]
I usually notice that when I leave it over night, have not really tested if that 's still a case for short naps.

**Comment by Gozala** [comment]
It looks like this issue happens regardless of how long my mac was asleep & latest builds still have it.

**Comment by paulrouget** [comment]
Closing as it's a gecko issue that is also happens in current Firefox Nightly.
