### ISSUE TITLE
Sometimes, the awesomebar doesn't dismiss

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#227]

**Comment by paulrouget** [comment]
I think it's because the throttled `computeSuggestion` is called after the `resetSuggestion` call.

**Comment by gordonbrander** [comment]
Happens for me too.

**Comment by paulrouget** [comment]
Let's wait and see if PR #230 fixes it. It's a big rewrite, and I haven't experienced this bug with it.

**Comment by Gozala** [comment]
I believe it fixed it as I have not seen it again, let's reopen if we run into it again.
