### ISSUE TITLE
Tile loading doesn't handle redirects properly

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#235]
go to "mail.google.com" -> premade tile loads
go to "gmail.com" (redirects to mail.google.com) -> premade tile does not load

**Comment by paulrouget** [comment]
Dupe of #97

**Comment by PalmerAL** [comment]
I'm not sure this is the same thing. In this case, you are redirected to mail.google.com, which should then match the mail.google.com tile. This isn't related to domain matching.

**Comment by paulrouget** [comment]
Oh right. I read that wrong.

**Comment by Gozala** [comment]
This was fixed by this change https://github.com/mozilla/browser.html/commit/05932a6cdad9954a6c2d355d92e6889877848313#diff-ac64a61ab532164b9e3f853bfb7ee2d7R111 issue was that tile was fetched from `iframe.src` which was no longer a loaction of the page.
