### ISSUE TITLE
partial rendered UI + unable to render web pages [Ubuntu 15.04]

### ISSUE THREAD

**Issue by pixelr0** [mozilla/browser.html#24]
partial rendered UI + unable to render web pages [Ubuntu 15.04]
firefox nightly 64-bit/Ubuntu 15.04

http://i.imgur.com/BDLwkDO.png

~/Downloads/browser.html-master$ ~/Downloads/firefoxN/firefox -app $PWD/runtime/application.ini $PWD/apps/browser/manifest.webapp

    (process:17654): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Register manifest at /home/pixel/Downloads/firefoxN/browser/chrome.manifest
    document readyset frame to be an app: 1006
    ############################### browserElementPanning.js loaded
    ######################## BrowserElementChildPreload.js loaded
    JavaScript error: chrome://global/content/BrowserElementPanning.js, line 91: TypeError:    evt.target.ownerDocument is null

http://i.imgur.com/BDLwkDO.png

**Comment by paulrouget** [comment]
Fixed fb60e6f86e5fac378d82465ca1777bf18e874210
