### ISSUE TITLE
Hitting space bar doesn't scroll active page

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#245]
- Hit space while on website

**Comment by gordonbrander** [comment]
Hmm, this isn't always the case. It must have either been the website I was on or some bug with the runner.

**Comment by paulrouget** [comment]
It happens when the iframe is not focused.

**Comment by Gozala** [comment]
No longer happens, presumably because #795 fixed all (to my knowledge) cases where iframe was not getting a focus back.
