### ISSUE TITLE
Proposal for some architectural changes

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#250]
I decided to start this issues after some discussion with @paulrouget about architecture and code base. I think we (at least I) learned few things from the experience with a current code base & I would like to address some of the constraints & ambiguities. What will follow in the comment is more of a brain dump & likely some followup discussion.

**Comment by Gozala** [comment]
The reason we use [immutable data structures](http://facebook.github.io/immutable-js/) for a several reasons:

1. To make it easy to reason about app state by avoiding out of sync situations, caused by mutations from one part of code that was not noticed by other part of the code.
2. Immutable data structures make it really easy to represent whole application state as a single data structure, and updates could be made deep down in the nested structure that would produce whole new structure as the root with common parts shared with previous. In other words making deep down updates very convenient.
3. By leveraging immutable data structures we take advantage of predefined & optimised [shouldComponentUpdate](http://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate) to gain performance boost by not re-triggering components who's state has not changed, this is explained in further details by [PureRenderMixin](http://facebook.github.io/react/docs/pure-render-mixin.html)

Although since UI interaction need to cause state changes that somehow need to initiate re-render with another updated state, we employed [Cursors](https://github.com/facebook/immutable-js/tree/master/contrib/cursor) that is part of Immutable.js library that allows to present sections of the actual immutable data structure such that transformations of it will notify a [renderer](https://github.com/mozilla/browser.html/blob/master/src/browser/core.js) of a transformed state so it could re-render with updated state. Unfortunately use of `Cursor`s caused some ambiguity (for developers & the system):

1. It is not obvious when cursors should be used over plain data structures. Although [attempt](https://github.com/mozilla/browser.html/wiki/Design-F.A.Q.#q-how-do-i-cause-side-effect--re-render-) was made to make it more clear.
2. Cursors have a `read+write` semantics and when passed around it is not clear if they intended to be read from or to be written into.
3. Result of render purely depends on input meant for `read` anything `write` related does not need to re-render, but since cursors are `read+write` ones intended for `write` would cause re-renders as well. To avoid that we established [event handler passing pattern](https://github.com/mozilla/browser.html/wiki/Design-F.A.Q.#q-how-do-update-state-that-i-dont-need-to-render-) which makes things worse by having two different ways to update.
4. Reordering items cursor points to does not affect cursors equality check that later [causes issue](https://github.com/omniscientjs/omniscient/issues/89) that performs update on a structure on an out of date location. This is very likely to be fixed but even if it will it would cause re-render even if not really necessary because as pointed out earlier cursors have `read+write` semantics.
5. Attempts to do [async rendering failed](https://github.com/omniscientjs/omniscient/issues/83) given that state captured by previous render is out of date until next render. This can be resolved by separating `read` / `write` concerns as I'll describe later.
6. Most times [same functions](https://github.com/mozilla/browser.html/blob/master/src/browser/deck/actions.js) can be used on both cursors and plain data structures, but outcome will be different. When applied to a immutable data structure new structure will be returned but when applied to cursor in addition re-renders will be initiated. Further more [composed transformation functions](https://github.com/mozilla/browser.html/blob/master/src/browser/deck/actions.js#L151-L152) will cause multiple re-renders there for we tend to do `cursor.update(action)` instead to trigger just a single update.

**Comment by paulrouget** [comment]
Random thoughts (just taking notes for future discussions):
- enforce cursors
- better naming. I did change the names of many things at the beginning, but we can do much better. Also, we should introduce a dictionary (navbar vs locationbar, page-switch vs. tabstrip, webviewer vs. tab vs. iframes, …)
- the structure of the state should be documented somewhere, and any change to the state structure would require the doc to be updated
- make components more self-contained, isolate them in a components directory?
- get rid of `actions.js` files
- one CSS file per component, maybe use react for CSS

**Comment by Gozala** [comment]
Now that problem has being explained (cursors complect `read` & `write`) I think the solution requires separating `read` & `write` inputs. Which can be achieved by:

1. Passing only immutable data structures (not cursors) for inputs that will affect output of the render.
2. Use different mechanism for sending updates to the renderrer.

I have prototyped & illustrated this idea in the above mentioned issues, that you can find here:
http://jsbin.com/rodanajeya/3/edit?js,console,output

In nutshell what is changed is that along with input additional parameter `edit` is passed to a component that can be invoked with a function that takes current state and returns new state like if you want to increment counter you'd do `edit(state => state.set('counter', state.get('counter')))` or more simply `edit(state => state.update('counter', inc))` which solves all the issues described above.

It is also really simple (as you can see in jsbin)  to define helper functions that would create sub-edit functions to pass around scoped versions of `edit` to a subcomponents. So above counter update can be simplified further as:

```js
const  editCounter = subedit(edit, 'counter')
// in other component
editCounter(inc)
```

There for all operations will be expressed as transformations over immutable data structures, in order to cause a re-render operation (transformation functions) will be just send to a renderer that will apply it to the current state to produce new state and re-render.

**Comment by Gozala** [comment]
Alternative would be to use CSP channels as [illustrated by our own James Long](https://www.youtube.com/watch?v=W2DgDNQZOwo) which will in nutshell will be the same but will use channels as transport over just functions that have both pros & cons.

**Comment by Gozala** [comment]
> enforce cursors

I would rather ditch cursors for reasons described.

> better naming. I did change the names of many things at the beginning, but we can do much better. Also, we should introduce a dictionary (navbar vs locationbar, page-switch vs. tabstrip, webviewer vs. tab vs. iframes, …)

Agreed, or reduce number by settling to common ones. Initially I was avoiding to use terms like tab or iframe as IMO they carry legacy that may not make much sense in the new context. While I'd much rather not use names like `tabs` and `iframes`, I still would favour that over current state.

> the structure of the state should be documented somewhere, and any change to the state structure would require the doc to be updated

Makes sense.

> make components more self-contained, isolate them in a components directory?

I am not sure what you mean by making them self contained. Although I agree that current directory structure is quite chaotic.

> get rid of actions.js files

I am not sure I agree. In my mind at least those files were intended for defining actions that can / are performed on the data model. Quite often component A & B would perform same actions on the same data model without any direct relationship to each other. In fact a lot of times that helps avoiding circular dependency of components.

That being said some of the `actions.js` files end up containing extra or unrelated stuff to what I originally intended. I'd definitely like to clean that up. 

> one CSS file per component, maybe use react for CSS


I personally would like to try react for CSS as well, as it resolves some of the common pitfalls (well presented here https://speakerdeck.com/vjeux/react-css-in-js):

1. Global namespace / name collisions.
2. Dependency management (My a.js depends on a.css).
3. Sharing constants (across css & js).
4. Computations (compute faded style or inverse etc...)

Additionally that would enable us in a future to reload app by just importing new js file no need to deal with html or css.

**Comment by paulrouget** [comment]
I would also add: not use flex-box model. Servo doesn't support flex-box model yet. Flex-box model is cool and handy, but it doesn't make browser.html better.

**Comment by gordonbrander** [comment]
Most of what we do with Flexbox could be done with absolute positioning, since most of our UI does not interact via flow.

**Comment by paulrouget** [comment]
> Agreed, or reduce number by settling to common ones. Initially I was avoiding to use terms like tab or iframe as IMO they carry legacy that may not make much sense in the new context. While I'd much rather not use names like `tabs` and `iframes`, I still would favour that over current state.

https://github.com/mozilla/browser.html/wiki/Thesaurus

> > make components more self-contained, isolate them in a components directory?
>-
> I am not sure what you mean by making them self contained. Although I agree that current directory structure is quite chaotic.

I'd like to separate what is part of the framework from the components. `embedding.js`, `core.js`, `index.js`, … these shoud not be mixed with the components files.

> > get rid of actions.js files
>-
> I am not sure I agree. In my mind at least those files were intended for defining actions that can / are performed on the data model. Quite often component A & B would perform same actions on the same data model without any direct relationship to each other. In fact a lot of times that helps avoiding circular dependency of components.

Absolutely. Not saying these files are useless, it's just many "actions.js" files. Maybe we can rename them. Also, I'd like to extract the state initialization form these files if possible.

> That being said some of the `actions.js` files end up containing extra or unrelated stuff to what I originally intended. I'd definitely like to clean that up.-
>-
> > one CSS file per component, maybe use react for CSS
>-
>-
> I personally would like to try react for CSS 

WFM.

**Comment by paulrouget** [comment]
Can you guys look at this: https://github.com/mozilla/browser.html/wiki/new-design - let me know if it works for you.

**Comment by Gozala** [comment]
> Can you guys look at this: https://github.com/mozilla/browser.html/wiki/new-design - let me know if it works for you.

For the naming consistency I'd suggest to rename `SuggestionsBox` to `SuggestionBox` and to rename `Navbar` to `NavigationBar`. Other than that looks good to me.

P.S.: I'm afraid react can't write a body as it needs to control all of the children under the root it writes to and giving react control of html element isn't going to work as either as requirejs mutates head and that confuses react.

**Comment by gordonbrander** [comment]
I'm fine with everything, but would prefer `WindowBar` (or something like that) to `Navbar`. Less prescriptive.

**Comment by gordonbrander** [comment]
Small idea: what if we wrapped the wordy DOM and Component configuration details in functions? Child view functions could be passed into parent view functions. You end up with this flat declarative `main.js`, where swapping views in and out for experiments is less error-prone.

```Main(
  Navbar(
    WindowControls(),
    LocationBar({placeholder: "Search the web..."}),
    ProgressBar()
  ),
  PreviewBox(),
  SuggestionsBox(Suggestion())
)
```
The idea is that the configuration for `LocationBar` or `PreviewBox` are contained within those view functions. Perhaps a _very small_ bit of configuration is exposed as function arguments. The functions would return a React view or a component.

**Comment by gordonbrander** [comment]
Regarding the `Veil` (overlay), let's make it generic so we can trigger it for any old component
example: if we want to show an alert dialog with a dark background, it should use Veil, not have its own.

**Comment by paulrouget** [comment]
I've updated the component structure in the wiki.

Now, I've also added a bare minimum state: https://github.com/mozilla/browser.html/wiki/new-design. We added and removed many useless properties in the current code base. I think what I'm proposing here is enough.

Notes:
* I want to get rid of `readyState`. It's a magic value that is used to reflect the `readyState` value of the `iframe` and also used for navigation (`goBack` / `goFwd`). It's confusing. I prefer to just have `isLoading` and `goBack=true/false`
* I removed the RFA value. It feels like a hack. I'm sure we can find a better way to animate the progressbar;
* we will use `typed-immutable` to enforce types

Can you look at this and tell me what you think?

**Comment by gordonbrander** [comment]
Is there a good reason to force Dashboard into WebViewBox? It behaves differently from other web views, so why not make it a separate component?

**Comment by Gozala** [comment]
@paulrouget can we avoid going to formal about it, I would much rather prefer to make changes and then document them as it's not yet obvious for me what we going to run into as we proceed. I actually wanted to structure each component somewhat along these lines:

```js
const HistorySuggestion = Record({
  href: String,
  text: String,
  selected: Boolean(false)
});

HistorySuggestion.render = ({text, selected, href}, {onActivate}) => DOM.p({
  key: `${text}@history`,
  className: classSet({
    suggestion: true,
    history: true,
    selected: selected
  }),
  onMouseDown: event => onActivate(href)
}, text);

const SearchSuggestion = Record({
  href: String,
  text: String,
  selected: Boolean(false)
})

SearchSuggestion.render = ({text, selected, href}, {onActivate, onSelect}) => DOM.p({
  key: `${text}@search`,
  className: classSet({
    suggestion: true,
    search: true,
    selected: selected
  }),
  onMouseDown: event => onActivate(href)
}, text);


const Suggestions = Record({
  isActive: Boolean(false),
  selected: Number(-1),
  entries: List(Union(HistorySuggestion, SearchSuggestion))
})
Suggestions.render = ({isActive, selected, entries}, {onOpen}) => DOM.div({
  className: ClassSet({
    suggestionscontainer: true,
    isActive: isActive && entries.count() > 0,
  }), 
}, DOM.div({
  className: 'suggestions',
  key: 'suggestions',
}, entries.map(entry => render(entry.set('isActive', selected === index), {onActivate: onOpen}))))
```

Where `render` implementation looks something along these lines:

```js
const render = (record, handlers) => {
  const type = record.constructor
  const component = type.render.component ||
                    (type.render.component = Component(type.render))
  return component(record, handlers)
}
```

This basically makes turns everything around to making component state model a primary actor, while render is basically function that maps state to HTML tree. It also get's rid of redundant `Component` wrapper that is all over the place right now.


Finally I imagine that all the actions that can be performed will also be defined similar to `render` for example:


```js
Suggestions.select = index => record => record.set('selected', index)
Suggestions.selectNext = record =>
  record.set('selected', record.entries.count() < record.selected + 1 ? record.selected + 1 : -1)
```

That way all state transitions are also defined along the component state and are well compatible with our current state transition API:

```js
onMouseover: _ => edit(Suggestions.select(index))
```

**Comment by Gozala** [comment]
> I want to get rid of readyState. It's a magic value that is used to reflect the readyState value of the iframe and also used for navigation (goBack / goFwd). It's confusing. I prefer to just have isLoading and goBack=true/false

I'm not fan of `readyState` either but I still have not came up with a better solution. This problem is actually inherent from the API exposed by DOM for iframes - like iframe state is not fully exposed in any way for example if iframe is navigating back how that state is exposed ? It is not only way of knowing that is that capturing somewhere fact that you have navigated it back, same goes for refresh and going forward etc... More I think about it more I'm convinced that goBack / goForward should be implemented at the higher level and goBack should just be change src to whatever it used to be before, meaning we should maintain history graph ourselves at the web viewer level and goBack should be just something like:

```js
WebViewer.goBack = record =>
  record.set('uri', record.history.entries.get(record.history.index - 1))
WebViewer.goForward = record =>
  record.set('uri', record.history.entries.get(record.history.index + 1))
```

Note this would have a benefit of preserving a navigation history across sessions, although we should either expose lower level API for loading from `bfcache` or handle `uri` changes to `goBack` `goForward` calls if that URI is in the history ?

**Comment by Gozala** [comment]
> I removed the RFA value. It feels like a hack. I'm sure we can find a better way to animate the progressbar;

Root problem here is actually the same as for `goBack` / `goForward` which is we do not get nearly enough state updates to render a reasonable progress bar. I do think we should tackle this problem same in similar way. Meaning we should either get enough progress updates from iframe or we should at least pretend that is the case. I think I may have pointed this somewhere already, but if it was up to me I would implemented something like a shared RFA scheduler to share it across all elements that need to simulate events. That way each instance of `IFrame` could schedule fake event (which does not really needs to be a dom event) dispatch with a progress update which we could also optimise to avoid dispatch on iframes that are not visible. That way singleton RFA scheduler could maintain last ID on it's own without even exposing it externally. As of progress bar it will end up being just a rendering of progress value on a current web view.

**Comment by Gozala** [comment]
Here is some comments on the state structure itself:

```js
    isSelected: false,
    isPreviewSelected: false,
```

It looks like we do have two different selections now, before we had two states `selected` & `active` which I personally found a lot more clear. Selected is a web view for which we display address and rest of the state while active is a web view which you currently see content. Only time active and selected get out of sync is during transition from one active web view to other active web view. Actions like `activate` also made sense which basically meant activation of currently selected web view.


```js
userinput: "foo",
```

We actually end up with two fields for the same thing `input` and `userInput` I would prefer name `input` but fine with either one.

```js
    url: "https://www.reddit.com/",
```

I noticed that `location` field is no longer preset. We do actually need both `location` and `uri`. The problem is `uri` is basically `iframe.src` while `location` is whatever is loaded and note exposed by iframe. If we just have `uri` we will end up with a problem where location changes we update uri to that location then we update `iframe.src` which will re-load the page. In other words we need to distinguish url entered by user and url that is loaded into iframe to only trigger src changes on user input and not the other.

It' probably reasonable to fix that at the `IFrame` level though by storing actually loaded `uri` into iframe "data-location" attribute or something only update "src" if `node.src !== dataset.location`.

**Comment by Gozala** [comment]
I also think web view state should be partitioned mainly because different components care about different parts of it. Like preview does not care about the progress or it's load state. It merely concerned about selected, active state and a thumbnail. While `WebView` (iframe part of it) does not really cares about the `thumbnail` or `userInput` or `securityState`. There for I feel like WebView state could be structured as a record of sub-states relevant to individual component.  I'm not sure what separation would make most sense or if separation is even worth it, I think keeping as you suggested for now is good enough.

**Comment by Gozala** [comment]
> Is there a good reason to force Dashboard into WebViewBox? It behaves differently from other web views, so why not make it a separate component?

This is a good point although issue here is really a vocabulary we use rather then anything else. Maybe we should rename `WebViewBox` to `ContentView` and in terms of state model rename `webViews` to just `views` or `contentViews` so it will be something like:

```is
const UIView = Union(CoreView, WebView)
const ContentView = Record({
  selected: Number(0),
  active: Number(0),
  entries: List(UIView)
})
```

In my mind `CoreView` implementations could be "about:settings", "dashboard" etc... while `WebView`s will really be our glorified iframes. In a future we could also add `AppView` for say pinned tabs or something along those lines.

**Comment by Gozala** [comment]
I do not like `TopBar` because it encodes placement in the UI into a name. I don't like it as placement may change and name will no longer make sense. I would even prefer something like `ControlBar` or `ActionBar` that encode role in the name instead of placement.

**Comment by gordonbrander** [comment]
@Gozala Agreed. I still think `WindowBar` is best, because this component handles the window controls and dragging.

**Comment by paulrouget** [comment]
(renamed TopBar to Windowbar)

**Comment by paulrouget** [comment]
> More I think about it more I'm convinced that goBack / goForward should be implemented at the higher level
> although we should either expose lower level API for loading from bfcache or handle uri changes to goBack goForward calls if that URI is in the history ? 

`bfcache` is irrelevant here. You just want the history entries and go through them.

But why would that help exactly? I'm trying to understand what's wrong with just calling `goBack`. Maybe we don't need to call `goBack` in the render function. The same way we don't have to animate the progressbar in the render function.

I'm afraid we're trying to be too smart about something that is, in fact, very simple. If you step back a bit a look at the problem, we just want to call `goBack` when the user clicks on the back button. Then all fall into places as `locationchange` is triggered.

> Note this would have a benefit of preserving a navigation history across sessions

This is not the same problem. Cache is not preserved for other reasons.

**Comment by Gozala** [comment]
> But why would that help exactly? I'm trying to understand what's wrong with just calling goBack. Maybe we don't need to call goBack in the render function. The same way we don't have to animate the progressbar in the render function.

We could do it and yes we could also use `locationchange` event in order to reset the state in which case it will work just fine. Never there less calling `goBack()` on iframe does not fits the data driven approach, as  there is no data associated with imperative call to goBack. Sure we could use `goBack: true` which to me not much better from `readyState: "goBack"` as in both cases it's just a hack to workaround the fact that iframe does not expose declarative API for this. What does make sense from data driven perspective  (ignoring the optimisation via bfcache) is to change `uri` of the web view to an `uri` of page from which it got to current one. I also take the fact that `goBack` is bound to the session as another indicator of the issue, if you refresh a browser.html you lost your back going ability because navigation history is not in a state and not exposed by an iframe, on the other hand if `goBack` was just change of the `uri` browser refresh or even load on a different machine won't have an effect on this as navigation history will be stored in the application state that we have control over.

**Comment by Gozala** [comment]
> > Note this would have a benefit of preserving a navigation history across sessions
> This is not the same problem. Cache is not preserved for other reasons.

I was not referring to cache reuse but rather to an ability to go back / forward. You should be able to go back even if that won't load from cache.

**Comment by Gozala** [comment]
To be clear I do not imply that `bfcache` and hiding navigation history under `goBack` / `goForward` API is the same issue. Quite the contrary actually, although sad reality is that without `bfcache` optimisation navigating back and forward will perform unacceptably which forces us to use `iframe.goBack()` instead of dealing with history on our own.
