### ISSUE TITLE
Resizing window or scroll during page load does not always work

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#255]
![screen shot 2015-03-14 at 12 27 56](https://cloud.githubusercontent.com/assets/21236/6653213/b326c2fe-ca45-11e4-985b-7a49b0880e09.png)

I'm under impression that content process for the iframe crashes that may explain the problem. And if this really a process crash it may also be the case that is what we observer in #219

**Comment by paulrouget** [comment]
Do you get the onerror message from the iframe?

**Comment by Gozala** [comment]
> Do you get the onerror message from the iframe?

I did not.

**Comment by Gozala** [comment]
Have not seen it in a while.
