### ISSUE TITLE
Sync gh-pages with travis

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#262]
I think Travis can automatically merge master into gh-pages, and run `npm install`.

I know nothing about these things. Can anyone help?

**Comment by gordonbrander** [comment]
This would be very cool. Let's not turn it on until after next week.

**Comment by donaldpipowitch** [comment]
Yeah, that should work, but I haven't done it myself yet. Maybe this helps to get started? https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db Doesn't look that hard. I can't do it myself as I visit Smashing Conf next week ♥
