### ISSUE TITLE
Session data bug

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#264]
With #252, it's apparently possible to end up in a state where the tab strip is never shown and it is impossible to create new tabs (happened twice so far). Only way to fix is to reset with shift-command-delete. Haven't found reliable steps to reproduce yet.

**Comment by Gozala** [comment]
@paulrouget @PalmerAL if you run into this again could you please paste state dump it can give a clue what's going on. You can do it by running following in the console connected with a webide

```js
JSON.stringify(state, null, 2)
```

**Comment by PalmerAL** [comment]
What's a good way to launch this then? In order to connect to webide, you have to (I think) run off of local host, but if you launch that from console, keystrokes in the window actually end up in console, making it impossible to use. Is there a way to run the command in the readme that lets keystrokes be applied to browser.html and not the terminal, or is there a way to do this with the github pages as the start manifest?

**Comment by paulrouget** [comment]
No need to run from local host. Devtools are started no matter what. Just run the app, then open WebIDE from a regular Firefox, and connect to localhost:6000

**Comment by Gozala** [comment]
I think the issue described maybe what the #268 is fixing. Although I'm not certain.

@PalmerAL 

>  where the tab strip is never shown and it is impossible to create new tabs (happened twice so far).

If that is the same issue I think what you may have bing observing is that address bar was in edit mode, and in that case hovering it does not bring up tabstrip (@gordonbrander is that desired BTW) although switching through should still be possible with keybindings. 

Also what do you meant by "impossible to create a new tab" ? Does `cmd + t` did nothing ? If that's a same bug as #268 I think you will get a new tab but you won't be able to type much as the selection bug will select whatever you type and you'll basically end up changing one character.


Does this sounds like what you have observed ?

**Comment by Gozala** [comment]
I've also created #269 to add a poor mans view-source or rather state-source so state dump could be obtained without having to open devtools.

**Comment by PalmerAL** [comment]
when this happens, cmd+t doesn't work. It just selects the URL (like cmd+l normally would).

**Comment by PalmerAL** [comment]
I'm thinking this may actually be caused by #271, as you can't create new tabs when the dashboard new tab is gone.

**Comment by PalmerAL** [comment]
However with that issue you can still see the tabstrip. Probably, this is #271 and #268 combined together.

**Comment by paulrouget** [comment]
Just happened to me: http://jsoneditoronline.org/?id=a01913a5da45e3c82782655f6b6145c6

**Comment by paulrouget** [comment]
Cmt-T still works thought. But tabstrip doesn't who up.

**Comment by paulrouget** [comment]
Pressing `F5` fixes the issue.

**Comment by Gozala** [comment]
> Just happened to me: http://jsoneditoronline.org/?id=a01913a5da45e3c82782655f6b6145c6

That is odd, as far as I can tell everything in state seems ok, one of the iframes should have focus and

**Comment by Gozala** [comment]
I don't think this is still happening, reopen if you see it again!
