### ISSUE TITLE
UX: can't see current tabstrip without moving the mouth or switching tab

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#265]
I don't always know exactly where I want to go next. Which tab. So I want to look at the tabstrip. There's no easy way to show it. Either move the mouse hover the navbar, which is not easy and slow, or press `ctrl-tab`, which actually does the job, but it activates the next tab, which makes the current tab not being the active one, which is confusing.

I know it's nit picking, but I would like to have a way to show the tabstrip the way it is right now.

**Comment by gordonbrander** [comment]
Yeah, I've been giving this some thought as well. Will revisit.

**Comment by paulrouget** [comment]
I explained more things in issue #288
