### ISSUE TITLE
Can't take screenshot unless iframe was ever displayed

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#266]
Now that we have session restore back on I was trying to figure out why we don't get thumbnails when you refresh. It looks like `.getScreenshot()` call remains forever pending if iframe always had `display: none`. Note that if iframe was displaying event once this issue no longer occurs.

I came to above conclusion by doing following reloading `browser.html` that already had some pages open with tabs tiles generated out of screenshots. After reload I connected with wedIDE & used console to try to `.getScreenshot()` note that calls to `setVisible` and `setActive` had no effect on the outcome. Finally after removing `hidden` attribute and then putting it back `.getScreenshot()` did succeed.

@paulrouget is this a bug that we can solve or a limitation of the platform ? If later then we should probably stack iframes on top of each other and and hide inactive iframes only if they were loaded.

**Comment by Gozala** [comment]
@paulrouget do we want to keep this one open ? Workaround in #277 works although I'd prefer if we could avoid such workarounds.

**Comment by paulrouget** [comment]
Let's keep this open.

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by Gozala** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1198503

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
