### ISSUE TITLE
Keep runtime separate ?

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#27]
Can we please keep runtime separate maybe link to it via submodule or something if necessary ? The reason I would prefer that is so that as I would like to avoid coupling it with browser.html too much. I would really like it to be on a par with node-webkit which is a porpular way to build desktop apps in node community.

Note that as we npm already takes care of dev dependency on NPM so it will take care of installing runtime so users won't have to deal with at at all.

I'm also more than happy to migrate runtime to mozilla organization, so we will all have a same control of it.

**Comment by paulrouget** [comment]
Yes. Go ahead a re-host firebox in your own repo.
