### ISSUE TITLE
Can't see theme switcher on small screen without resizing

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#270]
On my 11inc mac I can't see that there is a theme switcher unless I resize window to take most of the screen.

**Comment by paulrouget** [comment]
That's because of the default height of the window. @gordonbrander what should be the very first size of the window? (we will later restore width/height/sizemode, see #176 )

**Comment by gordonbrander** [comment]
Does it have to be a hardcoded width or can we define the size as a percentage of the screen size?

**Comment by gordonbrander** [comment]
Also, I can make a CSS fix for the theme switcher.

**Comment by gordonbrander** [comment]
I would prefer to start the browser with the window filling the screen. If we can't do that, 1024x768 might be a good starting size.

**Comment by gordonbrander** [comment]
Never mind. Can't easily fix the theme switcher occlusion with CSS. Since this is not the final theme interface, I would rather not spend time trying to fix it.

For now can we instead make the default window size larger? It should be anyway.

**Comment by paulrouget** [comment]
Size is restored now.

**Comment by gordonbrander** [comment]
This is hot 🔥🔥🔥
