### ISSUE TITLE
Flickering when hovering on dashboard tiles

### ISSUE THREAD

**Issue by fabricedesre** [mozilla/browser.html#272]
STR:
- open the new tab dashboard
- move over tiles at moderate to high speed.

There is some intermittent flickering, where it seems that we don't display the image at all, but only the text.

**Comment by gordonbrander** [comment]
@paulrouget mentioned this is a platform issue but he hasn't been able to trace the source yet.

**Comment by paulrouget** [comment]
I've been trying to reproduce in a recent build. I don't get flickering in the dashboard anymore. But I do get flickering in the tabstrip.

**Comment by paulrouget** [comment]
Appears to be fixed. If anyone can reproduce in a recent build, feel free to re-open.
