### ISSUE TITLE
Full screen toggle is broken

### ISSUE THREAD

**Issue by fabricedesre** [mozilla/browser.html#273]
At least on linux, this doesn't work anymore.
Gecko receives a message: |Got a mozContentEvent: toggle-fullscreen-native-window| but we're not doing the right thing anymore...

**Comment by paulrouget** [comment]
@fabricedesre https://bugzilla.mozilla.org/show_bug.cgi?id=1134106#c10

**Comment by paulrouget** [comment]
I think it works now.
