### ISSUE TITLE
Clicking a result in the awesomebar doesn' t work

### ISSUE THREAD

**Issue by fabricedesre** [mozilla/browser.html#274]
STR:
- start with a fresh profile
- enter mozilla.org in the address bar (the site loads normally)
- focus the address field again, type any key
- click on any suggestion from the awesome list.

Expected:
- we load the new page

Observered:
- nothing happens

**Comment by gordonbrander** [comment]
I can't reproduce this.

**Comment by paulrouget** [comment]
Dupe #219
