### ISSUE TITLE
New graphics bugs in 0a1 Graphene build

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#278]
Running the latest Graphene build. I'm seeing new graphics bugs:

- The tabstrip flickers in and out when activated
- `.tabstripkillzone` animation is janky
- Website iframes occasionally flicker as well

@paulrouget The build from yesterday was working great. Can we keep it as a back-up for this week?

**Comment by gordonbrander** [comment]
This may actually be something else. After restarting my computer, the issues went away.

Maybe related: I have noticed that after running a long time (or perhaps after waking computer?), Graphene no longer responds to mouse.

**Comment by paulrouget** [comment]
There are backups in the `archives` directory.

**Comment by paulrouget** [comment]
I assumed disabling tiles would make things more stable, I was wrong. Also, `layout.reflow.synthMouseMove` was set to `true` for no good reason.

Sorry :/

New build coming.

**Comment by paulrouget** [comment]
I assumed disabling tiles would make things more stable, I was wrong. Also, `layout.reflow.synthMouseMove` was set to `true` for no good reason.

Sorry :/

New builds are available.
