### ISSUE TITLE
Trackpad gestures for OSX

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#280]
- Swipe LTR: back
- Swipe RTL: forward
- Pinch: Dashboard

**Comment by gordonbrander** [comment]
This should be part of a broader strategy of designing for multi-touch from the ground-up. So we should be thinking about touch screens too.

**Comment by Gozala** [comment]
I believe this would require access to a following events:
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mouse_gesture_events

Which as @fabricedesre pointed out are chrome only. We should probably expose them though.

**Comment by gordonbrander** [comment]
Do we not fire `touch` events for these, or are they considered a different class of event?

**Comment by paulrouget** [comment]
> Do we not fire touch events for these, or are they considered a different class of event?

Like Gozala said, we could expose the gesture events to content, or forward them from chrome's code. It's straight forward to do.

**Comment by paulrouget** [comment]
Events name are: `MozSwipeGestureStart`, `MozSwipeGestureUpdate`, `MozSwipeGestureEnd`, `MozSwipeGesture`MagnifyGestureStart`, `MozMagnifyGestureUpdate`, `MozMagnifyGesture`, `MozRotateGestureStart`, `MozRotateGestureUpdate`, `MozRotateGesture`, `MozTapGesture`, `MozPressTapGesture`
