### ISSUE TITLE
parts of url field text being copied to new tab

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#284]
Sometimes (this seems to be kind of intermittent), when I select some text in the urlbar field and then press cmd+t to create a new tab, part of the previous url (I think the selected content but I'm not quite sure) is copied to the new tab's urlbar field.

**Comment by gordonbrander** [comment]
I've also experienced this, but not sure how to reproduce it.

**Comment by gordonbrander** [comment]
Out of date.
