### ISSUE TITLE
Need to press ctrl-tab twice for the tabstrip to show up

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#287]
STR:
- hold Ctrl
- press tab once
- tabstrip doesn't show up
- press tab again
- tabstrip shows up

**Comment by Gozala** [comment]
I got this since I switched to a new build & do suspect that's some issue with rendering again, as even tabstrip appears it does some flickering.

**Comment by Gozala** [comment]
I just confirmed that it's indeed something with a new build as I don't have that issue with an older builds. Also @gordonbrander submitted #278 which could be related as well.

**Comment by paulrouget** [comment]
Dupe #278
