### ISSUE TITLE
"wtf osx" appears on first use

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#289]
...Because there is no interface in the cache. cc @jcarpenter
Can we solve this in some quick and simple way (showing a spinner in main HTML) before we get around to implementing ServiceWorkers?

**Comment by Gozala** [comment]
Wait how do you get that ? steps to reproduce ? or which build is it on ?

If I download latest 3 builds and have no profile I start and get no issues. If I'm offline app unfortunately quits but that's it.

**Comment by jcarpenter** [comment]
I pulled down `graphene-cmdclick-39.0a1-.mac64.dmg` from http://people.mozilla.org/~prouget/graphene/, opened the DMG and ran it (without dragging it into local Applications folder first)

**Comment by Gozala** [comment]
Note that if it loaded first time online, next time it does work fine

**Comment by jcarpenter** [comment]
Yep, I see that. I quite and re-opened, and everything works right away. It's just the first time load that is the issue.

**Comment by paulrouget** [comment]
Is the the message from the runtime or the frontend?
Anyway, I put a less offensive message in index.html.

**Comment by paulrouget** [comment]
(it was from the runtime)
