### ISSUE TITLE
Package calls "python" expecting python 2

### ISSUE THREAD

**Issue by parkerlreed** [mozilla/browser.html#297]
And on systems with python 3, "python" links to 3.
````
> browser.html@0.0.2 server /home/parker/browser.html
> python -m SimpleHTTPServer 8080

/usr/bin/python: No module named SimpleHTTPServer

npm ERR! Linux 3.19.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! browser.html@0.0.2 server: `python -m SimpleHTTPServer 8080`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser.html@0.0.2 server script 'python -m SimpleHTTPServer 8080'.
npm ERR! This is most likely a problem with the browser.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python -m SimpleHTTPServer 8080
npm ERR! You can get their info via:
npm ERR!     npm owner ls browser.html
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/parker/browser.html/npm-debug.log
````

````
$ python --version
Python 3.4.3
````

**Comment by paulrouget** [comment]
Found the arch user :)

We should use `python2` in `package.json`.

**Comment by parkerlreed** [comment]
;D You found me. Thanks for the reply.

**Comment by paulrouget** [comment]
60238ccd542337f8989b2d41119526445029122e

**Comment by JAStanton** [comment]
It's funny because I now have the same problem except this time with `python2`
https://gist.github.com/JAStanton/12990abdbf3e2bf5f090

**Comment by paulrouget** [comment]
So that didn't help (see issue #302). What is the right way to require python2?

**Comment by parkerlreed** [comment]
Weird. I thought that on systems with only python2 it still at least had a python2 symlink. Not sure how to solve this.

**Comment by necrophcodr** [comment]
Python2 is without a doubt the correct way to solve this issue. However, some distributions solve this issue by providing only a single python version at a time, or by providing a python symlink to the most recent distribution, and leaving other symlinks to only be the exact version (python2.7 or python3.4, for instance).

The correct way is either python2.7 or python2, but one could use the "python" symlink and write a slight bootstrap code to spring up the python2.7 installation if it is found.

**Comment by paulrouget** [comment]
We don't use python anymore.
