### ISSUE TITLE
python2: command not found

### ISSUE THREAD

**Issue by JAStanton** [mozilla/browser.html#302]
Full output:
https://gist.github.com/JAStanton/12990abdbf3e2bf5f090
Related bug:
https://github.com/mozilla/browser.html/issues/297

**Comment by paulrouget** [comment]
Reverted 60238ccd542337f8989b2d41119526445029122e

**Comment by paulrouget** [comment]
@jasonthomas You don't have `python2` in your path? osx, linux or windows?
