### ISSUE TITLE
`npm start` starts server, but doesn't stop it

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#306]
STR:
* `npm start`
* quit browser
* `ps aux|grep npm` shows a running instance of *ecstatic*
* `npm start` and `npm run start-server` will throw

**Comment by Gozala** [comment]
It does stops it if you `^ c` in the terminal but does not if you quit b2g. Not sure exactly that is a case to be honest. Currently `npm start` does `npm run start-server & npm run start-app` is there a way to run two processes such that exiting one would exit other as well ?

Only other thing I can think of is to do `npm run start-server | npm run start-app` instead but then output from first process is lost which could be ok though.

**Comment by Gozala** [comment]
Fixed by #381
