### ISSUE TITLE
devtools broken since about:settings landed

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#308]
It's because we add iframes with `mozapp="null"`. iframes that are not apps should not have the `mozapp` attribute.

**Comment by Gozala** [comment]
We should just fix `BeforeAppendAttribute` implementation which should have being doing what regular `Attribute` implementation does: https://github.com/mozilla/browser.html/blob/master/src/browser/element.js#L130-L132

So `null` would actually remove attribute rather then set it to `"null"`

**Comment by paulrouget** [comment]
79d904e52374947f861d4a8f87a1af823c92d988
