### ISSUE TITLE
Exectuing commands that aren't possible from HTML

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#31]
Once context menus and toolbar menus are ported over to app itself we would need to execute commands that aren't currently possible from HTML (as far as I know). Here are few that come into my mind:

1. Toggle devtools (maybe we could have a special URL and use window.open(devtoolsURL) for that.
2. Quit application (This is little tricky as multiple windows can be opened and they would need to communicate closure with each other).
3. Redo / Undo.
4. Hide app / Hide other apps (OSX).

I'm sure there will be more of these so we do need to find a way to deal with it. General approach could be to dispatch custom "command" event on the window itself that `shell.xul` could listen to and trigger appropriate actions. In a future we could wrap that up in a nicer HTML APIs when they come along.

**Comment by paulrouget** [comment]
We should use the chrome events. Like in Gaia.

**Comment by paulrouget** [comment]
Let file issues for each specific issues.
