### ISSUE TITLE
Tab approach b

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#313]
Based on the hypothesis below, I would like to try another approach to tabs.

- Order tabs by opened
- Tabs in a grid

Note this is not necessarily a final design, but a small, fast change that will allow us to compare against the order-by-access model we have now.

## Design notes

Goal:
- Allow for organization.
- Want a design that scales to enough tabs that you don't have to close them.
- Want a model that will allow planners to organize, without getting in the way of launchers and pruners.

Hypothesis: most tab use falls into one of these personas:

The launcher
- Opens things on the fly
- Doesn't have time to learn details of tab model, doesn't organize tabs
- Gets overwhelmed -- but worries about closing opened items because they're often punished for it by losing pages or data.
- Current tools are failing this user

The pruner
- Opens things on the fly
- Culls heavily (open -> read -> close) to avoid tab explosion
- Leans heavily on search and history autocomplete

The planner
- Leans heavily on spacial model
- Spends time to organize tabs and bend tab system to their will
- More than 6 tabs

(from feedback in https://github.com/mozilla/browser.html/issues/288 and discussion)

**Comment by paulrouget** [comment]
> The launcher
> The pruner
> The planner

Do we have an idea of how many people fall into each category?

**Comment by paulrouget** [comment]
Some (old) studies:
- http://dubroy.com/blog/how-many-tabs-do-people-use-now-with-real-data/
- http://dubroy.com/blog/my-talk-at-mozilla/ & http://dubroy.com/blog/my-chi2010-talk-a-study-of-tabbed-browsing/
- https://wiki.mozilla.org/Labs/Test_Pilot/Hypotheses
- http://scienceblogs.com/cognitivedaily/2008/12/19/casual-fridays-whos-tabhappy-a/

**Comment by paulrouget** [comment]
More:
* https://testpilot.mozillalabs.com/testcases/tab-open-close/results.html

**Comment by paulrouget** [comment]
Do all these profiles use some tabs as apps? Can we consider that, whoever you are, you will always want to separate tabs "as app", and tabs "as document"?

Is there a category of users who would treat *gmail.com* and *wsj.com* exactly the same way?

**Comment by Gozala** [comment]
> Is there a category of users who would treat gmail.com and wsj.com exactly the same way?

I know bunch of ppl who don't use tabs as apps, so there are some portion of such users no idea what would be the number of them though. That being said such users just don't care about the app notion so whatever we do in regards to apps should not conflict with their use I think.

**Comment by paulrouget** [comment]
* http://telemetry.mozilla.org/#filter=aurora%2F38%2FFX_SESSION_RESTORE_SESSION_LENGTH%2Fsaved_session%2FFirefox&aggregates=Submissions&evoOver=Time&locked=true&sanitize=true&renderhistogram=Graph

Most people don't restore their tabs. But again, this is the default behavior.

**Comment by paulrouget** [comment]
I'd like us to revisit the "goal" part here.

We want to address the tab explosion and organization issues, but I'm not sure this is the most important issue. Looking at the (old) data linked above, tab explosion is not a problem for a majority of people (given that maybe if the tabbar would not limit the number of visible tabs, people would use more tabs, but that's just a guess).

I'm not saying we should not address the tab explosion issue, but it should not be the most important thing that drives our design process.

Our tab model should be optimized for the most common task and the most expected feature: 1) keep track of tabs we want to read and app we want to keep open, 2) switch between them in an **efficient** way.

Comparing the latest mockups to a regular browser, I find doing 1) and 2) to be more difficult.

This is what a regular browser does:
- apps are always easily accessible (they are not mixed with documents)
- it's very easy to have a quick glance at what tabs are open
- it's very easy to switch to a tab

This comes with plenty of problems (tab explosion, it frames the user into a certain model (what a "tab" is, what "open" means), UI clutter), but it does the most important job well.

We could have 2 tab models. One for organization, one for regular tab management (like in Firefox Desktop today, with group tabs and regular tabs), but I'm not in favor of forcing the user into 2 mental models of how his work is organized.

I would recommend that we work on a tab model that is *simple* to understand, that allows users to keep track of what's going on *now* (short term organization), let him switch between tabs in an *efficient* way. Bonus if this could be done in a way that doesn't clutter the UI, and if tab explosion can be addressed.

**Comment by gordonbrander** [comment]
Hypothesis behind the previous design was:
- Tabs are used for multitasking
- Multi-tasking typically happens between 2-4 items
- So all the organization, opening closing of tabs is a distraction.

Here's what I learned:
- Tabs are occasionally used for multitasking (app style), but are more often used for other use cases, including reflecting a train of thought, creating a task list, creating a reading list, collecting research, etc.

Here's my new hypothesis, based on how I interpret the tab data:
- Tab explosion is not the problem. We say "explosion" because the design of tabs today becomes overwhelming when you have more than 8.
- Users are forced to close tabs to create a clean state that is usable again. It is so painful to have more than 8 tabs with current designs that they prune to this number pretty consistently (see data). Sometimes they give up because this is too much work.
- We can solve these problems by creating a design that builds [strata](https://en.wikipedia.org/wiki/Stratum#/media/File:Quebrada_de_Cafayate,_Salta_%28Argentina%29.jpg) of tabs over time.
- You shouldn't have to manage or organize tabs, but they should give you a useful map of your browsing behavior.
- Your newest tabs are at the "top layer". You never have to close a tab. You can always scroll back to old tabs.

**Comment by Gozala** [comment]
> Tabs are occasionally used for multitasking (app style), but are more often used for other use cases, including reflecting a train of thought, creating a task list, creating a reading list, collecting research, etc.

As you can see all of this are kind of intent based based groups, there for i think that idea should be present in whatever we end up with. Meaning having a grid, list or any other kind of one pile of tabs is not going to work because at the end of the day it is still one huge pile. I think clastering tabs by intent is the key to handle organisation. I also think that plie of clasters is still a pile of things & there for a mess. I think clastering by intent and smart way to focus on specific intent is going to resolve "explosion" as it will limit pile to relevant things based on your current intention. Finding a way a good interface for intent switching is something that I find challenging though.

**Comment by Gozala** [comment]
BTW I don't think that your first hypotesis was incorrect, I do think it was absolutely right in fact. I do think reason why it did not worked out is because we can't focus on relevant tasks to switch between so you wind up with a huge pile that changes it's order every time you peek at something. In other words I think task switching will be very sucessful as long as tasks you're presented with are relevent to your intentions.

**Comment by gordonbrander** [comment]
Out of date.
