### ISSUE TITLE
iframes history is not restored

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#315]
See https://bugzilla.mozilla.org/show_bug.cgi?id=449967

**Comment by paulrouget** [comment]
First, we need bug 1033999. Then:

> kanru: the main use case I want to support is to restore a crashed or temporally killed process
> kanru: so initially it wont support persist session data across phone reboot or application (b2g) restart
> paul: What would it take to restore the session after a restart? 
> kanru: then we need to port the serialization / deserialization of session data from firefox. And define a method to control which iframe will be restored

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
