### ISSUE TITLE
Global multimedia controls

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#316]
Let's make it so only one tab can play music.

And also, the browser, when a player is detected, could show media controls (play/pause/prev/next) in the chrome, letting the user, for example, control soundcloud.com without having the soundcloud tab selected.

**Comment by julianrichen** [comment]
> Let's make it so only one tab can play music.

Isn't better to let the user decide? I see this effecting work-flow is multiple ways:

* User has a podcast or other media open in another tab, while browsing in another tab they open another media source which stops the original media.
* Some users like to overlay media to change a video; ex. playing one piece of music over a trailer to "re-score" the trailer.
* User is browsing multiple livestreams on services like twitch, hitbox, picarto, etc... every time they open a new stream it stops the other one.

That's just a few examples. It's an interesting idea to have a global control in the chrome, maybe make it a toggle (with the default set as off)?

Having an icon in the tab that media is playing would be a nice (both audo & video).

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
