### ISSUE TITLE
unclear install Nightly on linux in README.md

### ISSUE THREAD

**Issue by pixelr0** [mozilla/browser.html#32]
how exactly can you install FF Nightly on "linux"? (linux is a kernel! j/k) but on a serious note, https://nightly.mozilla.org/ FF Nightly links to a tar.bz2 archive. I have Ubuntu installed and Firefox 34 is the default browser... i think this will generate confusion on how to install Nightly. Even if they download/extract the archive, i don't think it's a easy way to make Nightly default.

**Comment by paulrouget** [comment]
Just extract the archive anywhere. And use the Firefox binary in it.
