### ISSUE TITLE
Allow script execution in the content that has access to a remote iframe document

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#332]
We exchanged few messages about this, but I think this deserves more torough discussion. Here is the issue I have reported for the webview API: https://github.com/benfrancis/webview/issues/8 with an example how that is useful.

Also note that currently mozbrowser is an only implementation that has nothing like that in place:

- Google: [`webView.executeScript`](https://developer.chrome.com/apps/tags/webview#method-executeScript)
- Microsoft [`webView.invokeScriptAsync`](https://msdn.microsoft.com/en-gb/library/windows/apps/dn301841.aspx)
- Electron (a.k.a atom-shell) [`webView.executeScript`](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#webviewexecutejavascriptcode)

As a matter of fact we kind of do have that as well:

- Mozilla [`browser.messageManager.loadFrameScript`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIChromeFrameMessageManager#loadFrameScript())

My reasoning is that it is impossible to expose every single thing we may need through a webview API inspecting markup for twitter cards is one example, in a future we may want to inspect some other parts of markup. Are we going to patch the webview for every new use case ? Or is in even makes sense to build twitter cards into webview API ?

At the end of the day it would also help us to try different things without needing to patch a platform, that not to say we should use workarounds, but rather that we can experiment quicker and decide what exactly we want to uplift into a platform.

**Comment by Gozala** [comment]
Another good example would be a pinning a page sections. Gordon had ideal like selecting subsections adding notes etc... All of that would require some access interaction with a DOM inside a web view. I think it would be really difficult to iterate over ideas like that if we need to think to expose everything through a platform API. I'd much rather iterate fast with something like `executeScript` and once we're settled then try to formalise a platform API around that.

**Comment by gordonbrander** [comment]
This is a very good idea assuming we can reconcile security stuff.

**Comment by paulrouget** [comment]
I'm ok this idea, but I don't think this should be a priority today.

**Comment by paulrouget** [comment]
Patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1174733

I've posted in dev-platform about this feature.

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by paulrouget** [comment]
Fixed in Gecko.

**Comment by Gozala** [comment]
I do think we still need long lived scripts not just one timers so they could track for example track DOM mutations or other events and communicate them with a embedder.

**Comment by paulrouget** [comment]
File a different bug for that.
