### ISSUE TITLE
Lots of flickering in latest build

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#333]
@paulrouget I'm getting extreme flickering in `graphene-40.0a1.en-US.mac64.dmg` when showing the `.tabstripkillzone` opacity animation

**Comment by gordonbrander** [comment]
Also getting more scroll jank in Graphene than Firefox Desktop.

**Comment by Gozala** [comment]
I did not notice that first myself, but then if I use dark backrgound in dashboard, and do `cmd L` then `esc` I see a pretty nasty flickering qute realiably.

**Comment by paulrouget** [comment]
Yes, it happens sporadically. I think it's a gfx regression. I'll look at this.

**Comment by paulrouget** [comment]
(I would bet on a vsync bug)

**Comment by andreasgal** [comment]
I am using mac and I am seeing this. mac has vsync not turned on yet.

**Comment by paulrouget** [comment]
> I am using mac and I am seeing this. mac has vsync not turned on yet.

It is on B2G desktop.

**Comment by paulrouget** [comment]
Setting `gfx.vsync.hw-vsync.enabled` to `false` appears to solve (or greatly reduce) the flickering.

**Comment by paulrouget** [comment]
Please try build *graphene-novsync-40.0a1.en-US.mac64.dmg*

**Comment by paulrouget** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1151489

**Comment by paulrouget** [comment]
Still happening after reverting all the recent vsync changes. Bisecting now.

**Comment by paulrouget** [comment]
I can reproduce with a Graphene build from last month (21st of March).

**Comment by paulrouget** [comment]
It's very sporadic, so it's hard to bisect properly, but apparently, it would be cause by 18c6a3b.

**Comment by paulrouget** [comment]
Reverted: 15463b12896f88ca24e085cd1352c4568785a06c.
