### ISSUE TITLE
Thumbnails should not "win"

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#334]
@Gozala we have a sporadic bug where a website that has a tile (like gmail for example) will display the tile, but when the thumbnail is ready, it replaces the tile.

**Comment by paulrouget** [comment]
Isn't that #235 ?

**Comment by gordonbrander** [comment]
No this is something different, I think. #235 has to do with subdomains.

**Comment by paulrouget** [comment]
@gordonbrander looks very similar to me. It's a redirection issue. I might be wrong (haven't tested), so feel free to re-open.

**Comment by Gozala** [comment]
I think this was a different issue with an initial implementation which was fixed by #220
