### ISSUE TITLE
modules not loaded synchronously

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#339]
On top of each file, after `define((require, exports, module)`, I add this line:

```
console.log(require('./actions').sendEventToChrome);
```

And I see:

```
"suggestion-box.js" undefined
"iframe.js" undefined
"web-view.js" undefined
"progress-bar.js" function sendEventToChrome()
"location-bar.js" function sendEventToChrome()
"main.js" function sendEventToChrome()
"progress-bar.js" function sendEventToChrome()
"window-controls.js" function sendEventToChrome()
"window-bar.js" function sendEventToChrome()
```

What am I doing wrong?

**Comment by andreasgal** [comment]
put the console.log into window.onload, or $(function () {}) or whatever your preferred method is

**Comment by paulrouget** [comment]
`readyState` is `complete` at that time. Scripts are loaded with require.js.

**Comment by Gozala** [comment]
@paulrouget `require` js looks at the module source and preloads dependencies before it runs the module function. The problem you see is that you introduce circular dependency between modules if you look at `actions.js` you can see that it depends on `web-view.js` and `suggestion-box.js` so requirejs needs to load either `actions.js` first or `web-view.js / suggestion-box.js`. As of `iframe.js` it's a sub-dependency of `web-view.js` so it also joins the circular dependency graph.

BTW requirejs in such cases will give you an object for `require('./actions')` that will be populated as soon there is a chance, so if you had function like `exports.sendEventToChrome = msg => require('./actions').sendEventToChrome(msg)` that would still work.

Anyway I don't think we can really do much about it without JS getting a real modules that handle cyrcular dependencies (which I believe ES6 does).
