### ISSUE TITLE
browser.html as default browser can't handle links

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#342]
So today I've set browser.html as my default browser. Now if I click links in my email client I see it reloading active tab and that is it. Have not digged into what's going on but we should figure it out.

**Comment by Gozala** [comment]
It turns out I was mistaken in my observation. What actually was happening is that new window was getting opened restoring the state, which seemed like active tab was reloaded :)

My guess is browser.html does not even get's a chance to handle anything, I think graphene should dispatch event to a browser.html letting it to decide what to do.

**Comment by Gozala** [comment]
Simpler way tao reproduce the issue is by running a command `open -a B2G http://github.com/`

**Comment by paulrouget** [comment]
Sending a chrome event might be enough. I'll look at this.

**Comment by paulrouget** [comment]
Fixed. Latest nightly required.
