### ISSUE TITLE
Setup instructions in README.md do not work

### ISSUE THREAD

**Issue by erikvold** [mozilla/browser.html#343]
I tried the setup instructions `npm install && npm start` and these were the error that I received:

    $ npm install
    node-uuid@1.4.3 node_modules/node-uuid

    immutable@3.6.2 node_modules/immutable

    ecstatic@0.7.4 node_modules/ecstatic
    ├── url-join@0.0.1
    ├── mime@1.3.4
    ├── minimist@1.1.1
    └── he@0.5.0

    requirejs@2.1.16 node_modules/requirejs

    typed-immutable@0.0.3 node_modules/typed-immutable
    └── immutable@3.7.2

    omniscient@3.1.0 node_modules/omniscient
    ├── lodash.assign@3.1.0 (lodash.isnative@3.0.2, lodash._createassigner@3.1.0, lodash._baseassign@3.1.0, lodash.keys@3.0.6)
    ├── lodash.pick@3.1.0 (lodash.restparam@3.6.1, lodash._pickbyarray@3.0.1, lodash._bindcallback@3.0.1, lodash._baseflatten@3.1.1, lodash._pickbycallback@3.0.0)
    └── lodash.isequal@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseisequal@3.0.4)

    jscs@1.12.0 node_modules/jscs
    ├── strip-json-comments@1.0.2
    ├── commander@2.6.0
    ├── estraverse@1.9.3
    ├── vow@0.4.9
    ├── exit@0.1.2
    ├── lodash.assign@3.0.0 (lodash._createassigner@3.1.0, lodash._baseassign@3.1.0)
    ├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
    ├── glob@5.0.5 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.1, inflight@1.0.4)
    ├── vow-fs@0.3.4 (vow-queue@0.4.1, glob@4.5.3)
    ├── minimatch@2.0.4 (brace-expansion@1.1.0)
    ├── cli-table@0.3.1 (colors@1.0.3)
    ├── esprima-harmony-jscs@1.1.0-templates
    ├── esprima@1.2.5
    ├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, utile@0.2.1, winston@0.8.3)
    └── xmlbuilder@2.6.2 (lodash@3.5.0)

    react@0.13.0 node_modules/react
    └── envify@3.4.0 (through@2.3.7, jstransform@10.1.0)
    $ npm start

    > browser.html@0.0.2 start /Users/erik_vold/github/browser.html
    > npm run start-server & npm run start-app

    > browser.html@0.0.2 start-server /Users/erik_vold/github/browser.html
    > ecstatic . --port 6060

    > browser.html@0.0.2 start-app /Users/erik_vold/github/browser.html
    > /Applications/B2G.app/Contents/MacOS/graphene --start-manifest=http://localhost:6060/manifest.webapp

    sh: /Applications/B2G.app/Contents/MacOS/graphene: No such file or directory

    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "run" "start-app"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE
    npm ERR! browser.html@0.0.2 start-app: `/Applications/B2G.app/Contents/MacOS/graphene --start-manifest=http://localhost:6060/manifest.webapp`
    npm ERR! Exit status 127
    npm ERR! 
    npm ERR! Failed at the browser.html@0.0.2 start-app script '/Applications/B2G.app/Contents/MacOS/graphene --start-manifest=http://localhost:6060/manifest.webapp'.
    npm ERR! This is most likely a problem with the browser.html package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     /Applications/B2G.app/Contents/MacOS/graphene --start-manifest=http://localhost:6060/manifest.webapp
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls browser.html
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/erik_vold/github/browser.html/npm-debug.log

    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "start"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE
    npm ERR! browser.html@0.0.2 start: `npm run start-server & npm run start-app`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the browser.html@0.0.2 start script 'npm run start-server & npm run start-app'.
    npm ERR! This is most likely a problem with the browser.html package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run start-server & npm run start-app
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls browser.html
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/erik_vold/github/browser.html/npm-debug.log
    $ ecstatic serving . at http://0.0.0.0:6060

Then there was nothing happening, so I used control + C

In the `npm-debug.log` there is this:

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
    2 info using npm@2.5.1
    3 info using node@v0.12.0
    4 verbose node symlink /usr/local/bin/node
    5 verbose run-script [ 'prestart', 'start', 'poststart' ]
    6 info prestart browser.html@0.0.2
    7 info start browser.html@0.0.2
    8 verbose unsafe-perm in lifecycle true
    9 info browser.html@0.0.2 Failed to exec start script
    10 verbose stack Error: browser.html@0.0.2 start: `npm run start-server & npm run start-app`
    10 verbose stack Exit status 1
    10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    10 verbose stack     at EventEmitter.emit (events.js:110:17)
    10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
    10 verbose stack     at ChildProcess.emit (events.js:110:17)
    10 verbose stack     at maybeClose (child_process.js:1008:16)
    10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
    11 verbose pkgid browser.html@0.0.2
    12 verbose cwd /Users/erik_vold/github/browser.html
    13 error Darwin 14.3.0
    14 error argv "node" "/usr/local/bin/npm" "start"
    15 error node v0.12.0
    16 error npm  v2.5.1
    17 error code ELIFECYCLE
    18 error browser.html@0.0.2 start: `npm run start-server & npm run start-app`
    18 error Exit status 1
    19 error Failed at the browser.html@0.0.2 start script 'npm run start-server & npm run start-app'.
    19 error This is most likely a problem with the browser.html package,
    19 error not with npm itself.
    19 error Tell the author that this fails on your system:
    19 error     npm run start-server & npm run start-app
    19 error You can get their info via:
    19 error     npm owner ls browser.html
    19 error There is likely additional logging output above.
    20 verbose exit [ 1, true ]

**Comment by Gozala** [comment]
@erikvold you need a runtime, see the section below the setup:
https://github.com/mozilla/browser.html/blob/master/README.md#runtime

**Comment by erikvold** [comment]
@gozala tried that and ran into #361
