### ISSUE TITLE
false lack of javascript

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#35]
Since switching to the firebox runtime, certain websites (for example all google websites) believe that browser.html does not support javascript, and show a version of the website intended for use in browsers that do not support javascript or display a warning message, even though the browser does actually support javascript.

**Comment by andreasgal** [comment]
This is probably related to the UA string.

**Comment by PalmerAL** [comment]
probably. the user agent reports as "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firebox/0.1". Some websites might take the version number 0.1 and the word "mozilla" or "gecko" and interpret this as a version of firefox that does not support javascript.

**Comment by PalmerAL** [comment]
It might be a good idea to move the version of gecko to the end of the string (where the firefox version number goes) so that websites that look for the version number at the end see the real version number.

**Comment by andreasgal** [comment]
Yeah the 0.1 is probably the problem. Andreas

**Comment by paulrouget** [comment]
This will be fixed once we move to B2G and bug 1115935 lands.
