### ISSUE TITLE
100% CPU: typing in the urlbar is unresponsive

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#358]
This used to be fast.

Video: http://gfycat.com/DeterminedUniqueBoilweevil

**Comment by paulrouget** [comment]
We have a mix of:
- bad GC pauses
- `input`, `keyup`, `keydown` and `load` events trigger runScripts for about 30ms

**Comment by paulrouget** [comment]
![screen shot 2015-05-05 at 11 11 00](https://cloud.githubusercontent.com/assets/373579/7469777/7cd96f62-f317-11e4-99b7-6e0cbb832e6b.png)

**Comment by paulrouget** [comment]
It's 90% `input/keyup/keydown`.

**Comment by paulrouget** [comment]
![screen shot 2015-05-05 at 11 26 34](https://cloud.githubusercontent.com/assets/373579/7470012/a3d1806c-f319-11e4-8398-970360a0e4f7.png)
Many 320ms GCs.

**Comment by paulrouget** [comment]
@Gozala Can you look at this? I believe `editable.js` is the problem.

**Comment by paulrouget** [comment]
Looking closer, anything changes, even as simple as changing the `rfa` value, will take a long time (35ms), and a lot of GCs.

I'm wondering when we regressed that much.

**Comment by paulrouget** [comment]
Another example, `onTitleChange` takes 30ms.

**Comment by paulrouget** [comment]
`git bisect` tells me that commit 451883be7b6b68a6c86955094bbb13600166d26c is the issue.

**Comment by paulrouget** [comment]
The core of the issue is the rendering that takes so long.

Here is the most simple profile I could come up with: https://pastebin.mozilla.org/8832451

It's what happens when you just give the focus to the window. We change `isDocumentFocused` to true. And it takes 49ms, when it should take ~1ms (just painting the window buttons).

iirc, React is in "debug mode". Maybe that's the problem. I don't know.

**Comment by Gozala** [comment]
I'll check that if it is rerendering only necessary parts, my guess is it isn't

**Comment by Gozala** [comment]
Ok so this is what's going on on blur then focus:


```
"<Browser>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:01.170 "<Browser>: render" omniscient.js:2902:28
10:26:01.172 "<WindowBar key=navigation>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:01.173 "<WindowBar key=navigation>: render" omniscient.js:2902:28
10:26:01.175 "< key=WindowControls>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:01.175 "< key=WindowControls>: render" omniscient.js:2902:28
10:26:01.177 "<LocationBarView key=navigation>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.177 "< key=progressbar>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.178 "<PreviewBox key=tabstrip>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:01.179 "<PreviewBox key=tabstrip>: render" omniscient.js:2902:28
10:26:01.183 "<Preview key=315205c6-5ac1-4882-a396-40c0511c0a63>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.184 "<Preview key=604e446e-536a-4834-aa00-bdbec4bb3c20>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.185 "<Preview key=6d91255c-85cf-4aed-9133-0920edeb04f0>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.185 "<Preview key=about:blank>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.186 "<SuggestionBar key=awesomebar>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.187 "<Dashboard key=dashboard>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.188 "<WebViewsBox key=web-view-box>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:01.188 "<WebViewsBox key=web-view-box>: render" omniscient.js:2902:28
10:26:01.192 "<WebView key=315205c6-5ac1-4882-a396-40c0511c0a63>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.193 "<WebView key=604e446e-536a-4834-aa00-bdbec4bb3c20>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.194 "<WebView key=6d91255c-85cf-4aed-9133-0920edeb04f0>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.195 "<WebView key=about:blank>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:01.195 "< key=updates-banner>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.081 "<Browser>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:03.082 "<Browser>: render" omniscient.js:2902:28
10:26:03.086 "<WindowBar key=navigation>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:03.087 "<WindowBar key=navigation>: render" omniscient.js:2902:28
10:26:03.088 "< key=WindowControls>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:03.089 "< key=WindowControls>: render" omniscient.js:2902:28
10:26:03.091 "<LocationBarView key=navigation>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.091 "< key=progressbar>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.092 "<PreviewBox key=tabstrip>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:03.093 "<PreviewBox key=tabstrip>: render" omniscient.js:2902:28
10:26:03.098 "<Preview key=315205c6-5ac1-4882-a396-40c0511c0a63>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.103 "<Preview key=604e446e-536a-4834-aa00-bdbec4bb3c20>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.104 "<Preview key=6d91255c-85cf-4aed-9133-0920edeb04f0>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.105 "<Preview key=about:blank>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.106 "<SuggestionBar key=awesomebar>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.107 "<Dashboard key=dashboard>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.108 "<WebViewsBox key=web-view-box>: shouldComponentUpdate => true (props have changed)" omniscient.js:2902:28
10:26:03.110 "<WebViewsBox key=web-view-box>: render" omniscient.js:2902:28
10:26:03.115 "<WebView key=315205c6-5ac1-4882-a396-40c0511c0a63>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.116 "<WebView key=604e446e-536a-4834-aa00-bdbec4bb3c20>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.117 "<WebView key=6d91255c-85cf-4aed-9133-0920edeb04f0>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.118 "<WebView key=about:blank>: shouldComponentUpdate => false" omniscient.js:2902:28
10:26:03.119 "< key=updates-banner>: shouldComponentUpdate => false"
```

We do re-render much more than we need to, so that can be fixed which I'll look into.

That being said it takes less the 1ms on my machine with a build I got from your ftp which is `40.0a1` with a build id `20150422083707`. I wonder if version you are using had some regression that cause it to be way slower.

**Comment by Gozala** [comment]
I also noticed that if I run app with a profiler switched on it's magnitutes slower that without it. Like without profiler switched on I don't get any delay during typing, while I do get a huge one if profiler is running. I wonder how much of your observations are affected by this.

**Comment by Gozala** [comment]
Ok it took me a while but I finally understand what is causing unnecessary render loops:

1. When you type into a address bar we change active `webView.userInput`.
2. Since `webView`changed `WebViewBox` gets re-rendered.
3. Since we generate `theme` out of active `webView` everything that depends on theme get's re-rendered as well that includes previews and most of window controls.

We could change record structures such that only relevant data is going to be passed along that should reduce amount of code that runs and garbage generated.

Similar thing happens on iframe load events as those change state props on web view and there for cause re-render on more or less same components that aren't in fact necessary.

That being said I still doubt this caused a performance regression unless we had it since awesome bar was implemented. As far as I recall we've moved global `input` filed to `webView.userInput` during that change.

Neither I'm entirely sure performance is as bad as performance tools claim it to be, because I see huge perf difference with profiler or logging switched on vs switched off.

**Comment by Gozala** [comment]
I am going to make a patch to fix some of these, but it seems like a big change so probably it will take few steps.

**Comment by paulrouget** [comment]
Without the profiler running, rendering still take between 20 and 40ms.

**Comment by paulrouget** [comment]
Any update?
