### ISSUE TITLE
flash player support

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#36]
When switching to firebox, the browser can no longer use flash player. In addition, if you try to <a href="http://get.adobe.com/flashplayer/">download flash player </a> in the browser, you get the following:
![screen shot 2015-01-06 at 3 58 14 pm](https://cloud.githubusercontent.com/assets/10314059/5637084/8fdf27a8-95bd-11e4-9bab-5aecf1f5bc24.png)

**Comment by andreasgal** [comment]
This I would almost call a feature. We might want to look at Shumway at some point for the simple Flash use cases, but we should definitely keep Flash out of this.

**Comment by paulrouget** [comment]
Plugin support is not a thing we want now (ever?).
