### ISSUE TITLE
Readme isn't clear how to setup

### ISSUE THREAD

**Issue by erikvold** [mozilla/browser.html#361]
Browser.html needs a special build of B2G desktop called Graphene. Build this branch: https://hg.mozilla.org/projects/larch with --enable-application=b2g/graphene.

I did this:

    hg clone https://hg.mozilla.org/projects/larch
    cd larch
    ./mach build --enable-application=b2g/graphene

And I got this error 

    $ ./mach build --enable-application=b2g/graphene
    It looks like you passed an unrecognized argument into mach.

    The build command does not accept the arguments: --enable-application=b2g/graphene

So I'm not sure how to actually set this up.

**Comment by paulrouget** [comment]
Add enable-application in your mozconfig.
