### ISSUE TITLE
Smarter URL Bar autocomplete

### ISSUE THREAD

**Issue by nt1m** [mozilla/browser.html#368]
Probably a bit out of scope of browser.html, but there are 2 points that would be cool to have : getting results faster, and search faster.

Mockups (by shorlander) that illustrate better my ideas :
http://people.mozilla.org/~shorlander/Flare/ (Skip to the URL bar part)

**Comment by Gozala** [comment]
We would like to make search faster, but keeping this issue open won't contribute to getting there sooner.  Closing it!
