### ISSUE TITLE
Make tabbar a window drag handle

### ISSUE THREAD

**Issue by nt1m** [mozilla/browser.html#370]

**Comment by paulrouget** [comment]
Nothing to do at the app level. See https://bugzilla.mozilla.org/show_bug.cgi?id=1163113

**Comment by nt1m** [comment]
@paulrouget It's possible to drag the navigation bar, but not the tab bar (on OSX).

**Comment by paulrouget** [comment]
Sorry, I thought you were talking about Windows.

No, it's not possible now because of how drag's regions are updated.

**Comment by gordonbrander** [comment]
Does not apply to current design.
