### ISSUE TITLE
iframe dispatches multiple `loadend` events for a single page load.

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#372]
I am not sure if this is expected behavior or not (is it @paulrouget) but during history db implementation I noticed that I was receiving duplicate visits records for the same page visit, after little bit of investigation I noticed following output for `console.log(event.target.src, event.detail)` code in loadend event handler:

```
"http://www.amazon.com/" Object { backgroundColor: "transparent", msg_name: "loadend" } web-view.js:258:1
14:50:16.497 "http://qz.com/" Object { backgroundColor: "transparent", msg_name: "loadend" } web-view.js:258:1
14:50:27.582 "http://www.amazon.com/" Object { backgroundColor: "rgb(255, 255, 255)", msg_name: "loadend" } web-view.js:258:1
14:50:31.798 "http://qz.com/" Object { backgroundColor: "rgb(249, 249, 249)", msg_name: "loadend” }
```

Which suggests there are multiple loadend events for the same page load.

**Comment by Gozala** [comment]
I followed suggestion from @fabricedesre and checked  `loadstar` events & seems to fire twice as well:

```js
15:01:45.811 "http://qz.com/" Object { msg_name: "loadstart" } web-view.js:257:1
15:01:45.846 "http://www.amazon.com/" Object { msg_name: "loadstart" } web-view.js:257:1
15:01:45.931 "http://qz.com/" Object { backgroundColor: "transparent", msg_name: "loadend" } web-view.js:261:1
15:01:45.986 "http://qz.com/" Object { msg_name: "loadstart" } web-view.js:257:1
15:01:46.006 "http://www.amazon.com/" Object { backgroundColor: "transparent", msg_name: "loadend" } web-view.js:261:1
15:01:46.042 "http://www.amazon.com/" Object { msg_name: "loadstart" } web-view.js:257:1
15:01:52.322 "http://www.amazon.com/" Object { backgroundColor: "rgb(255, 255, 255)", msg_name: "loadend" } web-view.js:261:1
15:01:55.531 "http://qz.com/" Object { backgroundColor: "rgb(249, 249, 249)", msg_name: "loadend" }
```

**Comment by Gozala** [comment]
Ok it looks this is a code path that is causing reload of the page:
https://github.com/mozilla/browser.html/blob/master/src/common/element.js#L58-L62

The problem is combination of following things:

1. React does not know about non standard attributes like `mozbrowser` there for we generate a component for such elements that sets such custom attributes manually.
2. React let's you set such attributes only after it's inserts it into a document.
3. Setting `mozbrowser` attribute after `iframe` is in the document has no effect on it.
4. To workaround combination of above limitations we set such custom attributes once react hands node to us and then replace it with itself, in such case `mozbrowser` attribute is picked up by gecko.


Looks like iframe start to load document before we get a chance to replace it with itself, I suspect that interrupts load and triggers loadend event and then restarts load and there for causes second set of `load` events.

**Comment by Gozala** [comment]
Ok turns out I was wrong blaming react / us for this issue, in fact removing & reinserting node does not really causes this issue. In fact issue seems to be the way gecko dispatches `mozlooad*` event. As far as I can tell it's sending async message from the content process that triggers actual dom event on parent process after certain delay. So what happens is blank iframe starts loading `about:blank` page we change it's `src` and attach event listeners, and then get delayed load events for `about:blank` and actual load events for the page we were loading. It is just that `event.target.src` is already changed from `about:blank` by the time we receive those events there for it felt like we load page twice.

Here is simple test case that illustrates this issue: https://gist.github.com/Gozala/e6232524c31908b6c6bd

**Comment by paulrouget** [comment]
Yeah, I suspected something like that.

We should not load `about:blank`. But I don't think Gecko can create a window with no document. So we should set `src` before appending the node.

**Comment by paulrouget** [comment]
Or we could set `event.detail.url` to the loaded URL, but I'd much rather avoid the race condition by setting the `src` attribute before appending the iframe.

**Comment by paulrouget** [comment]
@Gozala do you need `event.detail.url`?

**Comment by Gozala** [comment]
> @Gozala do you need event.detail.url?

I think it's helpful but not a complete solution for the problem, as it won't cover following scenario:

1. iframe.src = foo
2. iframe.src = bar
3. iframe.src = foo

When you get first `event.detail.url` it will be equal to `iframe.src` but it won't actually mean that document was loaded.

I think `iframe` and `event.detail` would have to carry some other field maybe `sessionID` or that user would be able to assign to an iframe like: `iframe.src = url; iframe.sessionID = ++guid;` including `sessionID` along with an events like `event.detail.sessionID` would allow an event handler to assess if received event belongs to a current session - page load or not.

While this is unrelated same `iframe.sessionID` ideally would also be used to deal with a cache so instead of doing `iframe.goBack()` one would be able to say `iframe.restore(sessionID)`. 

Maybe `iframe.sessionID` can be generated automatically if user does not sets it or maybe it's just generated all the time, but I think such a fix would make a lot more sense.

**Comment by Gozala** [comment]
I'll attempt to fix this specific race condition by setting up an `src` before iframe is injected into a tree. Still there will be an issue described above, but maybe we should create a separate graphene issue for that.

**Comment by Gozala** [comment]
I just created that other issues and assigned this one to myself to set `src` ahead of injection to a tree.

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
