### ISSUE TITLE
Scrolling is junky

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#377]
Scrolling is quite junky every now and then, I notice it quite frequently if:

1. Page is loading.
2. If devtools is connected.

**Comment by paulrouget** [comment]
Is it a regression?

**Comment by paulrouget** [comment]
@Gozala ^

**Comment by Gozala** [comment]
> Is it a regression?

I think it has being junky during loading on sites like amazon.com I have not noticed as much junkiness with devtools connected before I think that one is regression (maybe changes in devtools) ?

**Comment by Gozala** [comment]
I tried couple of older versions and did testing on current one and I think problem that I was observing was related to a profiler, or more specifically memory used by recordings. During page load scrolling is & always was junky for me.

**Comment by Gozala** [comment]
Let's leave it open / or close if you want I can I'll post (reopen) more details if I observe something more specific.

**Comment by gordonbrander** [comment]
No longer true.
