### ISSUE TITLE
Profiler crashes graphene

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#378]
Using `deviceinfo.platform_build_id: 20150515044201` and `Nightly 41.0a1 (2015-05-15)` with profiler connected to `browser.html` I get graphene crashes quite frequently.

**Comment by paulrouget** [comment]
OOM?

**Comment by paulrouget** [comment]
@Gozala ^

**Comment by jsantell** [comment]
Is `devtools.performance.ui.enable-memory` on? That can cause some instability.

**Comment by Gozala** [comment]
@paulrouget I assume you're asking if it runs out of memory, don't know I'll upload crash log next time I get it.

**Comment by Gozala** [comment]
No longer have seen it, so I'm going to close it.
