### ISSUE TITLE
Failure to update an app

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#379]
It seems that browser.html fails to update this is what I see:

```
15:33:38.833 Github: 200 github.js:49:9
15:33:38.834 Github: pulling in 600000ms github.js:51:1
15:33:41.032 Github: remote: 078592a555238fe829f3d397cdbaa183aed1cbfa
 github.js:37:1
15:33:41.034 Github: local: 32b17d7bd92ad1825f19fa0431815380ffb7f813
 github.js:39:1
15:33:48.140 Unknown mozChromeEvent: apps-update-check embedding.js:36:9
```

After reload remote and local sha's are still the same.

**Comment by Gozala** [comment]
This is a build of graphene I'm observing this on `20150515044201`

**Comment by Gozala** [comment]
Just erased my profile and I still seem to get this issue which is really odd, as I'd expect that cache would be stored in the profile o_0

**Comment by Gozala** [comment]
Ok so I see different content here https://github.com/mozilla/browser.html/blob/5ed8dc6d322120645ee0c09b02658eb173ad319b/HEAD and http://mozilla.github.io/browser.html/HEAD which may explain the issue.

**Comment by gordonbrander** [comment]
@paulrouget same problem, even after updating to yesterday's build.

**Comment by paulrouget** [comment]
Looking at it.

**Comment by paulrouget** [comment]
So the branch `gh-pages` is up to date, but the code served by github.io is old.

**Comment by paulrouget** [comment]
79fccf2851ce5d8afceb7c3ef8becb1ce3a7fc63
