### ISSUE TITLE
CertErrors should use about:netError

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#38]
STR:
- Load https://linuxfr.org
- empty page

**Comment by PalmerAL** [comment]
When this happens, the browser api calls <code>mozbrowsererror</code> with type <code>other</code>, so it shouldn't be too hard to add some kind of warning message when this error occurs explaining what went wrong.

**Comment by PalmerAL** [comment]
Somethings like this maybe.
![screen shot 2015-01-08 at 4 35 26 pm](https://cloud.githubusercontent.com/assets/10314059/5672240/73540106-9754-11e4-849e-496f9c15c520.png)

**Comment by paulrouget** [comment]
I don't know if this is supposed to be handled at the runtime level or at the app level. I guess if we get the browsererror message, that means it should be handled in the app.

So yes, something like that.

**Comment by evilpie** [comment]
I think in theory we should get a "certerror" here. http://mxr.mozilla.org/mozilla-central/source/dom/browser-element/BrowserElementChildPreload.js#1315

What is the value of the security.alternate_certificate_error_page pref in our runtime?

**Comment by Gozala** [comment]
Appears to work on current build.

**Comment by paulrouget** [comment]
No. We don't handle errors at all.

**Comment by paulrouget** [comment]
I was wrong. CertErrors are not netErrors. They are supported. But I'd much prefer if we could use netErrors for that.

**Comment by Gozala** [comment]
Do we need to keep this open ? I no longer see this issue.
