### ISSUE TITLE
Fresh profile seems to be created every now and then

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#380]
Now that we have browser history integrated loosing a profile became a very irritating issue, as I keep loosing my history info every now and then.

**Comment by Gozala** [comment]
As far as I can see running browser.html with `npm start` and then running by starting `b2g` or other way round reliably looses my profile data. Could it be related to github serving content through `https` and local server through `http` ?

**Comment by fabricedesre** [comment]
for sure http and https are different origins, so indexedDB data ends up in different cookie jars.

**Comment by paulrouget** [comment]
It's not only http vs. https, the domain is also different.

@Gozala Is it really a new profile or just the db content that is different?

**Comment by paulrouget** [comment]
Apparently, it's because the db is been deleted everytime the app is being re-installed (switching between origin triggers a re-install).

@Gozala mentioned using a different app name for dev profile.

I think we should just use a different profile.

@Gozala what do you think?

**Comment by Gozala** [comment]
I have few constrains with this:

1. It won't be visible to make something as simple as `npm start` which is unfortunate as it would make contribution more difficult. Although not a big deal right now.
2. Larger constraint is that graphene seem be too bound to a single app, meaning if I run any other app say app that "vr" team is working on I'll loose data of both apps.

I think fixing this is effort well spend especially if we hope graphene to be useful outside of this project. Using separate profile in the meantime is fine.

Not sure where this fall in terms of priority scale though, I'll let @gordonbrander speak of that :)

**Comment by paulrouget** [comment]
We can fix this. But really not a priority compared to all the other things.

**Comment by Gozala** [comment]
BTW another unfortunate thing I noticed which is kind of relates to this bucket is that it's impossible to run multiple graphene based apps at a time (without specifying profile).

**Comment by paulrouget** [comment]
Not sure to understand why. Graphene can run multiple apps. It's based on B2G, and B2G can run multiple apps.

**Comment by Gozala** [comment]
> Not sure to understand why. Graphene can run multiple apps. It's based on B2G, and B2G can run multiple apps.

@paulrouget Just create any other app but **browser.html** say **webvr** start it, first you'll get a see a message that `b2g` is already running. Another step would be to quit **browser.html** and start **webvr** with will work  but then you loose all the data stored by **browser.html**.

Of course you could use different profile for every app you'll use to run them simultaneously and not loose data but that's not ideal and requires a lot of discipline just to avoid data loss. Now in contrast this with other runtimes like [electron](http://electron.atom.io), you can run as many apps simultaneously and they do not collide. I would like **graphene** to be viable competitor.

**Comment by paulrouget** [comment]
Multi-apps works differently with B2G. The runtime starts a "root" app (system app), and then, it's up to this app to launch other apps. So we would need to add some sort of command line handler that would ask the system app to launch another app, like we did for `-url`.

**Comment by fabricedesre** [comment]
Sharing a profile while switching frontends can be undesirable actually. Let's imagine that we have the possibility to keep data around when switching apps, and that:
- I use browser.html to do my browsing for a while. We store my navigation history in indexedDB.
- I switch to superGreatBrowser because I got the link somewhere. This browser now has access to my navigation history, but it's actually nefariousBrowser and uploads my data to a 3rd party server without my consent. I can even not realize that.

Privacy and user control is more important than developer convenience.

**Comment by Gozala** [comment]
> Sharing a profile while switching frontends can be undesirable actually. Let's imagine that we have the possibility to keep data around when switching apps, and that:
> 
> I use browser.html to do my browsing for a while. We store my navigation history in indexedDB.
> I switch to superGreatBrowser because I got the link somewhere. This browser now has access to my navigation history, but it's actually nefariousBrowser and uploads my data to a 3rd party server without my consent. I can even not realize that.
> Privacy and user control is more important than developer convenience.

In my opinion each app `url` it's from should get it's own data store but not cause each other data stores to be erased. We may use profiles under the hood or something else, that's implementation details.

**Comment by Gozala** [comment]
With #381 most issues are resolves IMO, still would leave this open in case someone has time & desire to do a proper fix on graphene side.

**Comment by fabricedesre** [comment]
Yes, we may be able to make that work safely anyway. Like only uninstalling the previous system app if it's same origin with the new one.

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
