### ISSUE TITLE
Scrolling inside elements should not simultaneously scroll away controls

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#383]
When I scroll an element with `overflow:auto`, what we want is:

1. Element scrolls.
2. When there is no more room to scroll, scroll is handed off to outer item. Repeat.
3. Until you hit the outermost scrolling element -- the page. At this point, chrome should scroll with page.

I believe these are related:
- https://github.com/mozilla/browser.html/pull/353
- https://github.com/mozilla/browser.html/issues/355

@paulrouget am I right in thinking this will be fixed when we have APZC?

**Comment by paulrouget** [comment]
> At this point, chrome should scroll with page

Scroll at the same time (2px scroll would scroll 1px of the chrome and 1px of the content)?
Or first scroll the chrome then the page (start scrolling content only once the chrome is full scrolled)?

**Comment by gordonbrander** [comment]
We want the chrome and page to scroll together. This is the desired behavior:

> Scroll at the same time (2px scroll would scroll 1px of the chrome and 1px of the content)?

Of course, it doesn't have to be perfect, just close enough not to notice differences.

**Comment by gordonbrander** [comment]
No longer applies.
