### ISSUE TITLE
Flickering in latest Graphene

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#384]
@paulrouget I'm getting flickering when

- Hiding/showing the tabstrip
- Occasionally when scrolling

**Comment by Gozala** [comment]
I get that too.

**Comment by Gozala** [comment]
I get this flickering prettty consitently when tabstrip appears / dissapears.

**Comment by paulrouget** [comment]
I can reproduce. It's apparently not a browser.html regression (reverting to a 3 weeks old commit doesn't solve the issue).

Firefox Desktop doesn't appear to have this issue though.

Investigating.

**Comment by paulrouget** [comment]
Looks to be a hardware vsync issue. Setting `gfx.vsync.hw-vsync.enabled` removes the flickering. But Firefox Desktop doesn't have this issue.

**Comment by paulrouget** [comment]
I think it comes from https://bugzilla.mozilla.org/show_bug.cgi?id=1152461.

**Comment by paulrouget** [comment]
Reverting bug 115246, I get this warning:

> [Parent 25537] WARNING: Tiled PaintedLayer with no scrollable container ancestor: file /Users/paul/mozilla/src/gfx/layers/client/ClientTiledPaintedLayer.cpp, line 150

But the animation is smooth again.

**Comment by paulrouget** [comment]
Filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1168889

**Comment by paulrouget** [comment]
This is supposed to be fixed now.
