### ISSUE TITLE
White screen when starting up

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#385]
@paulrouget when launching browser.html, the window is white while the assets are loaded from the cloud. I thought we had fixed this with HTTP caching?

@Gozala I remember there was a config file you had me add to profile to disable caching. I deleted my profile and the issue persists.

**Comment by paulrouget** [comment]
> the window is white while the assets are loaded from the cloud.

You mean the app is slow to load?

**Comment by gordonbrander** [comment]
Yeah, the window displays blank white while the front-end is loading. I was under the impression this would not happen because we were caching whatever front-end we had downloaded previously.

**Comment by paulrouget** [comment]
> Yeah, the window displays blank white while the front-end is loading. I was under the impression this would not happen because we were caching whatever front-end we had downloaded previously.

In theory yes. Apparently, it's not working.

**Comment by gordonbrander** [comment]
Video example of slow launch time https://slack-files.com/T03955LHZ-F060T9WUC-b38a235b0a

**Comment by paulrouget** [comment]
Looking at it.

**Comment by paulrouget** [comment]
Some timing data:

* https://gist.github.com/paulrouget/1196c5f0a1f09dabcc44
* https://gist.github.com/paulrouget/6777b2ee640686acf85d

**Comment by paulrouget** [comment]
Some notes:
- I explicitly clear the cache before doing the measurements
- here, total time to download the app is ~10s
- 7s without tiles
- larger files (by far) are pouchdb and react (as expected)

**Comment by paulrouget** [comment]
github cache most of the files, except:
- index.html
- theme.css
- tabstrip.css
- dashboard.css
- require.css
- the tiles

**Comment by paulrouget** [comment]
Here, with caching, it takes ~900ms to from `navigationStart` to load.

**Comment by paulrouget** [comment]
We clear gecko's cache on `unload`. Disable that now: 9a8a0533429478c8205c1698124f3a4ea3c7bb2c

**Comment by paulrouget** [comment]
Much better now :)

**Comment by gordonbrander** [comment]
@paulrouget it is much faster, but we still get a lot of jank and flashing during launch. See https://slack-files.com/T03955LHZ-F066GSZQE-129a4e8239.

**Comment by paulrouget** [comment]
You're right.

**Comment by gordonbrander** [comment]
- We know more or less what is causing this in Gecko
- Rather than fixing in Gecko, we would prefer to fix in Servo when we go-to-market.

Closing for now.

**Comment by gordonbrander** [comment]
Created a follow-up card to remind us to fix this in Servo https://trello.com/c/JhFBvanP/116-servo-render-content-immediately-when-launching-app-no-flash-of-white
