### ISSUE TITLE
Clicking "Apply update (restart required)" does nothing

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#386]
@paulrouget I'm guessing this is a temporary workaround? Runtime updates should not be prompted, but rather happen silently on launch.

**Comment by paulrouget** [comment]
Yep. Not supported yet. You need to restart manually.

https://github.com/mozilla/browser.html/blob/master/src/browser/update-banner.js#L84

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
