### ISSUE TITLE
100% CPU because of pouchdb

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#387]
The `onsuccess` callback (in pouchdb.js) is called constantly.

**Comment by Gozala** [comment]
@paulrouget did you get it all the time or is it triggered sometimes ?

**Comment by paulrouget** [comment]
Let me put that on hold. It doesn't happen anymore. Not sure what was going on earlier.

**Comment by paulrouget** [comment]
This keeps happening. Pouchdb code is constantly triggered.

**Comment by paulrouget** [comment]
Here is a profile: http://people.mozilla.org/~prouget/bugs/profile-issue-387.json

**Comment by gordonbrander** [comment]
@paulrouget says this happens almost every time

**Comment by paulrouget** [comment]
Usually, when it happens, it stops after some time (minutes).

**Comment by Gozala** [comment]
Is this still relevant ?

**Comment by paulrouget** [comment]
Nope.
