### ISSUE TITLE
Graphene crashes when mac is awaken

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#390]
It's a third times I see crashed grapahene when I awake mac from sleep.

**Comment by paulrouget** [comment]
What kind of crash is it? Actual crash?

**Comment by paulrouget** [comment]
Did it use to work?

**Comment by Gozala** [comment]
> Spinning wheel or crash (with osx dialog)?

Crash! Although I have not seeing it lately maybe already fixed in latest builds.

> Did it use to work?

It used to happen in the past and it was fixed, looks like it came back though.

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
