### ISSUE TITLE
Fullscreen mode no longer works properly

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#394]
Fulscreen mode now just maximizes window but no longer makes it fullscreen.

**Comment by paulrouget** [comment]
It's like `full-screen-api.ignore-widgets` is being ignored. Investigating.

**Comment by paulrouget** [comment]
It's because of bug 1105939. And I think it makes sense.

**Comment by paulrouget** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1172422

This also solves issue #263

**Comment by paulrouget** [comment]
Will be fixed in next nightly.
