### ISSUE TITLE
start.js doesn't support for win32.

### ISSUE THREAD

**Issue by lygstate** [mozilla/browser.html#395]

**Comment by paulrouget** [comment]
What is start.js?

**Comment by lygstate** [comment]
.bin/start.js

**Comment by paulrouget** [comment]
What do you mean it doesn't support win32?

On Tue, Jun 9, 2015 at 7:41 AM, Yonggang Luo <notifications@github.com>
wrote:

> .bin/start.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/browser.html/issues/395#issuecomment-110230787>
> .
>



-- 
Paul

**Comment by magsout** [comment]
I have this on Mac OS, maybe same error in windows ..:

```
> browser.html@0.0.2 start /Users/GuillaumeDEMESY/Github/stuff/browser.html
> ./.bin/start.js

events.js:141
      throw er; // Unhandled 'error' event
```

**Comment by Gozala** [comment]
This issue is very old, we no longer even have that file. Closing!
