### ISSUE TITLE
Window.open/close seems to be missing reference

### ISSUE THREAD

**Issue by KevinGrandon** [mozilla/browser.html#398]
Test case: http://jsfiddle.net/p907Ld4v/5/

It seems that window.open and the handler to close that window aren't fully supported yet. This works on b2g, so maybe it's just a matter of hooking into the mozbrowser event somehow?

**Comment by KevinGrandon** [comment]
I think I may have this fixed actually for my case. I think you just need to use the iframe element from the mozbrowseropenwindow detail, instead of constructing a frame. I might be able to submit a PR, but I'm still not too familiar with the browser.html guts.

**Comment by Gozala** [comment]
This is dupe of #475
