### ISSUE TITLE
Make about:settings editable (support for paintflashing and drawing layer borders)

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#400]
We should make booleans toggleable, and string editable.

**Comment by paulrouget** [comment]
I set these manually:

>  "debug.paint-flashing.enabled": true,
>  "layers.draw-borders": true

It would be much better if these could be checkboxes in about:settings.

**Comment by paulrouget** [comment]
Same for FPS & co.

**Comment by Gozala** [comment]
Was fixed at some point.
