### ISSUE TITLE
Is there a bugzilla issue on bugzilla.mozilla.org?

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/browser.html#401]
Is there a bugzilla issue on bugzilla.mozilla.org?
I want to follow the integration into Firefox and it is easier to do it there.

**Comment by paulrouget** [comment]
No.

**Comment by andreicristianpetcu** [comment]
@paulrouget  I should probably start from the problem: I want to follow the progress on integrating browser.html into Firefox. I know this is a long process but from what I understand this is the goal. I do not have time to contribute but I would like to see what is going on on this issue. What is the simplest way I can do that? In Firefox Core or in Firefox Browser I follow meta bugs like the port to gtk3. These bugs aggregate other smaller bugs. If someone makes a copr for Fedora that runs browser.html as default or some special build flag, I would like to test that.

What is the simplest way to follow the integration into standard Firefox? Thank you!

**Comment by paulrouget** [comment]
> integrating browser.html into Firefox

I'm not sure what you mean by that. There is not plan of integrating browser.html into Firefox as browser.html is a browser itself.

We use Gecko to render Firefox. We use Gecko to render browser.html.

We use bugzilla to track what's going at the gecko level, and github to track browser.html work.

**Comment by andreicristianpetcu** [comment]
Isn't this a possible replacement for the whole XUL-based UI of Firefox? Just like Firefox will eventually drop Gecko for Servo will it not drop it's XUL UI for browser.html?

**Comment by paulrouget** [comment]
In theory, yes. But that would be too much work, and it's not the goal.

**Comment by andreicristianpetcu** [comment]
Ok. I understand. Thank you!
