### ISSUE TITLE
[apzc] vertical scrolling doesn't have momentum or is blocked

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#404]
With APZC enabled and without scrollgrab or scrollsnapping, scrolling vertically behaves in one of these ways:
- scroll properly, with momentum
- scroll, but there's no mementum
- no scroll

Scrolling horizontally works properly.

With the "no scroll" behavior happens, I get these warning in the stdout:

> 0xXXXXXXX replacing unconfirmed target 0xYYYYYYYY with real target 0x0

**Comment by paulrouget** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1175564

**Comment by gordonbrander** [comment]
Resolved fixed.
