### ISSUE TITLE
If you ever enter fullscreen after restart you'll be in fullscreen

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#409]
This is really anoying bug that I discovered not a long time ago, if you ever enter fullsrceen no mater what you do after app restart you'll end up in fullscreen.

**Comment by paulrouget** [comment]
Good catch.

Patch under review: https://bugzilla.mozilla.org/show_bug.cgi?id=1134106

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
