### ISSUE TITLE
Experiment with Picture In Picture

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#411]

**Comment by paulrouget** [comment]
We can't render the video into another process. We need to find a way to open a new document in the content process and keep it visible.

**Comment by paulrouget** [comment]
We want to use `mozCaptureStream`.

**Comment by paulrouget** [comment]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1177793

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
