### ISSUE TITLE
Implement option-click for window maximize vs window fullscreen

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#426]
On OSX, holding down option will reveal an alternate window control that lets you maximize the window instead of going fullscreen. We should implement this. Will also need to produce a graphic for this.

cc @Gozala.

**Comment by Gozala** [comment]
@gordonbrander I think there are two things to consider here:

1. We need to update sprites to render `+` in a green button.
2. This seems to conflict with what you want to do in #796 
3. `window.resizeTo(window.screen.availWidth, window.screen.availHeight);` seems to do nothing at all, I imagine it's just not implemented by graphene /cc @paulrouget 

I think it's still good idea to hook up visuals and call to `window.resizeTo` as displayed above, once platform implements support for that function it will start working (regardless if it's servo or gecko).

**Comment by gordonbrander** [comment]
Yup, this is in conflict with #796. Closing in favor of #796.
