### ISSUE TITLE
Implement card dashboard view

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#427]
Getting to the dashboard:

- Clicking the location field or hitting `cmd l` will display the card dashboard and focus the location field (filled out with previous page's URL). Editing the URL will change the page the card displays.
- Clicking the (+) button or hitting `cmd t` will display the card dashboard and focus the input field (empty).
- Hitting space will focus the input field and show the card dashboard (same result as +).
- Pinch gesture takes you from page to card dashboard.
- Zoom gesture takes you from selected card to page.
- While on a page, hitting `esc` will first escape any inputs. If there is nothing else to escape, subsequent hits to `esc` will transition from page to dashboard.
- While on dashboard, hitting esc will take you from dashboard to previously selected page.
- Blurring the location field does not dismiss dashboard.

Interacting with cards:

- Clicking a card takes you to the page.
- 2-finger swipe up closes selected card
- Transition animations for dashboard/page
  - Transition dashboard->page: zoom out from page to card.  A combination of crossfade and scale.
  - Transition page->dashboard: zoom in from card to page.
  - Fallback: page->dashboard, dashboard->page: crossfade
  - These transitions are not 1:1 with swipe. They are canned CSS animations.
- Hitting `cmd w` when viewing a page will close the current page and take you to the card dashboard.

- We render cards with different templates depending on the results we get back from the scraper.

Extras:

- Cards are loosely scroll-snapped, so when scroll slows, a card is always at the center.
- Zoom-in / zoom-out transition for cards

**Comment by Gozala** [comment]
> Clicking the location field or hitting cmd l will display the card dashboard and focus the location field (filled out with previous page's URL). Editing the URL will change the page the card displays.

It will change card if on the same domain but create a new card if new domain isn't it ?

**Comment by Gozala** [comment]
What happens when you do `accel l` then `accel shift [`?

**Comment by Gozala** [comment]
Say I'm on `twitter.com` I hit link to `github.com` where is the new card added ? At the end of the list ? After twitter ? What if `twitter.com` is selected card I hit `accel l` type `github.com` and navigate to it, where is the new card added ?

P.S.: As far as I understood all zoom in / out animations assume card to zoom in / out is in the center not sure how this going to work out when we add new cards.

**Comment by gordonbrander** [comment]
Out of date.
