### ISSUE TITLE
web content iframe is blank

### ISSUE THREAD

**Issue by evilpie** [mozilla/browser.html#43]
I am using the current nightly on Linux x86_64. Sadly I just get a blank rectangle where web content should show up. When I move across the area the cursor actually changes to a pointer when I am over a Link. Seems like some graphics problem.

Built from https://hg.mozilla.org/mozilla-central/rev/b3f84cf78dc2

**Comment by pixelr0** [comment]
same on Ubuntu 15.04 64-bit

**Comment by paulrouget** [comment]
I think it's a regression in nightly.

**Comment by gordonbrander** [comment]
Graphene (htmlrunner) is now part of `mozilla/central`.
