### ISSUE TITLE
Can't set it up

### ISSUE THREAD

**Issue by nifker** [mozilla/browser.html#433]
when I try to run 'npm start' I get this error:
<code>
> browser.html@0.0.2 start /home/user/Schreibtisch/browser.html
> ./.bin/start.js

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /Applications/B2G.app/Contents/MacOS/graphene ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! browser.html@0.0.2 start: `./.bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser.html@0.0.2 start script './.bin/start.js'.
npm ERR! This is most likely a problem with the browser.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./.bin/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls browser.html
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Schreibtisch/browser.html/npm-debug.log
</code>
Log is the following: http://pastebin.com/Fj2SD80L

**Comment by Gozala** [comment]
Sorry it's being developed and tested on osx only for now so paths are all hard coded accordingly
