### ISSUE TITLE
Scraper script not returning expected results

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#435]
It works great with test cases I've created, but isn't returning expected results when run via `executeScript`. We're not doing much more than running `document.querySelector` so I think this is because script is running too early. We should run on DOM ready.

cc @Gozala

**Comment by gordonbrander** [comment]
Poking around in `scraper.js`, it looks like we don't actually ever have an `iframe.executeScript` function to call.

@paulrouget is this function missing from the Whistler build?

**Comment by paulrouget** [comment]
As discussed on slack, you might want to clear your profile.

**Comment by gordonbrander** [comment]
Delaying the scrape until dom is ready solves the issue.
