### ISSUE TITLE
Graphene crashes frequently

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#445]
@paulrouget I'm having frequent crashes in the latest whistler build. On OSX Yosemite 10.10.4.

**Comment by gordonbrander** [comment]
@paulrouget https://browserhtml.slack.com/files/gordonb/F07A4NG4D/2015-07-07_crash_report.md

**Comment by gordonbrander** [comment]
I _think_ what's triggering the crash is refreshing the interface. It looks like a few seconds after I refresh the interface, the browser crashes.

**Comment by paulrouget** [comment]
Crash happens in DOM Worker code:

> dom::workers::WorkerPrivate::RunBeforeNextEvent(nsIRunnable*)

I'm pretty sure we're hitting this https://bugzilla.mozilla.org/show_bug.cgi?id=1132436.

I should check if patch from https://bugzilla.mozilla.org/show_bug.cgi?id=1179909 fixes the issue.

**Comment by paulrouget** [comment]
Confirmed. Patch form bug 1179909 appears to fix the crash.

**Comment by gordonbrander** [comment]
Seems like that fixes it for me as well.
