### ISSUE TITLE
Crashed executeScript crashes Graphene

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#446]
cc @paulrouget

**Comment by paulrouget** [comment]
Is that the same as https://github.com/mozilla/browser.html/issues/445?

**Comment by gordonbrander** [comment]
> Is that the same as #445?
> 

Possible. Let's wait for the patch then I will try to reproduce this issue.

**Comment by gordonbrander** [comment]
Never mind, this was actually #445.
