### ISSUE TITLE
Build beautiful thumbnails (not just screenshots)

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#45]
Not just a screenshot. Not just an icon. Something nice. Think 300x200 (x2 for retina).

For example:

![screen shot 2015-01-10 at 09 44 15](https://cloud.githubusercontent.com/assets/373579/5690937/60bc3acc-98ad-11e4-97aa-e0a4d43f315a.png)

Things to experiment with:
- extract dominant color + nice typo
- provide already made thumbnails for top 500 websites (http://www.alexa.com/topsites)
- nice image upscaling of the favicon
- automatic detection of the most visually interesting region of the page

**Comment by PalmerAL** [comment]
You could try using <a href="https://github.com/breach/mod_strip/blob/master/controls/strip/color.js"> this js </a> from <a href="Http://breach.cc"> breach </a> for extracting the dominant favicon color (would need to ask about license though-right now the file says it is copyrighted). I would also be willing to make some of the thumbnails if needed.

**Comment by PalmerAL** [comment]
Something like <a href= "https://github.com/briangonzalez/rgbaster.js"> this </a> might work better actually since it already has an MIT license.

**Comment by PalmerAL** [comment]
Instead of the favicon, would it be possible to extract the apple-touch-icons with the favicon as a fallback? Most websites already have these, and they go up to 152x152 px.

**Comment by paulrouget** [comment]
Afaik, we already have a function to extract the dominant color.
apple-touch0icons are not large enough. We want something much larger.

**Comment by andreasgal** [comment]
Would be good to support them though since it can be part of a larger composed icon.

**Comment by bbondy** [comment]
> Afaik, we already have a function to extract the dominant color in Firefox.

See mozIColorAnalyzer
https://dxr.mozilla.org/mozilla-central/search?q=mozIColorAnalyzer&redirect=true

**Comment by paulrouget** [comment]
> Would be good to support them though since it can be part of a larger composed icon.

Yes. icon + dominant color + nice typo for example. Like the dropbox thumbnail here:

![screen shot 2015-01-10 at 18 30 29](https://cloud.githubusercontent.com/assets/373579/5692480/d0e569a6-98f6-11e4-93d4-426245471c52.png)

**Comment by bbondy** [comment]
There's some very similar work at the same link I just gave above from the metro project. Note that metro code is going to be removed from the tree soon, so check soon :)

Here's an example of that UI for the "start screen"
http://i1-news.softpedia-static.com/images/news2/Firefox-Metro-Preview-Available-for-Testing-5.png

**Comment by PalmerAL** [comment]
Once #40 is fixed, would it work to track, based on the user's scroll position, how much time the user spends on each part of a page and assume that the part the user spends the most time on is the most interesting/important part?

**Comment by paulrouget** [comment]
This is what I get by adding the apple touch icon on top of the dominant color:

![screen shot 2015-01-13 at 06 09 01](https://cloud.githubusercontent.com/assets/373579/5716255/b6767506-9aea-11e4-8347-d6aece291a4a.png)

**Comment by andreasgal** [comment]
Love it. Great start. We can improve from here.

**Comment by PalmerAL** [comment]
I've started working on designing some tiles for popular websites. https://github.com/PalmerAL/website-tiles/

**Comment by paulrouget** [comment]
Thanks @PalmerAL . We'll see how we can use these. No need to implement more now as we don't know yet how we want to implement this.

**Comment by paulrouget** [comment]
We want these thumbnails to be responsive. 200x120 (on retina, 400x240), or 100x60. Shrinking the margins or downscaling the content in a smart way.

**Comment by paulrouget** [comment]
@PalmerAL We are actually using your tiles at the moment. Not sure how far we'll go with that, but I filed a couple of issues.
