### ISSUE TITLE
favicons aren't always displayed, even when they exist

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#455]
Looks like we respond to `onIconChange: Event('mozbrowsericonchange')`, but I suspect this doesn't fire unless the page has a `<link rel="shortcut icon">`.

cc @Gozala

**Comment by paulrouget** [comment]
`mozbrowsericonchange` is fired as soon as a `<link rel="icon">` or `<link rel="apple-touch-icon">` is found.

It's fired multiple times if there are multiple `<link>`.

**Comment by gordonbrander** [comment]
We should default the model to `https://example.com/favicon.ico`, then change the icon field if we get a `mozbrowsericonchange` event. That way we will also show favicons for web pages that have a `/favicon.ico` but don't list it in their meta (there are many like this).

**Comment by paulrouget** [comment]
I wrote that a while ago: https://gist.github.com/paulrouget/f79af67fab097175e27a

**Comment by paulrouget** [comment]
It includes the fallback, support for touch, moz-resolution, & co.

**Comment by paulrouget** [comment]
Knowing that icons were set that way:

```js
  WebView.changeIcon = icon => state =>
    state.get('icons') ? state.setIn(['icons', icon.href], icon) :
    state.set('icons', Map([[icon.href, icon]]));
```

**Comment by paulrouget** [comment]
I'll take care of that.
