### ISSUE TITLE
When a webview is open in the background, it stays visible until it's loaded

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#484]
STR:
- open a web page
- Cmd-Click on a link
- a new webview is open
- stays above the current webview, disappear one is loaded

We used to keep the iframe `setVisible(true)` until the screenshot is done, but set the iframe `display:none` (or something like that). I guess now the `display:none` is not happening until the screenshot is done.

**Comment by gordonbrander** [comment]
Fixed by https://github.com/mozilla/browser.html/pull/492
