### ISSUE TITLE
`window.close()` from content should close a window.

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#493]
windows don't close (if requested from content) (mozbrowserclosewindow) part #476

**Comment by Gozala** [comment]
I presume this is referring to [`mozbrowserclose`](https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowserclose) event. We don't seem to get that event at all, here is my test:


```js 
var browser = document.querySelector("iframe[mozbrowser]");

var listener = function( event ) {
  console.log("Asking for close:" + JSON.stringify(event.detail));
}

browser.addEventListener("mozbrowserclose", listener);
browser.addEventListener("mozbrowserclosewindow", listener);

browser.src = 'data:text/html,<button onclick="window.close()">close</button>'
```

I click close button and see no events logged.

**Comment by Gozala** [comment]
@paulrouget Am I testing it wrong ?

**Comment by paulrouget** [comment]
You're not. Wondering what's going one… I'll investigate. Apparently, we don't get `window.open()` either.

**Comment by paulrouget** [comment]
(I was wrong about window.open).

**Comment by paulrouget** [comment]
This is normal. It's because `dom.allow_scripts_to_close_windows` is `false`.
