### ISSUE TITLE
iframes should not be hidden with visibility:collapse

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#495]
Follow up for https://github.com/mozilla/browser.html/pull/492#discussion_r34634442

- We can't grab screenshots from iframes if we use `display: none`. It should work but it doesn't.
- `visibility: collapse` _shouldn't_ work according to the spec (see comment above https://github.com/mozilla/browser.html/pull/492#discussion_r34635110) but it does.

We're use `visibility: collapse` to hide the iframes while still grabbing screenshots. It's a workaround that relies on an implementation bug to get around an implementation bug. We should follow up with a fix.

**Comment by paulrouget** [comment]
It doesn't use collapse anymore.
