### ISSUE TITLE
[Tabs] Add new tab button

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#5]
_From @joshua-s on December 9, 2014 17:17_

It would be nice to have a "+" button to open new tabs.

![screen shot 2014-12-09 at 12 16 13 pm](https://cloud.githubusercontent.com/assets/1479244/5361963/3f6e069c-7fc7-11e4-9994-e7c87ff1ab00.png)

_Copied from original issue: paulrouget/firefox.html#15_

**Comment by paulrouget** [comment]
_From @AVGP on December 10, 2014 9:45_

I'd like to give it a try :)

**Comment by paulrouget** [comment]
Sure. Shoot.

**Comment by paulrouget** [comment]
_From @AVGP on December 10, 2014 23:19_

I struggle to find the original firefox "add new tab" button image - any hints?

**Comment by paulrouget** [comment]
http://mxr.mozilla.org/mozilla-central/source/browser/themes/osx/tabbrowser/newtab.png
http://mxr.mozilla.org/mozilla-central/source/browser/themes/osx/tabbrowser/newtab@2x.png
http://mxr.mozilla.org/mozilla-central/source/browser/themes/osx/tabbrowser/newtab-inverted.png
http://mxr.mozilla.org/mozilla-central/source/browser/themes/osx/tabbrowser/newtab-inverted@2x.png

**Comment by paulrouget** [comment]
_From @nt1m on December 16, 2014 22:30_

I've got an SVG here : https://github.com/nt1m/FirefoxDevToolsSVG/tree/master/browser

**Comment by paulrouget** [comment]
Let's not use SVG for now. We also want Firefox.html to run on Servo, and Servo won't be supporting SVG anytime soon.

**Comment by AVGP** [comment]
Anybody who wants to take this shall do so, I failed at getting anywhere with this

**Comment by gordonbrander** [comment]
No longer relevant. Closing for now.
