### ISSUE TITLE
Can't select URL in URL bar with cursor

### ISSUE THREAD

**Issue by Martz94** [mozilla/browser.html#50]
Hi there!

When trying to select a URL with the cursor, it moves the window instead. I don't think this should happen. People should be able to select URLs when keeping pressed the mouse button.

Thoughts?

**Comment by PalmerAL** [comment]
This happens because the entire HTML content is draggable. This also happens when trying to select text  or drag and drop things on a webpage

**Comment by paulrouget** [comment]
Yep. Working on it. https://bugzilla.mozilla.org/show_bug.cgi?id=1118169

**Comment by PalmerAL** [comment]
As a temporary solution until this is fixed, could you have a floating element over the browser in the xul window that has the dragging, but not apply the dragging to the main browser element?

**Comment by paulrouget** [comment]
Or just not use chrome margins.

**Comment by KevinGrandon** [comment]
@paulrouget @Martz94 - Seems the bugzilla bug is fixed. Can we close this issue now?
