### ISSUE TITLE
Implement back/fwd 2 finger swipe gestures

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#502]
Part of sythesis UI that has not yet been implemented.

**Comment by gordonbrander** [comment]
We can use this https://developer.mozilla.org/en-US/docs/Web/Events/MozSwipeGesture

**Comment by paulrouget** [comment]
I'm not sure why, but swipe gestures don't work anymore. I'll investigate.

**Comment by gordonbrander** [comment]
We should slide one page over the other while you swipe.

**Comment by paulrouget** [comment]
Like Safari?
And it goes through history, not through tabs, right?

**Comment by gordonbrander** [comment]
> Like Safari?
> And it goes through history, not through tabs, right?
> 
Right.

**Comment by gordonbrander** [comment]
Sliding the new page over the old page is definitely the correct design decision, but it will probably need platform support. Options:

- We can defer for the MVP (https://github.com/mozilla/browser.html/milestones/Developer%20preview%20(Gecko%20Graphene)) and revisit in Servo.
- Slide over blank page, then render when slide is complete.

**Comment by gordonbrander** [comment]
Blocked by https://github.com/mozilla/browser.html/issues/571
