### ISSUE TITLE
executeScript throws error on pages that have theme-color

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#505]
@paulrouget this is a strange one. I'm getting an error from `executeScript` only on pages that have `theme-color` information. It doesn't matter what the script is.

<img width="1070" alt="screen shot 2015-07-17 at 13 57 11" src="https://cloud.githubusercontent.com/assets/58421/8757042/ef135888-2c8b-11e5-96de-528c34c56d25.png">

<img width="977" alt="screen shot 2015-07-17 at 13 56 44" src="https://cloud.githubusercontent.com/assets/58421/8757048/f3b53140-2c8b-11e5-9e72-878574b9cad2.png">

**Comment by gordonbrander** [comment]
We get results back from scraper despite the error

**Comment by gordonbrander** [comment]
The error seems to happen half a second after the page has finished loading. Only on pages that have a metachange event :/

<img width="977" alt="screen shot 2015-07-17 at 14 41 45" src="https://cloud.githubusercontent.com/assets/58421/8757775/c6e55b54-2ccc-11e5-919f-f6dc42b46933.png">

**Comment by Gozala** [comment]
We no longer make use of executeScritp
