### ISSUE TITLE
We should probably strip HTML from <title>

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#508]
We escape HTML, but site authors shouldn't be adding tags to titles anyway. We can lend a hand to poorly behaving sites by stripping tags vs escaping them.

<img width="587" alt="screen shot 2015-07-20 at 11 39 38" src="https://cloud.githubusercontent.com/assets/58421/8783984/37666658-2ed4-11e5-8a8a-f00d0d4d22a4.png">

**Comment by Gozala** [comment]
New UI works differently.
