### ISSUE TITLE
Package JS code with r.js, babel and uglify

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#522]
We want to package browser.html.

We can't use r.js out of the box for 2 reasons:
- `require('common/worker!...')` is not supported
- uglifyjs doesn't support ES6

I'm not comfortable with all these tools, but here is what I managed to do so far:

- use react.min
- update requirejs to latest version (necessary)
- comment out worker code
- `build.js`: https://gist.github.com/paulrouget/0ba08478ae7a7e6d2299
- /node_modules/requirejs/bin/r.js -o ./build.js
- it creates a file named `main-built.js`
- `babel main-built.js > main-built-es5.js`
- I had to add a call to `super()` in element.js (see https://github.com/babel/babel/issues/1131). ES6 code doesn't work anymore, but ES5 code works
- `./node_modules/uglify/bin/uglify -s ./main-built-es5.js -o ./main-built-es5-min.js`

I end up with a file that is ~280K, which is not bad (600k before).

@Gozala can you take over? You'll do a better job than me.

**Comment by paulrouget** [comment]
First step comes with PR #526.

**Comment by Gozala** [comment]
Done in #547
