### ISSUE TITLE
Prerender app before packaging

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#527]
We need to render the app on load. We can't wait for react and all the modules to load.

PR #523 introduces a way to save previous rendering into localstorage. But this won't work for the first load. We can fill the `<body>` of `index.html` when we package the app.  React allows that (server side rendering).

`npm run package` should run a node script that generate the HTML code, and append it to `index.html` or `prerendering.js`.

**Comment by Gozala** [comment]
Closing this for now as #547 covers it, any further improvements can be tracked separately.
