### ISSUE TITLE
Fix icon size

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#529]
@paulrouget our icon is slightly too big.

<img width="269" alt="screen shot 2015-07-29 at 08 33 35" src="https://cloud.githubusercontent.com/assets/58421/8961875/8f357af0-35cc-11e5-839f-249dec143c45.png">

**Comment by gordonbrander** [comment]
I may need to tweak the border size in the graphic as well.

**Comment by gordonbrander** [comment]
Updated icon https://browserhtml.slack.com/messages/internal/files/F08BBSAT1/

**Comment by paulrouget** [comment]
Looks good:

<img width="79" alt="screen shot 2015-07-30 at 09 12 05" src="https://cloud.githubusercontent.com/assets/373579/8977622/1762a5c8-369b-11e5-9270-0a59b098060c.png">

Updating Graphene.
