### ISSUE TITLE
Navigating from page to page with color theme results in flashes of color

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#536]
1. Open http://imgur.com
2. Click on an image.

You'll see the header fades from `#222 -> #FFF -> #222` quickly.

**Comment by gordonbrander** [comment]
The question is what to do when we have a previous page with a pallet. Carry it over? This would mean that clicking on a link to a different domain could carry the previous pallet with you. That would be a bug

Really what we want to do is load opened pages in the background for a moment until we're ready to switch.

cc @Gozala: could you suggest the best approach here?

**Comment by KevinGrandon** [comment]
We had a similar problem in FxOS. You do get the metachange event before the page is loaded as typically the meta tag is included in the initial HTML payload. I believe we waited until loadend (instead of locationchange) and if no metachange was found, then we display the default.

**Comment by paulrouget** [comment]
> Really what we want to do is load opened pages in the background for a moment until we're ready to switch.

Define "ready to switch". We show the page as soon as it starts loading. Delaying would be against the spec and will most likely break pages.

I think we should reset the pallet after a short delay. Like 2 seconds.

**Comment by gordonbrander** [comment]
@paulrouget I'm pretty sure this is how Firefox and other browsers behave today:

1. Click link
2. Start loading immediately
3. Show page on first paint, or after ~2.5s delay.

This does a few things:

- You can "change your mind" and click a different link, interrupting the first.
- By skipping the "flash of white" you see fewer "noise frames", which makes things feel faster.

If we did something similar, we would be able to theme the location bar consistently, since this information would be available by that time.

**Comment by paulrouget** [comment]
This is how it works:

1. Click link
2. Connecting to the server (no response yet), page (1) stays up
3. first response from the server, page starts loading, page (1) is trashed
4. first paint of the page

Use can "change its mind" during (2).

Both Firefox and Graphene work the same way.

But during phase 2 we trash the pallet. We should trash it only at (3) (when we get the "loading" event).

**Comment by gordonbrander** [comment]
Ok, that sounds good.

**Comment by paulrouget** [comment]
iirc, we get the loading event at connection. I think we will need to introduce more granular events. We need to re-land bug 1125713.

**Comment by Gozala** [comment]
So right now what happens is that on `LoadStrated` we reset the page state which includes thumbnail, scraper data and also a color pallet:

https://github.com/mozilla/browser.html/blob/50307661782181eff31a165b7eab63bfcc38fce3/src/browser/web-page.js#L134

We don't necessarily need to do it although we need to reset card details at some point my understanding is that it should happen at phase 3, but @paulrouget is there event that signifies that we entered that phase ?

For addressing this specific issues we could probably just keep the color pallet during page state reset if the domain is the same.

**Comment by Gozala** [comment]
Hmm looks like we don't know what is current `uri` so it's not that obvious to preserve pallet with in the domain.

**Comment by Gozala** [comment]
So #554 sort of mitigates general issue by preserving colors with in the single domain, you would still get a flickering if say your on domain `A` and navigate to domain `B` and both seem to have non default color pallet.

In proper fix we would never reset color pallet but instead wait for a deterministic `PalletChanged` event that is fired on every page (that  is not a case currently, it is only fired if there is a meta tag for `theme-color` or if domain is in the list of curated domains) so we would never need to reset pallet but rather just update it to a proper value.

**Comment by Gozala** [comment]
Made a second pass on this, I think  this is more complete solution. Now color pallet is changed either by lookup in curated list of domains (takes a precedence) or by a meta tag containing `theme-color` if pallet has not being updated by either source between `loadstart` and `loadend` then pallet is reset. This eliminates intermediate color changes during navigation.

**Comment by paulrouget** [comment]
> We don't necessarily need to do it although we need to reset card details at some point my understanding is that it should happen at phase 3, but @paulrouget is there event that signifies that we entered that phase ?

No. We used to have one, but it got backed out for performance reasons. I know how to fix that though. Is #554 a workaround or a proper solution? Should I add a "connected" event to the iframe?

**Comment by paulrouget** [comment]
I have a working patch that tells us when we enter phase 3. It sends a `mozbrowserconnected` event.

Should I land that?

**Comment by Gozala** [comment]
@paulrouget I don't think we still need that event for this specific feature, you can find more details on the final solution here: https://github.com/mozilla/browser.html/pull/554#issuecomment-128503945
