### ISSUE TITLE
ctl tab quickly should switch immediately

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#538]
Currently when hitting `ctl tab` we fade to overview mode. If you command tab very quickly, we should immediately switch pages without the fade.

- [ ] Delay switching to `select-web-view` until `ctl tab` has been held down for 100ms
- [ ] Delay `ctl tab` key repeats until `select-web-view` has been showing for 500ms (we should probably also throttle repeats)
- [ ] Add distinction between WebView `selected` and `highlighted`
- [ ] Select highlighted webview on `SynthesisUI.Select` completion. Then fade to `show-web-view`.
- [ ] If `ctl tab` keys are released prior to 100ms delay, don't show `select-web-view`. Select next web view immediately.

^ The same obviously applies to `ctl shift tab`.

**Comment by paulrouget** [comment]
You mean `Ctrl-Tab`?

**Comment by gordonbrander** [comment]
Yes, sorry.

**Comment by gordonbrander** [comment]
We need to do something like:

                             *-> delay interrupted by keyup -> switch to prev tab immediately
                            /
    ctl tab -> delay 30ms -*
                            \
                             *-> delay complete -> fade to select-web-view mode
