### ISSUE TITLE
Session restore: maybe we should not restore the state 

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#542]
I'm not sure we want to restore the state when the app restart/reload. Most of the information stored in the state have no point of being restored. Other info should be stored in the settings, like in Gaia. Settings are more performant than localStorage, and can be synchronized online easily (because the Gaia people are working on this).

Opened tabs will eventually be stored and restored with Gecko's session restore mechanism.

**Comment by paulrouget** [comment]
We should also see how that deals with prerendering.

Settings are asynchronous, making it impossible to render the app synchronously with a restored state.

**Comment by Gozala** [comment]
I have figured out the issue which is relate to selection state, when we select all we set selection to `{start: 0, end: Infinity}` but `JSON.serialize({start: 0, end: Infinity})` produces `{start:0, end:null}` which causes invalid state to be stored for the session.

The for this issue is one liner that I've included in the different pull:
https://github.com/mozilla/browser.html/pull/547/files#diff-2c8b4521eac83629c3dc939a131e56f7R229

I can cherry-pick it to land separately.

**Comment by Gozala** [comment]
> Other info should be stored in the settings, like in Gaia. Settings are more performant than localStorage, and can be synchronized online easily (because the Gaia people are working on this).

Currently we store state to `localStorage` but that's only so because we never got to update that code to store that state into indexed db instead.

> Opened tabs will eventually be stored and restored with Gecko's session restore mechanism.

Even though gecko's session restore mechanism will allow us to restore some of the state I don't believe it will be able to fully replace a need for storing state as we would still need to create DOM tree of the browser UI at startup don't we ?

**Comment by Gozala** [comment]
In general blocking UI to fully restore APP state is probably not an ideal solution. I think it would be great if we designed our UX such that app state could be incrementally restored, we could also probably use some animations to make perception of restoring faster.

@gordonbrander do you have any thoughts on this ?

Also please not that once we store serialized state into indexed db restoring it will become async which will pose extra delay.

**Comment by Gozala** [comment]
Alternatively it would be great if gecko could just store state of the DOM and restore it on next app lunch, that way ui could be immediately usable while react (or whatever else could deal with figuring out what the DOM should look like). Also note that while service workers could be used to kind of achieve that it still won't be ideal as we would have to serialize markup and transfer it to service worker to be stored for the next load, doing that on unload is going to be racy as it's async operation, doing it on every state change would add too much overhead to be worth it.

**Comment by paulrouget** [comment]
We should store in settings anything the user might want to sync or save (themes, privacy preferences, search provider, …).

If there anything in the state that we want to save for next session, we can't rely on the unload event (think about crashes), so it can't be sync (or we would freeze the UI time to time), so it has to be indexeddb.

What is not considered a setting but still need to be stored persistently? The list of tabs?

For the prerendering, I agree that we should design a UI that could be incrementally restored. index.html could include a minimal non-interactive version of the UI. Now, let's imagine we support themes. The user use a pink theme. Is it ok if the UI is first grey then switch to pink? If not, the prerendering needs to be aware of the theme data, and prerendering needs to happen synchronously. So how do we do that? I see 3 options: 1) we use syncstorage for some data 2) we are ok with having a basic UI that shows up at startup that is will change ~200ms later 3) we don't show the UI at load, but later, with a custom event.

**Comment by Gozala** [comment]
> What is not considered a setting but still need to be stored persistently? The list of tabs?

- value of the input field
- mode in which browser is (dashboard / web-view / new-tab / etc..)
- list of tabs with their own small details (like theme colors, scrapped data etc...)

> For the prerendering, I agree that we should design a UI that could be incrementally restored. index.html could include a minimal non-interactive version of the UI. Now, let's imagine we support themes. The user use a pink theme. Is it ok if the UI is first grey then switch to pink? If not, the prerendering needs to be aware of the theme data, and prerendering needs to happen synchronously. So how do we do that? I see 3 options: 1) we use syncstorage for some data 2) we are ok with having a basic UI that shows up at startup that is will change ~200ms later 3) we don't show the UI at load, but later, with a custom event.

I was thinking more in line of having something like a login screen that logs into previous session with an animation that should give us little time to do the restoring. Or just start with a single zoom-ed in page hopefully that we can restore from cache and while user is occupied looking at it we could load the rest.

Still the easiest but still practical solution would be to store serialized DOM that is restored on restart that where react get's to re-render will have nothing to do.

**Comment by Gozala** [comment]
I think this not as relevant right now as it used to be. Let's reboot this conversation once we have more of it working on servo.
