### ISSUE TITLE
Prerendering: storing in localStorage is useless if we only save a reset state

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#543]
We store in localStorage the rendering of a reset state. We want to generate HTML code during packaging (see #527). That means the result of the rendering stored in localStorage will always be the same as the HTML code rendered at packaging.

If we don't save the rendering on unload, there's no point of saving the rendering.

**Comment by Gozala** [comment]
Let's discuss the sessions and how do we restore them in #542 as decisions there will have direct impact on things like this.
