### ISSUE TITLE
Reconcile create-web-view and edit-web-view states

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#556]
We need it to be obvious when we're in "create web view" mode. Ideas:

- Maybe merge edit-web-view and create-web-view modes?
- Select the ghost tab.
- Change the selection style too?

**Comment by Gozala** [comment]
I like this idea, I think I suggested and create a bug for it before.

**Comment by gordonbrander** [comment]
I'll think through the interaction details on this bug and then hand off when I have a description of exactly what we need.

**Comment by gordonbrander** [comment]
Depends on viewport work https://github.com/mozilla/browser.html/issues/557#issuecomment-130870429

**Comment by gordonbrander** [comment]
Step one: we should fix the interaction details around the ghost tab: `edit-web-view`: show a `+` button. Clicking `+` button transitions to `create-web-view`. `+` morphs into ghost tab.

We might further simplify by

- Allowing unlimited empty tabs to be created at head of list
- Showing url (if any) of highlighted tab in location bar
- Committing edit and switching to `show-web-view` when you hit enter.

**Comment by gordonbrander** [comment]
Here's the iteration I'm working on

**Comment by gordonbrander** [comment]
Does not apply to `perspective-ui`.
