### ISSUE TITLE
Support "enough" tabs

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#557]
We eventually want to support infinite tabs, but if implementation is difficult, we can take a temporary shortcut for MVP. Some potential shortcut ideas:

- Cap the number at 100. Disable "new tab" when you hit 100.
- Render all tabs, but if there are more than 20 tabs, unload old ones until you have only 20 living tabs.
- Maybe some other shortcut?

**Comment by Gozala** [comment]
What happens when you try to open 101st tab ?

**Comment by gordonbrander** [comment]
@Gozala updated requirement. The idea here is that we should not get stuck for MVP if "infinite" tabs is difficult. We can settle for "lots of tabs" and then release an update with true infinite tabs later.

**Comment by gordonbrander** [comment]
Per our conversations, it sounds like we want some rudimentary form of viewport
