### ISSUE TITLE
Add scroll snapping to card dashboard

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#558]
We should be able to use CSS scroll snapping.

**Comment by Gozala** [comment]
Does not seem to have any effect at least on my machine. I think we should keep that open until it actually works. I suspect current build does not yet have scroll snapping.

**Comment by paulrouget** [comment]
@Gozala make sure to disable APZC.

**Comment by paulrouget** [comment]
> I suspect current build does not yet have scroll snapping.

They do.

**Comment by Gozala** [comment]
Ok so I seeing this warning in the console:

```
15:15:30.976 Warning: Unsupported style property scroll-snap-coordinate. Did you mean scrollSnapCoordinate? index.js:27201:7
```

I think that explains why it did not worked for me.

**Comment by gordonbrander** [comment]
@Gozala Huh, I thought the style API accepted either one. I can submit a follow-up PR. However, I suspect this may not fix it for you, since scroll snapping works fine for me as-is.

**Comment by Gozala** [comment]
> @Gozala Huh, I thought the style API accepted either one. I can submit a follow-up PR. However, I suspect this may not fix it for you, since scroll snapping works fine for me as-is.

Issue was that have not restarted after disabling `APZC`. Now it works although it does not feel smooth :(
My guess is react still supports styles as is but is planning to drop that that's why we see this warning. @gordonbrander followup change would be great to get rid of this warning.

**Comment by paulrouget** [comment]
> Issue was that have not restarted after disabling APZC. Now it works although it does not feel smooth

gfx team is actively working on supporting snapping + apzc. Should get better soon.
