### ISSUE TITLE
Implement "top hit" for Awesomebar

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#559]
Per the Synthesis UI design.

- In addition to history and search suggestions, search for root domains in history that match search term (e.g. facebook.com).
- If we have a match, style it as a "top hit".

This is to help people get back to their favorite websites.

**Comment by gordonbrander** [comment]
![group](https://cloud.githubusercontent.com/assets/58421/9239415/57b79730-4110-11e5-9906-7df06227d875.png)

**Comment by Gozala** [comment]
#596
