### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#56]
I think we really need to come up with some test automation solution, I for one really wanted to write some tests for the history API to see if all things work as expected.

So far I'm thinking of picking one of the popular test frameworks for the web, but then I'm not entirely sure how they can be integrated.

**Comment by bbondy** [comment]
Possibly something like Jest, but it does not have support for AMD modules.  Our modules could be written in such a way that it is compatible to commonjs modules though.

**Comment by Gozala** [comment]
@bbondy I wish we could just use commonjs, but I'm afraid fxos apps restrict all forms of eval, which I'm afraid what module loaders that support commonjs format use. If you know how to workaround that, I'm all ears as I find amd rather unpleasant.

**Comment by bbondy** [comment]
I'm not sure what the plan is for this front end eventually, but perhaps a custom build of b2g with an ifdef around the part that restricts it.

**Comment by bbondy** [comment]
webpack or browserify would work no? Or are you saying they use eval too? I would think they just include a single file and work out an eval system within that loaded file. I'm not sure how they work internally though.  Anyway maybe we're getting off track from what the task is :).

**Comment by bbondy** [comment]
Yep tried via browserify and it does evals. I guess via the ifdef and custom b2g build, but probably not worth it.

**Comment by paulrouget** [comment]
Also consider Gaia's testing mechanism.

**Comment by bbondy** [comment]
I converted a Firefox OS app that I have to CommonJS and have it loading / working in the simulator via browserify.  I was getting a CSP error before because of a local script tag in the html without specifying an src.

**Comment by Gozala** [comment]
@bbondy browserify is great, and I'd be happy to use it, but then I really don't want to introduce a build step.

Another option maybe to use a service worker to intercept network requests and wrap modules into amd wrapper but I'm not sure what the state of service workers implementation is right now.

**Comment by vegetableman** [comment]
@Gozala you could use systemjs which doesn't have any sort of build step and loads commonjs and amd modules without any problems.

**Comment by bbondy** [comment]
A build step is really not that big of a deal, you just start gulp and it watches and runs your pipeline. Then you can use JSX, browserify, Flow type checking, etc.

**Comment by Gozala** [comment]
@vegetableman I have not heard of systemjs, I'll take a look at it. I'd be happy if they manage that without eval. I have also tried hack with transpilation using service workers: https://github.com/Gozala/commonjs-to-amd-sw which works on chrome but in firefox I keep getting error during sw registration.
```
DOMException [AbortError: "The operation was aborted. "
code: 20
nsresult: 0x80530014]
```

**Comment by vegetableman** [comment]
I do see eval in the systemjs code but @guybedford could answer that.

**Comment by guybedford** [comment]
@vegetableman there's a CSP build of SystemJS that does script injection only at https://github.com/systemjs/systemjs/tree/master/dist. For this, it requires CommonJS be built into a wrapper System.registerDynamic output, which is supported in https://github.com/systemjs/builder.

Also the 'self-executing' bundle does no eval either.

Not entirely sure how it would be needed here, but if it is a useful option just ask if you need help.

**Comment by vegetableman** [comment]
Thanks for answering @guybedford. Using a builder introduces a build step, which doesn't fulfil the use case here. https://github.com/mozilla/browser.html/issues/56#issuecomment-72134057

**Comment by KevinGrandon** [comment]
The FxOS integration tests are fairly well-suited for this task and are written in javascript, and using marionette. It's already running tests using b2g desktop, so we might be able to hack it quickly to simply run against a different "system" app.

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette
https://developer.mozilla.org/en-US/Firefox_OS/Platform/Automated_testing/Gaia_integration_tests
