### ISSUE TITLE
Drag / 2-finger flick tabs to close

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#560]
For interaction let's try:

- Swipe up or down by a fixed `threshold` to close card (a threshold of 200 is probably a good place to start, but we should make this tweakable)
- If user releases inside `threshold`, card moves back into place.
  - Good: we transition back using a fixed-duration CSS animation
  - Better: we base transition duration on avg velocity of swipe upon release, but will add accel to velocity until we reach `minimum` if velocity is too slow.
- When user passes `threshold`, but has not yet released, card transitions to semi-transparent using fixed CSS transition. If user moves card back within threshold, card transitions to opaque.
- When user releases finger(s) from trackpad past threshold, we trigger the close animation:
  - Card moves in direction of swipe, at swipe velocity (we add accel until velocity is at `minimum`, if velocity is too slow)
  - At the same time, card fades out. Fade progress should be tied to distance. I think we want card to be "gone" visually at about `100px` past `threshold`. We may want to make this tweakable too.
  - When card is gone, cards to the left and right move in to fill space, using a fixed-duration CSS transition.

**Comment by Gozala** [comment]
Depends on #571
