### ISSUE TITLE
reparenting `event.detail.frameElement` after animation frame causes a crash

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#564]
Blocks  #483

 I'll try to create a simple test case and then submit a b2g bug to bugzilla

**Comment by Gozala** [comment]
Ok crash seems to happen if `iframe` is inserted into `head` and only afterwards under desired parent. Stashing it into `document.body` seems to not cause a crash, but reparenting also seems to cause `frameElement` to loose it's special connection with an opener.

**Comment by gordonbrander** [comment]
@Gozala should this still be open?

**Comment by Gozala** [comment]
I think this is a bug that is worth fixing on gecko side, that being said I don't really care if we keep it open or not.

**Comment by Gozala** [comment]
No need to keep this open on our side as we can't really do anything about it.
