### ISSUE TITLE
Use of `event.detail.frameElement` should be allowed in a different tick

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#565]
Also see #564

**Comment by paulrouget** [comment]
But then, how does it work internally? How would the engine (gecko or servo) know that the iframe will be used in the future?

Sadly, `window.open` is a sync operation, so if the iframe is not handled right away, the engine has to assume it will never be used. Or, it can delay the event (pause the event loop in the child process) until the iframe object is garbage collected (or is not). But that would seriously delay the time it takes to execute `open.window`.

We could add some sort of timeout (ugly), or attach a property to the event saying the window will be use in the future for sure.

I think the only realistic solution is to go back to the child process only after a RFA, but that's very specific to browerhtml's internals.

Do we really need that? This kind of constraint would be very inconvenient.

**Comment by paulrouget** [comment]
Imagine this:

`var win = window.open()`

In Electron:

* if `frameName` is used later (next tick), is `win` null?
* if `frameName` is used later (setTimeout(2000)), is `win` null?
* if `frameName` is not used, is `win` null?
* if `frameName` is used right away, does `win` as a value?

**Comment by Gozala** [comment]
> But then, how does it work internally? How would the engine (gecko or servo) know that the iframe will be used in the future?

That is also why I think #566 is more appropriate solution. As far as fixing current API goes most reasonable solution would be to let GC do the job. If JS keeps reference it is expected to be used, once reference is dropped it's no longer used.

Alternative less desired, but still better solution would be to allow storing it into document fragment to indicate that that it's going to be used.



> Sadly, window.open is a sync operation, so if the iframe is not handled right away, the engine has to assume it will never be used. Or, it can delay the event (pause the event loop in the child process) until the iframe object is garbage collected (or is not). But that would seriously delay the time it takes to execute open.window.

Wait `frameElement` does not load anything if you put it into document right now, it starts loading only when you set an src.

**Comment by Gozala** [comment]
> if frameName is used later (next tick), is win null?
> if frameName is used later (setTimeout(2000)), is win null?
> if frameName is not used, is win null?
> if frameName is used right away, does win as a value?

`win` is `WindowProxy` window which is documented BTW, I believe messages / actions are queued till target window finished initialization.

**Comment by Gozala** [comment]
> Imagine this:

var win = window.open()

> In Electron:

> if frameName is used later (next tick), is win null?
if frameName is used later (setTimeout(2000)), is win null?
if frameName is not used, is win null?
if frameName is used right away, does win as a value?


Also what happens today if I append `event.detail.frameElement` to document, but don't navigate it to the requested `event.detail.url` ? All of those question seem relevant in such scenario as well don't they ? Well maybe apart from `window.close()` which I think is also easy to solve with `frameName` you just drop the `frameName` so even if it's used later it will no longer have a `window.opener`.

**Comment by paulrouget** [comment]
> That is also why I think #566 is more appropriate solution. As far as fixing current API goes most reasonable solution would be to let GC do the job. If JS keeps reference it is expected to be used, once reference is dropped it's no longer used.

Doesn't that mean in the child process `window.open` will have to wait until next GC?

> Wait frameElement does not load anything if you put it into document right now, it starts loading only when you set an src.

So what about it? Doesn't change the fact that the original event loop will be blocked much longer.

> win is WindowProxy window which is documented BTW, I believe messages / actions are queued till target window finished initialization.

So it returns a WindowProxy in these 2 cases?

* if frameName is used later (next tick), is win null?
* if frameName is used later (setTimeout(2000)), is win null?

I just want to understand how Electron implements that internally. If they are all `null`, no bother looking. 

For:

* if frameName is not used, is win null?
* if frameName is used right away, does win as a value?

I just want to make sure they at least work synchronously.

**Comment by paulrouget** [comment]
Looking at Electron's code, I'm under the impression that they just don't even bother keeping a reference to the window. Which mean that they don't support `win = window.open()`.

Or maybe I'm looking at it wrong.

**Comment by paulrouget** [comment]
See https://github.com/mozilla/browser.html/issues/566#issuecomment-128833297

**Comment by Gozala** [comment]
I don't know what exactly Electron does have not actually tried it just read their docs. Docs at least seem to suggest that instance of `BrowserWindowProxy` is returned back http://electron.atom.io/docs/v0.30.0/api/window-open/

**Comment by Gozala** [comment]
I imagine there are different things that can be done in gecko and servo. Blocking an event loop seems like the worst possible thing to do IMO. I imagine it's will be ton of work in Gecko but maybe there is a hope in Servo to do the right thing, which in my opinion is:

- `w = window.open(...)` should be a `WindowProxy` instance for the window that maybe opened at some point in the future.
- `w.postMessage` should queue messages.
- `w.close()` should just destroy the proxy and break a connection with eventual window.
- `w.location = ...` should trigger an event on `iframe` to let browser implementer navigate or not.

It maybe even worth to consider changing `window.open` API in servo to `window.open(uri, callback) // => null`

**Comment by paulrouget** [comment]
> * w = window.open(...) should be a WindowProxy instance for the window that maybe opened at some point in the future.
> * w.postMessage should queue messages.
> * w.close() should just destroy the proxy and break a connection with eventual window.
> * w.location = ... should trigger an event on iframe to let browser implementer navigate or not.

All of that already works in Gecko. Gecko already implement and use a WindowProxy. The problem has nothing to do with gecko, but with the fact `window.open()` can return `null`.

> It maybe even worth to consider changing window.open API in servo to window.open(uri, callback) // => null

Or return a promise. Yes. That's ideally what should be done. But we can't change how the web was built and how it's used today.

**Comment by paulrouget** [comment]
> I don't know what exactly Electron does have not actually tried it just read their docs. Docs at least seem to suggest that instance of BrowserWindowProxy is returned back

Isn't that for `window.open` in the main process? This is a different thing.

**Comment by paulrouget** [comment]
I would argue that if webkit and gecko can't do that today, and that the current API works well for Gaia, there's no reason to try to fix that for browser.html. It's a browser.html issue that should be addressed at browser.html level.

If Reacts doesn't allow using a node creating by a 3rd party, I think it's better to fix React than the platform or the spec.

**Comment by gordonbrander** [comment]
@paulrouget it's not for the sake of react, it's so that you can manipulate iframe on the next animation frame.

**Comment by paulrouget** [comment]
> it's not for the sake of react, it's so that you can manipulate iframe on the next animation frame.

There's no reason to manipulate the iframe in the next tick other than being compatible with the way we render with React. We can just not wait for the next animation frame, and problem is solved.

The other solution is to block the child process until gc is complete or something slow, complicated and ugly like that. Let's not forget that the API is synchronous (this is a constraint we can't change, it's part of the spec, and it is use that way on the web), and here you're suggesting an async implementation.

And using a WindowProxy won't change anything.

I'm closing this issue here because the right answer is to not use RAF when getting the `mozbrowseropenwindow` event with a `frameElement`.
