### ISSUE TITLE
Pass config handle to mozbrowseropen event instead of frameElement 

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#566]
Currently `window.open()` causes `mozbrowseropen` event on an iframe with `event.detial.frameElement` that can't be used after animation frame (see #565). Attempt to workaround that limitation by stashing it to `document.head` and then reparenting on animation frame into appropriate location causes a crash (see #564).

Truth is this API is not only buggy but also really unfortunate as it does not play well with a popular libraries like react and is quite limiting as it is. As far as I can tell only reason to pass an iframe element with an event is to attach a specific configuration to it so that opener can remain connected to it. It would be much better if runtime stored that configuration / internal iframe implementation internally and exposed to a user a unique id for it that could be used by an embedder to pass that configuration to an iframe by assigning attribute with that id. In fact Electron seems to already do exactly that by passing `event.frameName` (see http://electron.atom.io/docs/v0.30.0/api/web-view-tag/#new-window)

**Comment by paulrouget** [comment]
I might be completely wrong because I don't know Electron, but I believe they have a very basic implementation of `window.open` *from a child process*. It basically works the same way we used the `mozbrowseropenwindow` event. You take the URL, create a new iframe, and that's it. There is no inter window communication system and there is no process management.

`frameElement` and `frameName` are not equivalent, as `frameElement` points to an existing window, whereas `frameName` points to nothing, it's just the name used in `window.open()` and maybe the `target`, and we actually support that in Gecko already: `event.detail.name`.

If I'm wrong (and again, I might really be, I haven't look too much), I'd be happy to look at how it works internally in Electron/Webkit.

**Comment by paulrouget** [comment]
Let's forget about the sync issue (discussed in #565) and let's focus on the id-over-frame proposal.

Gaia relies on this API, and it seems to work well for them.
What's special about us that makes it difficult to use?

**Comment by gordonbrander** [comment]
@Gozala should this be open still?

**Comment by Gozala** [comment]
@gordonbrander I think it should at least for now.

**Comment by Gozala** [comment]
> Let's forget about the sync issue (discussed in #565) and let's focus on the id-over-frame proposal.

Well it's hard to discuss the issues if we ignore some of them.


> Gaia relies on this API, and it seems to work well for them.

That does not mean that API is sane.

> What's special about us that makes it difficult to use?

1. Well one thing is that our update loop (a.k.a as event handling loop) is independent of a render loop, that is because we re-render only on animation frame. Such an API forces us to make an exceptions (that can cause race conditions) and re-render in the same turn of event loop.

2. Libraries like react, ember, angular all provide higher level abstraction over DOM, in other words application developer writes application logic and library deals with DOM manipulations. This API makes it difficult to use such libraries as you are forced to take over the DOM ownership and deal with an updates yourself.

3. More important problem is this API is a hack that was shoehorned onto iframes that were never designed for this. There is no single standard API that emits events providing you with an element that you have to use. That is because HTML is supposed to be declarative (even though it's far from it) and this is just so far from it on so many levels.

4. Special objects usually tend to be an indication of an unfortunate API. This is good example why is this iframe so special and different from the other iframes. Why can't I create a such an iframe ? The only reason is that two iframes need to be connected, so instead of solving problem of how do we expose an API to create connected iframes we ended up with special iframes that require special treatment otherwise they break.

**Comment by paulrouget** [comment]
I understand that using this API is not easy use. Sometimes we have to bend APIs to make the implementation possible.

If you come up with a better API which is actually possible to implement, I'd be happy to give it a try.

**Comment by Gozala** [comment]
Closing this issue as I don't believe we

**Comment by Gozala** [comment]
@bbondy Would you mind telling us how does Electron handles `window.open` calls, or more specifically how on can set up communication channel between opener and opened windows ? Gecko passes this `event.detail.frameElement` that is just terrible to work with I would really like if we could do something better for servo and insight from Electron side would really help.

I did picked a little at brave-laptop code base but could tell if that actually works or not. My guess is that `guestInstanceId` might be doing it somehow but could not find any docs or proofs of it anywhere.

Thanks

**Comment by bbondy** [comment]
Electron itself worked through a BrowserProxy which worked worse than the Graphene solution w/ `event.detail.frameElement`, it was removed here:
https://github.com/brave/electron/commit/dd628f9a3c23193ba59e101a0ebaa03a58279164

@bridiver implemented support here, which he'll upstream to atom/electron:
https://github.com/brave/electron/commit/58064872260cdec858e75c5f4737345a156b4833

He'll be able to answer better than I would.
He didn't need to dig into libchromiumcontent to get it working nicely.
See https://github.com/brave/electron if you want to clone.

**Comment by bridiver** [comment]
as @bbondy said in Electron they wrote their own window.open implementation in JS and used a BrowserProxy with some basic functionality implemented through ipc (atom/renderer/lib/override.js). We removed that layer and use the webkit/chromium code that is substantially more involved. The guestInstanceId is used to lookup the webContents (in the main process) and attach it to the renderer process through the render host after we create the new window. That is really just a result of the combination of our specific use case and the way the webcontents delegate callbacks work. Are you talking about cross-window scripting support or just async postMessage-style communication?
