### ISSUE TITLE
zoom on `event.detail.frameElement` throws

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#567]
Attempt to use `frame.zoom(n)` on `event.detail.frameElement` from `mozbrowseropen` event throws:

 `InvalidNodeTypeError: The supplied node is incorrect or has an incorrect ancestor for this operation.`

**Comment by gordonbrander** [comment]
@Gozala should this be closed?

**Comment by Gozala** [comment]
No it should be fixed in gecko.

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
