### ISSUE TITLE
setVisible on `event.detail.frameElement` throws

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#568]
Attempt to use `frame.setVisible(value)` on `event.detail.frameElement` from `mozbrowseropen` event throws:

`InvalidNodeTypeError: The supplied node is incorrect or has an incorrect ancestor for this operation.`

**Comment by gordonbrander** [comment]
@Gozala should this be open still?

**Comment by Gozala** [comment]
Yes it should be fixed in gecko.

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
