### ISSUE TITLE
Clicking on the location or hitting cmd-l should not open a new card

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#576]
If a tab is highlighted (blue ring), and I type in its address bar, I am expecting to change its url.

The current behavior makes a simple task very annoying: loading a new url in a tab require going back to the preview mode and close the old one.

And fixing url typo is now difficult too: I type "redit.com". I type "reddit.com". "redit.com" is still here.

**Comment by gordonbrander** [comment]
This is a bug. Per the spec, clicking the location bar or hitting `cmd l` should edit the current card url, not open a new card.
