### ISSUE TITLE
Show title in cards, not domain

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#578]
I have plenty of bugzilla tabs open. Not seeing the title makes it impossible to know which tab is the one I want to switch to.

**Comment by gordonbrander** [comment]
I think this may be a good idea.

Note that in general, Bugzilla workflow is an outlier... very different from the way we use most sites. We should be aware of this when making decisions so that we don't accidentally design for the 10% case.

**Comment by paulrouget** [comment]
How is bugzilla an outiler? That's true every time you open more than one page for a website. Isn't that a very common pattern?

At the moment, in Firefox, I have multiple tabs for github, french tax website, duckduckgo, imdb and reddit.

**Comment by gordonbrander** [comment]
@paulrouget my hypothesis is that `cmd click` is something that tech-savvy users know about, but many others do not. BZ, GH and Reddit are all websites that are difficult to use without `cmd click` and also attract the type of folks that would know about `cmd click`.

Exploring this hypothesis: if we think opening multiple pages for one website is an important feature, maybe the answer is to think about new ux approaches that surface it in a more natural way (i.e. experimenting with how/when we open tabs).

Like all hypothesis, this is obviously something we would want to test via experimentation.

**Comment by paulrouget** [comment]
> if we think opening multiple pages for one website is an important feature

I'm convinced this is an important feature. People who have more than 3 tabs are extremely likely to have tabs from the same domain.

Looking at my friend laptop (not at all tech-savy, she doesn't even know what I meant by "tab"), she has multiple facebook and yelp tabs open.

Then maybe these people would prefer to see the domain name instead of the title.

**Comment by gordonbrander** [comment]
Yup, we should think about how we can make this kind of thing simple to use.

**Comment by gordonbrander** [comment]
To circle back to the bug topic, the spec already says that screenshot cards should display title in header. We should definitely fix this.
