### ISSUE TITLE
In cards, screenshots should fit better

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#579]
For example, the screenshot of reddit.com, 20% of the right and the left is cropped out:

<img width="255" alt="screen shot 2015-08-12 at 04 00 15" src="https://cloud.githubusercontent.com/assets/373579/9215124/ab482e1a-40a6-11e5-8df9-3ef34d6806d4.png">

We should take a screenshot that fits better, or if it's not possible, align the screenshot on the left.

**Comment by gordonbrander** [comment]
Agreed. The problem is that we don't know where the content begins and ends, so we take a wide screenshot and then center it. This isn't great. What we really need is for the screenshot API to find the content and center on it, the way iOS and Android browsers do when loading a page on mobile.

**Comment by paulrouget** [comment]
> What we really need is for the screenshot API to find the content and center on it, the way iOS and Android browsers do when loading a page on mobile.

What do you mind "find the content"? Crop plain colors until we reach a non-uniform texture?

**Comment by gordonbrander** [comment]
@paulrouget I'm not sure what the algorithm is, but when you load a webpage on mobile, for example, it figures out how to size the page to the viewport using some heuristic of "show all the content and as little empty space to the left and right as possible).

Think about what we mean when we say "screenshots should fit better". We want content of the page not to get cut off. We want the left and right boundaries of the content to line up with the left and right boundaries of the card.

Perhaps we could experiment with taking screenshots at the width of the viewport, then setting the height via ratio to the width, then downscaling the image to fit the card?

**Comment by paulrouget** [comment]
> Perhaps we could experiment with taking screenshots at the width of the viewport, then setting the height via ratio to the width, then downscaling the image to fit the card?

Yes.

**Comment by gordonbrander** [comment]
@paulrouget it looks like the screenshot API will not give me a screenshot with dimensions larger than the viewport.

This is a problem because our viewport is landscape, whereas screenshots are portrait. If we want to show a screenshot that is a scaled-down version of the page, we need to be able to screenshot content outside of the viewport. The only other option is to cut off content awkwardly.

Do you know if this is something we can easily fix?

**Comment by paulrouget** [comment]
> Do you know if this is something we can easily fix?

As long as the page is long enough, yes.

I'll file a bug.

**Comment by gordonbrander** [comment]
No longer applies.
