### ISSUE TITLE
Reconsider not using stoplights as window controls

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#583]
browser.html is the only app that doesn't use osx window controls. It feels wrong. Can we go back to normal controls?

iirc, we used different controls because of the themes that might break them. Could we use stoplights when using white theme and foreground color (text color) when using other theme?

**Comment by paulrouget** [comment]
@gordonbrander what do you think?

**Comment by gordonbrander** [comment]
@paulrouget Worth considering. I like the glyphs, but there is an argument both for imitating the host OS, and for letting non-native controls look non-native.

There's a lot of work to get this looking right with color themes, which is one reason wht we removed the circles but kept the glyphs. I'd like to take another look at this after https://github.com/mozilla/browser.html/milestones/Developer%20preview%20%28Gecko%20Graphene%29. It would be a quick update.

**Comment by Gozala** [comment]
+1 On native controls, I never liked when APPS completely opt out of native look and feel of the os.

**Comment by gordonbrander** [comment]
We went back to stoplight controls.
