### ISSUE TITLE
B2G for browser.html should have its own pref file and its own shell.* files

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#59]
There are many prefs in b2g.js that we do not need. And also some prefs that are not safe enough for B2G Desktop (Simulator) that we want to enable for Browser.html (like ipc.tabs.enabled, APZC, ...).

Also, B2G Desktop comes with a pretty big `shell.js` file and desktop only scripts. I don't know how much of that is required.

@fabricedesre - what would you recommend?

**Comment by paulrouget** [comment]
Looking at the desktop scripts. I think we can remove them all. We might need screen.js. At least, we need to replace the script with something like `window.reiszeTo(500,500)`.

**Comment by fabricedesre** [comment]
I think we're gonna need a MOZ_HTML_BROWSER switch. I have a patch, just need to convince a build peer ;)
About shell.js being big, I'm not too worried, we'll do cleanup if we really face issues. I agree that desktop.js/screen.js are probably unneeded. Again, details in the bigger picture!

**Comment by paulrouget** [comment]
Bug 1134106.
