### ISSUE TITLE
Hitting enter on focused input in edit-web-view does not work

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#594]
@Gozala this looks like another regression. Hitting enter on focused input in edit-web-view does not show-web-view. I get a "too much recursion" error.

<img width="655" alt="screen shot 2015-08-13 at 16 54 42" src="https://cloud.githubusercontent.com/assets/58421/9264517/37c22018-41dc-11e5-8c7e-6c56718018ba.png">

**Comment by gordonbrander** [comment]
This line is causing `action` to be `false`:

<img width="1330" alt="screen shot 2015-08-13 at 17 08 23" src="https://cloud.githubusercontent.com/assets/58421/9264682/efee7352-41dd-11e5-9493-a718dba2da60.png">

**Comment by Gozala** [comment]
> This line is causing action to be false:

That's not really what's going in it's our debugger quirk. Fix is provided in the pull.
