### ISSUE TITLE
Experiment with improving zoom-in, zoom-out animation

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#595]
We had a pretty good animation at one point that would transform a screenshot. Maybe we can do something more like this?

**Comment by Gozala** [comment]
This probably depends on #577

**Comment by Gozala** [comment]
@gordonbrander assiging to you as I beleive you said you're working on this.

**Comment by gordonbrander** [comment]
No longer applies to `perspective-ui`.
