### ISSUE TITLE
Sometimes zoom-in animation gets stuck at a "most of the way" point

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#608]
Occasionally, when clicking on a tab, the webview will get stuck in a "not-zoomed-all-the-way-in" state. The transition doesn't complete. I'm guessing this is a platform bug, because I'm unsure how it would be possible for a CSS transition to get stuck. cc @paulrouget

**Comment by paulrouget** [comment]
Is it still happening with the new runtime?

**Comment by gordonbrander** [comment]
@paulrouget yes

**Comment by gordonbrander** [comment]
No longer applies.
