### ISSUE TITLE
Build for B2G for browser

### ISSUE THREAD

**Issue by Mte90** [mozilla/browser.html#61]
Is possible create a build of https://github.com/paulrouget/gecko-dev/compare/b2g-for-browser.html for the various platform?

**Comment by Mte90** [comment]
The repo link is changed https://github.com/paulrouget/gecko-dev/compare/htmlrunner

**Comment by Mte90** [comment]
any news for this?

**Comment by paulrouget** [comment]
Still WIP.

**Comment by paulrouget** [comment]
Happening in bugzilla. Bug 1115098
