### ISSUE TITLE
Performance: the location bar is repainted many times when switching from previews to webviews

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#611]
STR:
- enable paint flashing
- go to preview mode
- press ESC to go back to iframe
- see location bar flashing many times

**Comment by Gozala** [comment]
I noticed paint flashing on location bar when swiping cards in https://github.com/mozilla/browser.html/pull/617 but when I investigated location bar was not actually re-renderd so I wonder if that's an issue with paint flashing, renderer or maybe a react itself.

**Comment by paulrouget** [comment]
It's a problem with our zooming code. For some reasons, it requires painting the location bar several times.

**Comment by gordonbrander** [comment]
This issue is out of date.
