### ISSUE TITLE
Add a go-back button to the location bar

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#612]
I know that we want to use gestures and/or the context menu, but I believe the "going back" feature is too important to be hidden. How do you discover how to go back?

**Comment by paulrouget** [comment]
@gordonbrander what do you think?

**Comment by gordonbrander** [comment]
We should implement it as-designed first, and then assess.

**Comment by gordonbrander** [comment]
Update: we have designs for this now. Will implement simple version first, then adjust as necessary.
