### ISSUE TITLE
Suggestion list sometimes is shorter than expected

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#613]
So sometimes when you type things into address-bar you can get 3 suggestions instead of 6. What happens is following say you typed `fo` and you got 3 search suggestions and 3 history suggestions, then you typed `foo` so two new (search and history) queries were made. First we got response from search query so we updated 3 search results, then we got response from history query with no match and we dropped existing history suggestions & wind up with just three search suggestions.

What should have happened was that instead of updating 3 search results on first response we had to drop all previous suggestions with MAX number of new suggestions, but to do that we had to know those suggestions were for previous query which we are unable to do now because there is nothing in state that would let us do so.

To fix this issue we should update our suggestion engine to be able to handle this case more correctly.

**Comment by gordonbrander** [comment]
Cool. I think we can fix this one after we finish https://github.com/mozilla/browser.html/milestones/Developer%20preview%20%28Gecko%20Graphene%29.
