### ISSUE TITLE
Graphene freezes when it loses focus

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#616]
@paulrouget this seems to be a pretty consistent bug with the new larch build.

**Comment by paulrouget** [comment]
I can't reproduce :/

Does it happen when you click on a different window?
And by crash, you mean actual crash or frozen window?

**Comment by gordonbrander** [comment]
@paulrouget frozen window. It happens when I `ctl tab`.

**Comment by Gozala** [comment]
I can't reproduce it either

**Comment by gordonbrander** [comment]
Oddly, this has stopped happening for me as well. Maybe it was something in the JS? Closing for now. Will re-open if I can find steps to repro.
