### ISSUE TITLE
Why are the tabs RTL and not LTR?

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#621]
The "+" button is on the right, the "Cmd+T" is a right-oriented binding, all the browsers I know use LTR, iOS is also moving to LTR previews.

I think we'd be better with regular LTR ordering.

@gordonbrander thoughts?

**Comment by gordonbrander** [comment]
Maybe. We've gone back and forth on this. The summary is if you match browsers, `ctl tab` feels different. If you match OS, tab order feels different. I'm open to experimenting. In the new UI it's pretty easy to reverse.

**Comment by gordonbrander** [comment]
Does not apply to `perspective-ui`.
