### ISSUE TITLE
Introduction of new actions requires cascading changes

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#625]
With typed-immutable every field is typed so when we say `Record({ action: Union(X, Y) })` it will only accept actions of `X` and `Y` types. Problem is if we add new action to say `WebLoader` we need to update `WebView.ByID` etc.. If we do forget to what happens is actually really bad, action is interpreted as some other type of action in fact it's usually `WebView.Close({...})` as it's first in the union type.

We should define union types for each component and then create union types out of those union types. That way changes to `WebLoader` won't require any changes to `WebView`.

**Comment by gordonbrander** [comment]
I'm confused... it sounds like you're saying that typed-immutable "coerces" types?

**Comment by Gozala** [comment]
> I'm confused... it sounds like you're saying that typed-immutable "coerces" types?

Here is an example of two types:

```js
const X = Record({x: 0}, 'X')
const Y = Record({y: 0}, 'Y')

const C = Record({ data: Union(X, Y) })

C({data: {x: 2}}) // => Typed.Record({data: Union(X, Y)})({ "data": X({ "x": 2 }) })
C({data: X({x: 5})}) // => Typed.Record({data: Union(X, Y)})({ "data": X({ "x": 5 }) })
C({data: Y({y: 3})}) // => Typed.Record({data: Union(X, Y)})({ "data": Y({ "y": 3 }) })

C({data: {y: 2}}) // => Typed.Record({data: Union(X, Y)})({ "data": X({ "x": 0 }) })


// Introduce new type but forget to extend C type signature
const Z = Record({ z: 0 })

C({data: Z({z: 5})}) // => Typed.Record({data: Union(X, Y)})({ "data": X({ "x": 0 }) })
```

**Comment by Gozala** [comment]
Also note that `{y: 2}` is valid duck typed X and Y instance but given that `X` is first type in the union `C({data: {y: 2}})` interprets it as `X` even though you may mean `Y`.

**Comment by gordonbrander** [comment]
wow that seems like a big mis-feature for an algebraic type system

**Comment by Gozala** [comment]
> wow that seems like a big mis-feature for an algebraic type system

Those type systems usually don't allow duck typing or default fields so they don't run into same issues.

**Comment by gordonbrander** [comment]
No longer relevant. We now use Flow.
