### ISSUE TITLE
App should start only after build is finished

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#644]
This requires some digging into [gulpsj](http://gulpjs.com) which I'm not at all familiar with. As far as I can tell gulp runs dependent tasks concurrently so sometimes browser app will lunch before dist is created and there for it fails to load. It should first finish build and only then lunch an app.

**Comment by gordonbrander** [comment]
@Gozala I believe this is the case, no?

**Comment by gordonbrander** [comment]
This is done (see above).
