### ISSUE TITLE
Design round 3

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#655]
What we've learned from synthesis UI:

- Simplifying the UX works
- Color themes feel good
- 27px header is just right. It fades out of the way.
- We still haven't nailed tabs. It could be that small changes will make a big difference. I also have some alternative ideas I want to explore.
- We need more animation.

Focus on animations and riffing on tabs.

**Comment by paulrouget** [comment]
To me, the main question is: *should we show the tabs all the time, or only after a user action?*

Until now, our implementations were hiding tabs by default. It looks nicer, but it's not practical. As I said in https://github.com/mozilla/browser.html/issues/622:

> * Getting to the right tab is slow. Before, I was spotting the tab to go to with my eyes and then clicked/ctrl-tabed to it. Now I have to get to preview mode first and search for it, which is slow and hide my current page.
> * Often I don't want to select a new tab, but just have a quick look at what I have open. Knowing what is open used to be a very simple task, now it's not. I'm basically losing context every time I want to know what I have open.

**Comment by julianrichen** [comment]
You could take the Gnome Web approach: http://imgur.com/a/HK2PL

Hide the tab bar until the user opens a new tab, then the tab bar slides down and shows the tabs.

Not sure if you are taking suggestions from the community but having the tabs visible all the time would better imo. Making it an extra step to multitask would bad for productivity.

**Comment by gordonbrander** [comment]
We already have UX designs that show tabs all the time. We know they will work well enough, because the approach has been tried. Our goal for this sprint is to find out if we can do better.

Remember: everything we do is a hypothesis. Rather than making a blanket statement about what won't work, we're asking "what if it does work?". Design is a delicate balance of factors. Small differences can make a big difference.

Experiment with cheap prototypes (like the ones I'm working on for this sprint). Experiments generate new ideas. Often things you think won't work end up working. Then you narrow those ideas down until they're perfect. If you don't generate ideas before you judge, you'll always end up doing what's already been done.

![ideo_diverge_converge_process](https://cloud.githubusercontent.com/assets/58421/9674561/e6c9b450-5266-11e5-881d-5c41e4f76654.jpg)

Anyway, the moral of the story is, try crazy things, you might get a crazy reward — but make sure you have a backup plan. And we do :D

**Comment by paulrouget** [comment]
I haven't said we should not try new things or suggest to go for the traditional approach. I was just asking a question.

> We already have UX designs that show tabs all the time

Which was a lot like traditional tabs. A backup plan.

"Tabs on screen" doesn't have to be like traditional tabs.

"Crazy things" doesn't have to be hiding tabs.

And part of the iterating/experimenting process is learning. I've learned that having to do a user action to access the tabs is not working so well.

Happy to experiment again with the cards mechanism, as long as we try to address this multitasking issue.

**Comment by gordonbrander** [comment]
I'm open to any and all explorations. I'm building a few static HTML prototypes. I don't want to burn too much time trying concepts in the actual codebase. Dynamic mockups should be a quick way to smoketest a few ideas.

**Comment by Gozala** [comment]
Just to give a different perspective on this subject. To me traditional tabs did not solved neither of these two issues:

> - Getting to the right tab is slow. Before, I was spotting the tab to go to with my eyes and then clicked/ctrl-tabed to it. Now I have to get to preview mode first and search for it, which is slow and hide my current page.

With a number of tabs I tend I have open I rarely can spot the tab I need to go to. In fact ordering tabs by recency matched a lot better my workflow in term of jumping to where I need to. I also find current dashboard to be more effective way to discover a tab I need to switch to as in traditional tabs I usually would end up jumping back and forth between tabs, with card view I tend to scroll around to find a card I'm looking for still not great when number of tabs is large but I find it to be better than traditional tabs. I do really wish I could filter out card by typing though.

> - Often I don't want to select a new tab, but just have a quick look at what I have open. Knowing what is open used to be a very simple task, now it's not. I'm basically losing context every time I want to know what I have open.

It is probably just that my tab bar is a mess so I don't get much overview of what's open by looking at it also often times I need to scroll in the tab bar to discover somewhat relevant one. I do prefer cards for this task as well as it actually gives me some overview with a help of colors and descriptions. I'm not entirely happy that we just use one row as we see less content and require more scrolling, although it could be that more rows would add more noise and don't end up being better.

P.S.: When I'm trying to get an overview I don't tend to care about loosing a context / current tab as it's typically when I am switching a context anyhow.

**Comment by gordonbrander** [comment]
Ongoing work for this prototype is happening in `master` https://github.com/mozilla/browser.html/wiki/perspective-ui.
