### ISSUE TITLE
Revisit preview's code

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#657]
I'm trying to make the preview render properly with Servo.

But looking at the layout, it's very complex.

* can we have one global wrapper, not 2?
* The top wrapper should not have any padding (`padding-bottom`)
* the scroller overflows to hide the scrollbar. This is a useless workaround. Just add the class `moz-noscrollbars` to hide them.
* remove all the useless `overflow:*`.
* do not use `z-index` if it's not useful
* with is there a `transition` on `width`?
* use `height:100%` only if it's useful
* why do we use non-static positioning in the card? Is it just for the favicon?
* can we have only one wrapper per card?
* I don't understand that:
```
// This is important. We need previews to make space around itself.
// Margin doesn't play well with scroll -- the right-hand edge will get
// cut off, so we turn on the traditional CSS box model and use padding.
```

**Comment by paulrouget** [comment]
The most important, at least for Servo, it's to remove as many `overflow` properties as possible.

Could someone look at this?

**Comment by Gozala** [comment]
> - can we have one global wrapper, not 2?
- The top wrapper should not have any padding (padding-bottom)
the scroller overflows to hide the scrollbar.
- This is a useless workaround. Just add the class moz-noscrollbars to hide them.

I believe I introduced second wrapper to hide the scrollbar. I did not knew about `moz-noscrollbars` at a time. I would personally prefer not to use proprietary extensions like `moz-noscrollbars` when possible although if this is blocks servo that's definitely not worth it.

> - remove all the useless overflow:*.
> - use height:100% only if it's useful
> - can we have only one wrapper per card?

Each card is wrapped in a container that has full height and receives swipe events it also has overflow none as when card is swiped out we would not want to see a scrollbar. Card itself can't receive swipe events cause once it's swiped out of mouse pointer it no longer receives events. I could not think of any better way to achieve that.

> - with is there a transition on width?
> - why do we use non-static positioning in the card? Is it just for the favicon?
> - I don't understand that:

>>  ```js
>>  // This is important. We need previews to make space around itself.
>>  // Margin doesn't play well with scroll -- the right-hand edge will get
>>  // cut off, so we turn on the traditional CSS box model and use padding.
>> ```

I am not sure about these but @gordonbrander may know, I believe he's also an author of that comment.

**Comment by paulrouget** [comment]
>  I would personally prefer not to use proprietary extensions like moz-noscrollbars when possible 

Let's be pragmatic. One class name is much better than making the layout more complex. We can add this CSS too: `::scrollbar {width: 12px}` (not supported by gecko).

>> remove all the useless overflow:*.
>> use height:100% only if it's useful
>> can we have only one wrapper per card?
> 
> Each card is wrapped in a container that has full height and receives swipe events

ok.

> it also has overflow none as when card is swiped out we would not want to see a scrollbar

This one makes sense. That are other uses of `overflow` that don't seem necessary.

> Card itself can't receive swipe events cause once it's swiped out of mouse pointer it no longer receives events. I could not think of any better way to achieve that.

You're right.

**Comment by paulrouget** [comment]
Also: https://github.com/mozilla/browser.html/issues/661

**Comment by gordonbrander** [comment]
Does not apply to `perspective-ui`.
