### ISSUE TITLE
Allow editing url of selected suggestion

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#659]
Based on https://github.com/mozilla/browser.html/pull/656#issuecomment-138724186

> Interaction bug:

> Arrow down to top hit
Select all (cmd a) and then start typing
What should happen: blow away old text and insert new text.
What happens: the url of the top hit stays in the input even as you type. Cursor jumps around.

**Comment by gordonbrander** [comment]
The interaction described is what we want, but this bug is out of date. Does not apply to current codebase.
