### ISSUE TITLE
Text selection is broken (content)

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#66]
It often lags behind the mouse, sometimes only shows when you release the mouse, and other times does not select at all.

**Comment by gordonbrander** [comment]
Also copy/paste doesn't work. This is a bummer because it's preventing me from daily dogfooding. It's no fun to find an awesome quote or link and then have no way to copy it.

I wouldn't call this a high-priority issue, but if it is as easy as toggling a Gecko pref, we might want to take a look at it.

**Comment by paulrouget** [comment]
Gecko issue. I'll look at this.

**Comment by paulrouget** [comment]
(e10s issue)

**Comment by paulrouget** [comment]
Appears to work properly with B2G Desktop + e10s + Gaia.

**Comment by paulrouget** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1154168
Fixed with workaround: f1f0b16715d1ef0bd09dfe9a9d7775749691a101

**Comment by gordonbrander** [comment]
@paulrouget did this also fix copy/paste, or should we open a follow-up bug?

**Comment by paulrouget** [comment]
@gordonbrander see #137 and bug 1154182
