### ISSUE TITLE
`gulp application` crashes on current larch

### ISSUE THREAD

**Issue by chrmod** [mozilla/browser.html#671]
```
chrmod@rebis:~/Projects/opensource/browser.html* build-typo-fix$ gulp application
[22:28:32] Requiring external module babel-core/register
[22:28:34] Using gulpfile ~/Projects/opensource/browser.html/gulpfile.babel.js
[22:28:34] Starting 'application'...
[22:28:34] Finished 'application' after 4.51 ms
*** UTM:SVC TimerManager:registerTimer - id: xpi-signature-verification
1442608114392	Marionette	INFO	Marionette enabled via build flag and pref
```
Graphene is being run, but it instantly crashes without meaningful logs. 

Graphen build include recent fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1205633

**Comment by chrmod** [comment]
I'm being able to run:
`gulp build-server`
and then
`./mach run --start-manifest http://localhost:6060/manifest.webapp`

Is it sufficient for testing and development?

**Comment by gordonbrander** [comment]
I've not encountered this problem, but Gecko Graphene merged with `mozilla/central` some time ago, so that may be the root cause. Here are the up-to-date build instructions https://github.com/mozilla/browser.html/wiki/Building-Graphene-%28Gecko-flavor%29.

**Comment by Gozala** [comment]
Feel free to reopen if yo have more details on how to reproduce.
