### ISSUE TITLE
Make our renderer swappable

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#673]
Keeping 60FPS with React seems to be little tricky specially when dealing with animations. There are several ways we could improve on that. On the other hand there has being explosion of libraries that take same approach as react in terms of "virtual dom" while improving on performance. For example as you can read in this article http://elm-lang.org/blog/blazing-fast-html [virtual-dom](https://github.com/Matt-Esch/virtual-dom) library performs >2x faster on a todo-mvc application than react. We should try to factor out renderer such that it would be a backend that we could swap. That would enable us to try virtual-dom instead and maybe get to stable 60fps and if that's not enough create a hand optimized branches for animations etc...

**Comment by Gozala** [comment]
At the moment I have split our reflex  library into just **reflex** and **reflex-react-renderer** libraries and have a work in progress **reflex-virtual-dom-renderrer* library. Initial result of new renderer is very promising, but I still need to finalize it and publish all of these. At the moment I'm still finishing examples that includes effects and animations #674 as soon as it's done I'm going to publish all these pieces.

**Comment by gordonbrander** [comment]
This is done.
