### ISSUE TITLE
Add page context menu

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#7]
_From @SebastianZ on December 10, 2014 7:2_

Right-clicking a page currently doesn't do anything. It should open the context menu.

Sebastian

_Copied from original issue: paulrouget/firefox.html#20_

**Comment by paulrouget** [comment]
We need to handle the `mozbrowsercontextmenu` event. https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowsercontextmenu

**Comment by paulrouget** [comment]
We need to expose a way to show native panels from htmlrunner.

**Comment by paulrouget** [comment]
No native panel. Let's go for a floating `<div>`.

**Comment by paulrouget** [comment]
_From @SebastianZ on December 22, 2014 12:28_

Or better a [`<menu>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu). Though that probably [requires platform support](https://bugzilla.mozilla.org/show_bug.cgi?id=897102).

Sebastian

**Comment by paulrouget** [comment]
`<menu>` describes the content of the menu. It's not a layout container.

**Comment by paulrouget** [comment]
As in, a `<div>` will show what is described by the menu markup.

**Comment by Gozala** [comment]
This looks like a dup of #29 in fact it's other way round, but later has more comments so closing this one.
