### ISSUE TITLE
Javascript files should not be in node_modules

### ISSUE THREAD

**Issue by KevinGrandon** [mozilla/browser.html#74]
Unless they are pulled in via npm...

Having javascript files inside the node_modules folder breaks a lot of existing tooling for the web. A lot of editors and tools prevent recursion into the node_modules folder for things like searching and file autocomplete. This also breaks grepability - it's very difficult to search for things if there are several modules at the same level of the code.

My recommendation is to move them into a js/ folder, or pull them in with npm if they are truly meant to be modules. I am not aware of the original intent of having them in the node_modules folder though, so opening this issue up for discussion. @paulrouget @Gozala

**Comment by paulrouget** [comment]
+1 @Gozala ?

**Comment by KevinGrandon** [comment]
I've opened a pull request here if you guys think this is a good idea: https://github.com/mozilla/browser.html/pull/75

**Comment by Gozala** [comment]
My original intent was to move parts of the implementation into separate packages, but this clearly proved to be a bad way to go about it. So I do agree let's move these files out of `node_modules`.

That being said there are few pull requests I'd like to merge before going ahead with that, so people won't have to deal with this wrong decision.

**Comment by KevinGrandon** [comment]
Seems like this was done here: 35f161906c8bfcd72e1a100edd213a31c8246f8c
