### ISSUE TITLE
Closing a tab sometimes results in no webview being shown

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#777]
I'm not sure what the STR are, but I think it has to do with closing before an animation completes?

<img width="938" alt="screen shot 2015-12-11 at 11 30 17" src="https://cloud.githubusercontent.com/assets/58421/11753568/aa4ad4c8-9ffa-11e5-808d-066f44e06faa.png">

**Comment by Gozala** [comment]
I believe it was fixed by #795. Please reopen if you're able to reproduce.
