### ISSUE TITLE
Creating new tab: old tab shows until new tab loads

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#778]
1. Open a page ("Webview A")
2. Open a new tab (`cmd t`)
3. type a url
4. hit enter ("Webview B")

What happens: `create-webview` mode disappears. "Webview A" is shown until "Webview B" renders.
What should happen: "Webview A" should not be shown. If "Webview B" is not ready, we should show whitespace.

**Comment by Gozala** [comment]
I believe this was fixed by #795
