### ISSUE TITLE
Add scrollbox to tab bar if tabs don't fit

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#8]
_From @SebastianZ on December 10, 2014 7:19_

The tab bar should add a scrollbox if the tabs don't fit into the window.
![Tab bar scrollbox](https://cloud.githubusercontent.com/assets/958943/5372192/2427172e-8045-11e4-8740-61f63a6c188d.png)

Sebastian

_Copied from original issue: paulrouget/firefox.html#21_

**Comment by gordonbrander** [comment]
No longer applies. Closing for now.

**Comment by SebastianZ** [comment]
May I ask why this and #6 and #9 do no longer apply? I need to admit that I didn't follow the project's progress lately.

Sebastian
