### ISSUE TITLE
Tab shade should only show if > tab

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#81]
Hovering over the URL bar should only show tab shade if > 1 tab exists.

**Comment by Gozala** [comment]
Worked under #87

**Comment by Gozala** [comment]
Fixed by #87 @gordonbrander and I chatted what should be a behavior of tab key if there is only one tab,  right now it does nothing, but @gordonbrander if you want to change it I'd suggest separate issue for that.

**Comment by gordonbrander** [comment]
You're right. This was a bad idea. My apologies. I'll open a new bug to change behavior.
