### ISSUE TITLE
Add fallback screenshots

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#83]
Per https://github.com/mozilla/browser.html/issues/45, we have clever ideas about how to provide something better than a screenshot for website tiles. However, we still need screenshots as a fallback.

**Comment by Gozala** [comment]
I can take this one, but will leave it open in case someone else can get to it sooner. I'd be curious what would be a size of screenshot we would be interested in taking. There is also an interesting challenge in deciding weather we should load page to make a screenshot of it or if we should request a screenshot when page is loaded ? Not that currently all tabs that isn't selected are set to invisible there for deprioretizing their loading.

**Comment by Gozala** [comment]
I have work in progress patch here at #88

**Comment by gordonbrander** [comment]
Regarding screenshot size:

- Tab strip screenshot size is `100x62.5` software px
- At retina size, `200x125`

Aspect ratio is `16:10`. If screenshot sizes will be hard to change in future, we should go bigger. I've got some dashboard comps that use `320x200`.

**Comment by gordonbrander** [comment]
What I learned from trying this out:
- It's not a big deal that thumbnails have to wait until page load.
- The tab strip is hidden when you hit enter, so you seldom see this state.
- By the time I go back to the tab strip, thumbnail is almost always ready
- We can create a "tab image not loaded yet" style (with icon)
- If we also cached thumbnails, this would essentially be a non-issue
- We might want to think about "zooming in" on the top left 0.3 of the thumbnail rather than trying to fit the whole page. It's small!

What should change:
- Hard-coded tiles should win. Screenshots should always be last fallback.

cc @Gozala

**Comment by gordonbrander** [comment]
One more small ask: can we fade in screenshots when they are rendered?

**Comment by gordonbrander** [comment]
Also, I see a flash of broken image icon. We should get rid of this.

**Comment by Gozala** [comment]
Fixed by #220

**Comment by gordonbrander** [comment]
![money](https://cloud.githubusercontent.com/assets/58421/6624090/49f12150-c8a4-11e4-8de9-f8020cec5e98.gif)
