### ISSUE TITLE
Use input event

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#834]
input events are now supported in Servo. We should remove the `keyup` workaround.

**Comment by Gozala** [comment]
@paulrouget I still don't seem to get `input` events I'm afraid on the latest build from you.

**Comment by Gozala** [comment]
This also breaks #863 on servo

**Comment by Gozala** [comment]
It turns out it's not that `input` is not dispatched, it's that it does not propagate. Submitted following issue for that: https://github.com/servo/servo/issues/9574
