### ISSUE TITLE
Some sites are rendered as if on mobile

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#84]
We have a few glitches that seem like they are caused by left-over B2G prefs:

- Some websites serve up a "mobile mode". Maybe a UA problem?
- We override the stylesheets of some websites and enlarge the text. Mobile sometimes does this to prevent text from being too small to read on small screens, but it obviously isn't right here.
- Text selection has Firefox OS behavior. Carats are Firefox OS. Also see https://github.com/mozilla/browser.html/issues/66 -- probably related.

**Comment by fabricedesre** [comment]
Are you using the graphene runtime? 
Your user agent should be similar to: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 (go to http://whatsmyuseragent.com/ to check).

**Comment by paulrouget** [comment]
Works for me with Graphene.
