### ISSUE TITLE
Reduce the number of node dependencies

### ISSUE THREAD

**Issue by nt1m** [mozilla/browser.html#847]
It takes *a lot* of time to install the node dependencies on a slow network.

**Comment by nt1m** [comment]
I also get a lot of NOENT errors when doing npm install

**Comment by nt1m** [comment]
Forget the NOENT errors, goes away when I use sudo

**Comment by Gozala** [comment]
@nt1m we don't have that many dependencies & they all are fairly small:
https://github.com/mozilla/browser.html/blob/master/package.json#L28-L34

We do have bunch of `devDependencies` & some pretty large ones, but you don't have to install them unless you plan on hacking on browser.html itself. You can avoid installing dev dependencies as described in readme:

```js
npm install --no-optional
```
