### ISSUE TITLE
Add close button to tab when hovering

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#85]
Per comp.

**Comment by Gozala** [comment]
@gordonbrander should we use some image for displaying that close button, or is there anything in font we could use ?

**Comment by gordonbrander** [comment]
I used the icon font in comp.

**Comment by gordonbrander** [comment]
Closed by https://github.com/mozilla/browser.html/commit/7e2b07493eae1fab807deb0f514c4973e7265a1c
