### ISSUE TITLE
Add proper styling to history buttons

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#9]
_From @SebastianZ on December 10, 2014 7:32_

The history buttons currently don't look like in the normal Firefox.
Here's how they should be styled:
![History buttons disabled](https://cloud.githubusercontent.com/assets/958943/5372330/4582bc00-8047-11e4-9aca-dfc245f2fc5d.png)
![History button Back](https://cloud.githubusercontent.com/assets/958943/5372335/4e0e2e9a-8047-11e4-901e-7651ea1e4ebc.png)
![History button Forth](https://cloud.githubusercontent.com/assets/958943/5372336/543c75b0-8047-11e4-8fff-a87881a0b309.png)
![History buttons Back and Forth](https://cloud.githubusercontent.com/assets/958943/5372339/5a5783f4-8047-11e4-97cb-aec03c7f8091.png)

A few points on this:
- The buttons should be connected with the Awesome Bar.
- The Back button should be big and round.
- The Forth button should hide when you're at the end of the history.

Sebastian

_Copied from original issue: paulrouget/firefox.html#22_

**Comment by daleeidd** [comment]
I like how they are currently. Perhaps, we could have the above as the default, the current one as an optional theme, and add the developer edition styling as another optional theme?

**Comment by paulrouget** [comment]
Not relevant anymore.
