### ISSUE TITLE
When tabstrip is visible, it should be impossible to scroll `<main>`

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#91]
STR:
- show tabstrip
- scroll when mouse is hovering the navbar

![screen shot 2015-02-18 at 11 01 56](https://cloud.githubusercontent.com/assets/373579/6245312/92d541ce-b75d-11e4-8345-bd3c6cf2b05a.png)

**Comment by gordonbrander** [comment]
Before we can fix this issue, we will have to solve the problem of showing the location bar without moving the content position (same issue as #96).

**Comment by Gozala** [comment]
I believe with a changes for #82 it's impossible to reproduce this, as strip get's hidden as soon as you release keys.

**Comment by gordonbrander** [comment]
No this can still be reproduced:

1. Mouse over location field. Tab strip shows.
2. Scroll

The fundamental problem is that it is currently possible to show the tab strip without showing the title bar. This is true for any state in which we are not at the top of the page.

1. Scroll page
2. Hit `ctl+tab`

You will see exactly the state shown above.

**Comment by paulrouget** [comment]
So there's 2 things to do here:

1. forbid scrolling from the mouse is hover the navbar or forbid scrolling when the tabstrip is visible. I think the first option is better. Scrolling while hovering the navbar should do nothing
2. when should the tabstrip, should the navbar

And of course, 2 requires #96.

**Comment by paulrouget** [comment]
Fixed. 11054c1852ae471653ed806469e9284daf807eda
