### ISSUE TITLE
Show title bar when mousing over hotzone

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#96]
When you mouse toward the title bar and pass over the hot zone, the title bar should slide down. Content visual position should not change.

The hotzone should be 100% the width of the window. Let's start with a hotzone that's 200px high and keep it easy to tweak so we can tune for the right size.

**Comment by paulrouget** [comment]
I will take care of that. I'll try to hack something to synchronize chrome and content scrolling to translate the titlebar back in the viewport.

**Comment by paulrouget** [comment]
This is what I tried:
- expose scrolling to the browser api (patch for the record: https://gist.github.com/paulrouget/e5acbe78d0e4cde5e992 I didn't manage to make it synchronous yet)
- scroll `<main>` by `+x` and content by `-x`

It flickers pretty badly, and of course, animation is super bad.

No surprise, the call is async and go through IPC.

I could make it sync, but that would change that we have to go through `main process -> (DOM call) -> child process -> scroll -> compositor (main process)`.

I see 2 options:
- make it possible at the compositor level to scroll `<main>` and keep the position of the content
- find a different mechanism to hide/show the navbar, something not based on scrollgrab + snap points

**Comment by paulrouget** [comment]
So I've been experimenting with different approaches. Sadly, to get anything to work properly, we need to track the scroll position of the content, which only works if APZC is enabled. But APZC is really broken on Mac.

No matter what we do, it won't be an optimal solution.

So we can, either, give up on this feature for now until the platform allows us to do that (see http://bugzil.la/1138896, http://bugzil.la/1137872 and https://groups.google.com/forum/?fromgroups#!topic/mozilla.dev.platform/K_NhNWVKOPI). Also, waiting for APZC will make our life easier.

Or we can build a temporary patch.

Here, 2 approaches:

1. do not base this mechanism on scroll position. Show/hide the navbar if we're in the hotzone or not. Scrolling won't hide the navbar.
2. we do implement the double-scroll thing. Every time the navbar shows up, the animation will be choppy. This will also require a platform patch (we have it, but it will need reviews, not sure it will ever land).

**Comment by gordonbrander** [comment]
3. A temporary fix where we render 2 title bars: one at the top, one `position: fixed` above the screen. We show the `position: fixed` title bar when mousing into the hotzone. This obviously will cover `position: fixed` elements on the page, but could be a good temporary approach while platform gets fixed.

**Comment by gordonbrander** [comment]
I'm not keen on `1` because it would involve moving the whole contents of the screen down. This is a problem. Imagine you're trying to mouse over a link that happens to be in the hotzone and it suddently jumps out of your way. It's also a lot of visual movement for such a small change.

**Comment by paulrouget** [comment]
My 1) is what you describe as 3).

This can't work as there's no way to dismiss the 2nd navbar (or whatever mechanism you used) once it appears. Only 2 options: hide only if you leave the hotzone (not on scroll), hide on scroll, but enable APZC, with all the bugs we know.

**Comment by gordonbrander** [comment]
So would `1` overlap the web content (`position: fixed`) or move it down (`transform: translateX(...)`)? Will in-page nav bars be covered?

**Comment by paulrouget** [comment]
Yes. `transform:translateY`. Content will be covered by the navbar. I don't think it's a problem for now.
But the problem is not that, the problem is there's no way to dismiss the scrollbar with scroll events.

(In-page navbars?)

**Comment by gordonbrander** [comment]
Option 3) is to leave things as they are (hide/show on scroll w/o hotzone) until platform fixes land (~1mo?)

**Comment by paulrouget** [comment]
@gordonbrander Here is what I managed to do so far: PR #188 (please comment here, issue #96). You need the syncScroll build. You'll see that it's jumpy, but it implements the expected behavior. Let me know if it is what you have in mind.

**Comment by gordonbrander** [comment]
@paulrouget I think we should move forward with https://github.com/mozilla/browser.html/pull/188, but first I need to understand a couple of things:

- Is the implementation approach a big departure from what we will do once we get platform support? Will we be able to smoothly change code once we get platform support, or will it be a big refactor?
- Will this cause the interface to break in the "official" build, or will we update the "official" build?

My rational:

- This is not a giant screen flicker. A 2px jump/back is minor jank. Not shippable, but understandable in an alpha product.
- The story is the same whether we have it or not: we will have to explain that it will work when we have better platform support.
- I accidentally used it without thinking! I went to move the window and by the time my mouse got there, the title bar was ready for me. This is exactly the type of interaction I hoped for.

**Comment by paulrouget** [comment]
> Is the implementation approach a big departure from what we will do once we get platform support? Will we be able to smoothly change code once we get platform support, or will it be a big refactor?

Actually, there will be no code changes at all. #188 is the *right way to do it (tm)*. But we need to fix the platform to achieve a smooth animation.

> Will this cause the interface to break in the "official" build, or will we update the "official" build?

No. We can land #188 and it won't break the normal behavior. #188 tests first if the new API I introduced in the special build is present or not.

Ok. Let me polish #188 and we land it.

**Comment by gordonbrander** [comment]
Out of date.
