### ISSUE TITLE
Allow website to override themes and thumbnails via <meta> tag

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#99]
Builtin themes and thumbnails should be fallbacks. We should allow a website to expose themes and thumbnails via `<meta>` tags.

**Comment by gordonbrander** [comment]
Other things we could leverage:
- apple-touch-icon
- [oembed](http://www.oembed.com/)
- favicon.png / favicon.ico
- Screenshot thumbs
- Grab a hero image from the page (largest image?)
- Facebook opengraph
- `<link rel="image_src" href="http://i.imgur.com/4clqUdj.jpg"/>` (Facebook)
- Twitter card meta
- Windows8 meta tags: `msapplication-TileImage`, `msapplication-TileColor`

One fallback approach:

- Use a meta tag if present
- Fallback: designed graphic from web service
- Fallback: grab a hero image via FB open graph or Twitter card meta or Win8 tile graphics
- (maybe) generate image from apple-touch-icon and theme-color, etc
- Fallback to screenshot thumb

**Comment by gordonbrander** [comment]
I think this is out of date.
